### ISSUE TITLE
Feature request: paste to different page

### ISSUE THREAD

**Issue by ldecicco** [ddvk/remarkable-hacks#1]
Currently a big limitation of reMarkable xochitl application is that it is not possible to paste to a different page. Would it befeasible to implement this?

Thanks a lot in advance for your great contributions!

**Comment by ddvk** [comment]
If I find a way sure, but it's a bit difficult for me.I think they are planning on implementing it, though

**Comment by ldecicco** [comment]
Thanks a lot for considering!

**Comment by ddvk** [comment]
this got finally implemented in 2.1.0.6, so i'm closing thie issue :>
