### ISSUE TITLE
files in root home directory

### ISSUE THREAD

**Issue by AaronDavidSchneider** [ddvk/remarkable-hacks#10]
First of all,

thankyou for these awesome tools! I really enjoy using them!
I have one question tough:
In my remarkable home directory (`/home/root`) appeared some files which I don't know if they belong there:
```
-rw-r--r--    1 root     root         39305 Mar  4 07:34 patch_01
-rw-r--r--    1 root     root         43121 Apr  7 16:09 patch_02
-rwxr-xr-x    1 root     root       4157340 Apr  7 16:09 xochitl
-rwxr-xr-x    1 root     root       4153248 Mar  4 07:34 xochitl.2106
-rwxr-xr-x    1 root     root       4157340 Apr  7 16:09 xochitl.2113
```
Installed the patches using 
`sh -c "$(wget https://raw.githubusercontent.com/ddvk/remarkable-hacks/master/patch.sh -O-)" ` and hitting `Ctrl`+`C`
Is the homedirectory really the path where the binaries belong to?

Thanks again! Great work!

**Comment by 1094** [comment]
Also, if I decide not to use the patch anymore, can all of files listed removed?

**Comment by ddvk** [comment]
those are the backups of the original binary, used for reapplying the patches

**Comment by AaronDavidSchneider** [comment]
Fixed in latest commit
