### ISSUE TITLE
Request - closing of menus / buttons by finger tapping outside of them

### ISSUE THREAD

**Issue by Tridens92** [ddvk/remarkable-hacks#101]
Would it be possible to close tools / menus by clicking outside of them rather than only on them?  Examples:

1) I often bring up the Recent File menu by accident (often by inadvertently activating the long-click of the Home button with my palm).  Then, if I don't want to change the current open document to one in the recent menu, I have to navigate back to some other way of closing the menu (like clicking the "R").  It would great just to tap outside the Recent File menu and it would close.

2) Incidentally, on (1) above, it would also be great if a subsequent long-press of the Home button when the Recent Files menu is open would close it.

3) Same is true of sub-menus on tools.  Right now, if you open a sub-tool and then write with the stylus, the sub-menu closes.  However, doing the same thing--tapping with your finger vs. the stylus in the writing area--does not close the submenu.  It would be great if this could be added.

I believe the above UI modifications are inline with typical GUI behavior for most OSes.  They would also save me time and keep me "in the flow" of what I'm doing, which is of course why most of us love the rM so much.

Thanks so much for considering this suggestion!

**Comment by ddvk** [comment]
that was the default behavior, but was conflicting with the bookmarks menu, i ll fix it

**Comment by Tridens92** [comment]
Fantastic.  Thanks so much!

**Comment by ddvk** [comment]
added

**Comment by Tridens92** [comment]
You rock, @ddvk.  Many thanks again!
