### ISSUE TITLE
Feature request: Single swipe up to close

### ISSUE THREAD

**Issue by tsang** [ddvk/remarkable-hacks#102]
Hi, thanks for the tweaks, it has become indispensable. I was wondering if we can add single swipe up to close (I.e same as the current single swipe down to close).   Muscle memory from iOS would make it consistent.  

While not necessary, it would free single swipe down as well, and that could be reassigned to the two finger swipes (personal pref: quick swap previous file)

**Comment by ddvk** [comment]
it was 2 finger swipe up,  but then they added the swipe down gesture. 

most users of the stock sw are already accustomed to this gesture....

**Comment by tsang** [comment]
Ah!  Which version was that in?  That would be great. 

One more plug:  Single swipe from the bottom does nothing right now, would match mobile OS’s these days, be ergonomic, and doesn’t conflict (i.e keep both).

Also two finger down I feel is better for the MRU, reminds me of Notification Center on Android.  Then two finger up could be to swap last file.  If only they can be configured ;-)
