### ISSUE TITLE
rM1 and rM2 hack

### ISSUE THREAD

**Issue by imi122** [ddvk/remarkable-hacks#105]
I used to have the hack installed on my rM1. Ever since the update Im not able to reinstall it. P.s Software is currently on 2.4.1.30 and I have a Mac

Is someone able to explain what i need to do. 

Anything to get it back on my rM will be much appreciated

Thanks in advance

**Comment by pstemper** [comment]
Can you provide any additional information other then "I'm not able to reinstall it"?  Do you get an error when you try?  At what point is it "failing"?  What messages appear, and when?

**Comment by ddvk** [comment]
just ssh into the device, make sure it has internet and paste the script line
