### ISSUE TITLE
PDFs use different default pen/eraser

### ISSUE THREAD

**Issue by sersorrel** [ddvk/remarkable-hacks#106]
The default pen/eraser when I create a new notebook is medium (width 2) fineliner and the selection eraser, but when I open a new PDF it defaults to the thin (width 1) fineliner and the normal eraser. Is there a reason the defaults are different for notebooks and PDFs?

rM 1, fw 2.4.1.30, rm-hacks 16.1.03

**Comment by ddvk** [comment]
the last pen is used for new notebooks. however when a document is loaded (notebook or pdf) it has a saved pen which overrides the last pen

**Comment by sersorrel** [comment]
is there any way I can set the "saved" pen for new PDFs downloaded to the rM from the cloud? or am I stuck with having to set it by hand every time I upload a new PDF?

**Comment by ddvk** [comment]
i have/had the same problem with the desktop ui.  (i use rmapi mostly  now to upload files and there i have set the fineliner as a default tool).

**Comment by sersorrel** [comment]
ahhh, here? https://github.com/juruen/rmapi/blob/c0b46e0be985b0e68eda08927ab5a4ca77f391b7/archive/file.go#L23-L36

I'm also using rmapi, I'll recompile it with the defaults changed. thanks!

**Comment by ddvk** [comment]
yes, createzupdocument
