### ISSUE TITLE
feature request: double tap for centered zoom in

### ISSUE THREAD

**Issue by martinhess-at** [ddvk/remarkable-hacks#108]
Hello, since precise centering by pinch zooming in is not easy at all, i'd ask if its poosible to zoom by (double) tapping. 
Maybe zoom out could be triple tapping, but for zoom out pinch zooming is perfect anyway.. 
Thanks for considering, regards and greetings from vienna
Martin

**Comment by folofjc** [comment]
Something like this would be great, I agree. Pinch to zoom is a bit inconsistent.

**Comment by ddvk** [comment]
i havent had time to experiment.
also, the chance of it being activated by mistake is pretty high

**Comment by folofjc** [comment]
Yeah, I understand. That is why I was thinking maybe only implement it if you are already panned all the way to the respective side (all the way right for next page, all the way left for prev page)

**Comment by folofjc** [comment]
Once I read @ddvk's suggestion on the pinch to zoom, I haven't had many problems anymore.

**Comment by martinhess-at** [comment]
> i havent had time to experiment.
> also, the chance of it being activated by mistake is pretty high

ok, i see. if you'll be able to try someday, it woud be great.

**Comment by ddvk** [comment]
zoom in stock sw makes this obsolete
