### ISSUE TITLE
[Feature request] Insert text with virtual keyboard

### ISSUE THREAD

**Issue by jebediah2** [ddvk/remarkable-hacks#110]
Not sure how difficult it would be to implement, but I can think of a few scenarios (both note taking and PDF markups) where **inserting typed text by calling the virtual keyboard** could be useful, especially if you can customise available fonts too.

**Comment by ddvk** [comment]
where would you insert the typed text? 
the notes format is a vector one. there is one project that kind of does that, by converting the font to strokes, but still difficult

**Comment by jebediah2** [comment]
Isn't typed text also in a vector format? I thought that's what happens when you edit a PDF document on PC. This could be used to create titles or other structural elements, and if it also becomes possible to use your own fonts, to work graphically with them. Another use could be to insert clean text like when you want to type code, or an address.
Not a big priority I guess, but could be helpful.

**Comment by dstango** [comment]
don't mix what's happening in your favorite word processor/pdf application and how remarkable handles it:
the rm uses a proprietary .lines-Files-Format, that is specialized only on pen strokes of the rm. To make it mimic Fonts would mean that every character of the alphabet needs to be converted in a form of the lines (like taking a fineliner and redrawing a character) and then be added to the .lines file. Too much effort to implement for the hacks, I'd guess -- and I fear it would result in massive performance drawbacks, as about 10 lines of characters might easily be the equivalent of thousands of generated pen strokes ...

**Comment by ddvk** [comment]
as @dstango said, what you see is just lines. if i could do such a thing, i would have written the app from scratch and open sourced it

**Comment by jebediah2** [comment]
Could this idea be revived now that the official firmware supports typing when using their new Type Folio hardware?
