### ISSUE TITLE
rm2 bugs with latest patch

### ISSUE THREAD

**Issue by idnovic** [ddvk/remarkable-hacks#111]
I installed the latest patch and I have the following bugs:

page turn by button does not work.

I can not choose a color with the highlighter.

**Comment by idnovic** [comment]
patch 16.2.02-0

**Comment by chimpdude** [comment]
Button? Are you sure you're talking about the reMarkable 2, which doesn't have buttons?

Also, the highlighter has only one color. The stock software has no other color options.

**Comment by idnovic** [comment]
I was under the impression that with your patch I can choose more "colors". 

About the buttons, at the left side where your patch has added a page turn feature. 
The two arrows do nothing.

**Comment by sethmnielsen** [comment]
I'm not the author. Where did you read that about the highlighter? Those arrows are for bookmark navigation. The README is a good read, btw

**Comment by chimpdude** [comment]
I'm not the author. Where did you read that about the highlighter? Those arrows are for bookmark navigation. The README is a good read, btw
