### ISSUE TITLE
[Feature request] one touch sheet

### ISSUE THREAD

**Issue by Mizio66** [ddvk/remarkable-hacks#112]
It would be nice to have the possibility with a button or else to quickly create a new sheet with a predetermined template and location and with the name set to date and time.
This way one could quickly open a place to write and later organize it as desired.

**Comment by zelomel** [comment]
That is the use of Quick Sheets ...
You can apply a template to quick sheets and maybe a template with a date field.

**Comment by ddvk** [comment]
yes, you can use quick sheets and then extract the page. the datetime in the name makes sense and can be made toggleble
