### ISSUE TITLE
[Feature request] add option to show filename

### ISSUE THREAD

**Issue by grobins** [ddvk/remarkable-hacks#116]
WIth so many notebooks for different topics, I find it hard to remember which notebook I'm currently working on.  It would be nice to have the option to display the notebook name at the top/bottom of the screen to avoid accidentally writing in the wrong book and having to move pages.

**Comment by Eeems** [comment]
Click on the battery on both bottom of the toolbar. It'll show you the notebook name.

**Comment by ddvk** [comment]
already an option in the stock ui as noted above
