### ISSUE TITLE
[Feature Request] Force sync button

### ISSUE THREAD

**Issue by jebediah2** [ddvk/remarkable-hacks#117]
Syncing between the cloud and the tablet doesn't really happen live and sometimes takes a frustrating wait, especially after uploading/editing a document from the PC then waiting for it to appear on the tablet. 
Adding a sync button on the homepage or the menu bar of the tablet to force it to sync would probably improve the experience quite a bit.

**Comment by ddvk** [comment]
the device tries to establish a connection as soon as it has connectivity. after that notifications are received almost immediately if the nothing is blocking the websocket connection. 
also, not possible for me

**Comment by Tridens92** [comment]
@jebediah2 , do you know there's already a built-in way to force the sync?  Settings --> Storage --> Check Cloud Sync

**Comment by jebediah2** [comment]
> @jebediah2 , do you know there's already a built-in way to force the sync? Settings --> Storage --> Check Cloud Sync

That features reads "Checks if your reMarkable is syncing properly" so I assumed it wasn't doing that job. If it does, then it would be really useful to add that button somewhere more convenient, either in the main menu or the top menu bar. What do you think @ddvk ?

**Comment by Barabazs** [comment]
IIRC it does force a sync. And as ddvk mentioned, the synchronisation should be almost instantaneously.

I'm not ddvk, but I can't imagine that implementing this would be of high value to the community.
