### ISSUE TITLE
[Feature Request] Misc tools with different pens

### ISSUE THREAD

**Issue by ai212983** [ddvk/remarkable-hacks#119]
Not sure if it is possible at all, but right now i do have 2 pens for rM2 - Lamy and Marker Plus. 

It would be awesome to remember tool for each pen used, i.e. Fineliner for Marker Plus, Highlighter for Lamy.

**Comment by ddvk** [comment]
sorry not possible, the device cannot distinguish the pens (wacom emr stuff)
