### ISSUE TITLE
Support Bluetooth Keyboards

### ISSUE THREAD

**Issue by b4be1** [ddvk/remarkable-hacks#122]
Hi @ddvk,

This may be slightly off-topic but you may be the only person who knows the answer. And given the popularity of remarkable-hacks, I think others may face a similar issue.

I want to connect a Bluetooth keyboard to Remarkable 2 to be able to type in text as on a typewriter. To achieve that, I first need to pair the Bluetooth keyboard with the Remarkable 2. But there seems to be no Bluetooth module on the Linux system on the device. Do you have a suggestion how to proceed? Is there a way to build Bluez on the Codex Linux?

The app I want to use is Crazy Cow and I provide some more details on my setup in https://github.com/machinelevel/sp425-crazy-cow/issues/7.

I think adding support for Bluetooth in remarkable-hacks would enable cool applications. E.g., see the list of requests for supporting Bluetooth keyboards on Remarkable 2 here https://github.com/machinelevel/sp425-crazy-cow/issues/2#issue-705620879.

Best,
Boris

**Comment by ddvk** [comment]
well, there is a bt module but it us not physically conected. i used a usb bt dongle once, and i compiled bluez, but for the rm2 you ll have to use the pogo pins

**Comment by b4be1** [comment]
My plan was to also use a bt dongle on rm2. Is this not possible on rm2?

I am not sure I understood exactly what you mean by using the pogo pins. Do you mean there is a physical bt module available on rm2 but not connected, and I should open the casing and connect it by hand?

**Comment by ddvk** [comment]
i haven't found a way to put the usb-c port in host mode. the pogo pins (the 5 dots you see on the side of the rm2 close to the usb port) is a second usb port that can be put in host mode

**Comment by b4be1** [comment]
Got it, thanks for the clarification. Then I will explore this direction.

**Comment by b4be1** [comment]
In case someone stumbles upon this thread, there is more info related to this question on reddit https://www.reddit.com/r/RemarkableTablet/comments/j9g1d5/rm2_with_an_external_keyboard_accessory_port_usage/ and in discord https://discord.gg/qEnCVcd in the rm2 channel.

**Comment by ddvk** [comment]
closing this as i can't do much about it.

**Comment by b4be1** [comment]
Now it is possible to use the USB-C port https://github.com/machinelevel/sp425-crazy-cow/issues/6#issuecomment-797095272

**Comment by gap736uk** [comment]
@ddvk  - just picking this thread up now as i'm looking at using a bluetooth keyboard with my RM1 and spotted in this thread you said that you did this once. I have managed to connect up a bluetooth keyboard with the dongle that came with the keyboard, but it isn't really a portable keyboard, so not ideal for travelling.... 

As such I'm looking to see if there's a way to use a generic bluetooth dongle to allow me to pair with any bluetooth keyboard.

couple of quick questions for you if I may:
1. above you mentioned that there _is_ a bluetooth module, but it isn't physically connected.. does that mean in there is the _hardware_ inside the RM1 case, just not actually connected for some reason (never mind the lack of software stack!)?
2. I assume you used a bluetooth dongle to connect such a device to your keyboard... was this by installing 'bluez' stack onto the RM1 and then getting that to pair with your keyboard initially? (I have seen some hints elsewhere that this is the method to get this to work).... it would be _so_ much easier if this case as part of the standard software and then there was a pairing option available on the settings menu 
3. Is there any way to get the onscreen keyboard to be suppressed at all when using such a keyboard? (The success I had above was slightly marred by this popping up unnecessarily.

Beyond that, with a MOFT tablet stand and a possible way to connect a keyboard i've got something close to the new fancy keyboard filio working

**Comment by ddvk** [comment]
1. the wifi chip has a bt module , but it is not physically connected i.e. the pins are not used.
2. yes, bt dongle, here's https://github.com/ddvk/remarkable-hacks/releases/download/0.0.0/bt.tar.gz the stuff I used back then (https://www.reddit.com/r/RemarkableTablet/comments/e8p22h/remarkablekeywriter_with_a_bluetooth_keyboard/)
3. haven't tested

**Comment by dodosocial** [comment]
@ddvk I would like to try to use bluetooth keyboard + 3rd party bluetooth dongle on my RM2.
I downloaded the bluetooth tar.gz file. And I'm trying to follow the steps in readme file. I didn't compile anything at my end and I'm simply using the files found in the tar file.

- copy dbus policy rule
	cp etc/dbus-1/system.d/bluetooth.conf /etc/dbus-1/system.d

# kernel modules (in lib/modules/4.9.84-zero-gravitas/
	insmod bluetooth.ko

When I tried to insmod the .ko files in RM2, I hit errors like below:
     insmod: ERROR: could not insert module bluetooth.ko: Invalid module format

What could be problem be? Thanks!

**Comment by dodosocial** [comment]
I see, got it. Super thanks for your prompt reply! I will check if there is any chance to compile with the current kernel version...
Just got my RM2. Will check how to setup my Mac with qtcreator, toolchain to make things work.

**Comment by Eeems** [comment]
> the modules were compiled for an older kernel version. also not sure whether modules are enabled on the newesr kernel...

The latest kernel ships with modules that aren't embedded in the initrd that are required for the keyboard folio, so I would assume that they are enabled.

> I see, got it. Super thanks for your prompt reply! I will check if there is any chance to compile with the current kernel version...
> Just got my RM2. Will check how to setup my Mac with qtcreator, toolchain to make things work.

you wouldn't need qtcreator for compiling kernel modules.

**Comment by dodosocial** [comment]
Thanks Eeems! That's very helpful! It has been painful to install qt5 on my mac

**Comment by Eeems** [comment]
> Thanks Eeems! That's very helpful! It has been painful to install qt5 on my mac

Running it from a docker container might be the better option if you need it in the future

**Comment by dodosocial** [comment]
Thanks @Eeems ! Kindly let me know if my planned steps are correct:
1, use the base image of toolchain docker `https://github.com/toltec-dev/toolchain`
2, run the docker, and copy in bluez source code
3, compile bluez to generate .ko files
4, insmod the .ko files to RM2

**Comment by Eeems** [comment]
> 2, run the docker, and copy in bluez source code

It would be easier to just mount it as a volume. If you want to see an example of building a kernel module: https://github.com/toltec-dev/toltec/blob/afa2840abae9113d46ec978aec661ebbcf74960b/package/wireguard/package#L50-L79

**Comment by Azeirah** [comment]
Does anybody know if the rM pro's bluetooth hardware is available in software?

@Eeems @ddvk

**Comment by Eeems** [comment]
> Does anybody know if the rM pro's bluetooth hardware is available in software?
> 
> @Eeems @ddvk 

This is not a generic support forum. You can get help on the community discord which is linked in the readme.

You can also find more information about Bluetooth here https://remarkable.guide/devel/device/bluetooth.html

**Comment by Azeirah** [comment]
> > Does anybody know if the rM pro's bluetooth hardware is available in software?
> > [@Eeems](https://github.com/Eeems) [@ddvk](https://github.com/ddvk)
> 
> This is not a generic support forum. You can get help on the community discord which is linked in the readme.
> 
> You can also find more information about Bluetooth here https://remarkable.guide/devel/device/bluetooth.html

Apologies, my impatience combined with eagerness can be too much at times. I'll keep it in mind.
I wasn't aware of the remarkable guide site, that's a good resource!
