### ISSUE TITLE
Swipe down to close also shows/hides the menu

### ISSUE THREAD

**Issue by sersorrel** [ddvk/remarkable-hacks#123]
As the title: using the stock swipe-down-from-top gesture to close a document (same action as the home button) also invokes the swipe-down gesture to toggle the menu, but it probably shouldn't – either the document should be closed or the menu should be toggled, not both.

rM1 Version 2.4.1.30 - patch_16.1.06

**Comment by zelomel** [comment]
you have to swipe all the way down to close the document and only few cm for toggle the menu.

**Comment by ddvk** [comment]
@zelomel he means that the gesture gets activated when you close, so next time you open the document the menu visibility is reversed

**Comment by Crash331** [comment]
Yes, I am also having this issue.  It's a little annoying since it seems the X to close the document is gone. It keeps alternating and every other notebook has the menu hidden.

**Comment by Crash331** [comment]
ddvk just told me how to close a document without using a swipe, so I can get around it for now (bottom icon on toolbar).  But it would be nice feature if the toolbar didn't toggle if a document close swipe is detected, if that's possible.
