### ISSUE TITLE
Unintuitive behavior of Show First Page / Show Last Page

### ISSUE THREAD

**Issue by b4be1** [ddvk/remarkable-hacks#124]
The behavior of the toggle Show First/Last Page seems somewhat unintuitive.

If I understood correctly, it works on document types. E.g., I can set all notebooks to show the last page and all pdfs to show the first page. However, the toggle remains in its last state when I switch from a notebook to a pdf file. Thus, the state of the toggle in the pdf file does not correspond to the actual state of the first/last page setting. But this is not so critical, since I can nevertheless get the desired result.

In general, the behavior is unintuitive because this toggle is available inside a file but has effect on all files on the device, on the way they are shown in the explorer. Is it possible to have this setting per-file? And have defaults per document type? E.g., having pdf show first page and notebooks the last page seems a reasonable default.

**Comment by ddvk** [comment]
i can split the toggle (ie for notebooks and documents). 
the  

the menu contains some global settings becuase it was less effort

**Comment by ddvk** [comment]
the latest update allows you to set which page is shown
