### ISSUE TITLE
Improve Lamy click / hold to erase differentiation

### ISSUE THREAD

**Issue by dstango** [ddvk/remarkable-hacks#126]
I find the timing for switching between first / second tool by using the Lamy button tricky -- it often goes to eraser mode and then back to the original tool for me.

Here's an implementation suggestion to probably improve that:
When the button is released take into account if the pen has actually touched the surface since pressing the button:
- if touch has happened assume it was the erase on hold action
- if touch hasn't happened (and time since press is below a timeout threshold of e.g. 1 sec) assume it was a request to toggle between first/second tool

I don't know if this might interfer with the Staedler Jumbo or the new rm pen with eraser side, but maybe it's an idea worth considering.

**Comment by ddvk** [comment]
the timing of the hold seems to be a bit tight (200ms)

detecting touch is kind of involved,
what seems to work for now is:

switch to eraser on button press

on release < 1 sec: switch tool and go back to pen

if > 1 sec treat as hold and go back to pen
if < 300ms double click: undo, go back to pen

**Comment by FastblinkerCalamity** [comment]
Is there something I need to do to enable the eraser on the Lamy? I've tried using it but it does nothing as far as I can tell.

**Comment by ddvk** [comment]
you uave to install the remarkble-stylus plugin from the repo with the same
name

**Comment by mgsoloway** [comment]
Any thoughts about just making the button press a mode toggle?:
When you first enter a file, it starts in pen mode. When it is pressed while in a file, it toggles back and forth between pen mode and eraser mode.

**Comment by dstango** [comment]
@mgsoloway: there was an option in former versions that has been removed, as the various settings seem to have caused confusion, I think

**Comment by mgsoloway** [comment]
Maybe consider making it a setting option? It would definitely make it easier for me to use, but everyone has different preferences.

**Comment by ddvk** [comment]
it became buggy and difficult to test all possible combinations, i m waiting to see how the current implementation fares.

**Comment by Tridens92** [comment]
I'm having a problem with the Lamy button causing a switch to the last used tool immediately after erasing.  Check out the video link below.  You can hear me click the Lamy button and release it...only one press, and then one release.  But it's still changing the tool.  Thanks for any help you can offer.

[https://photos.app.goo.gl/BoAsnX4ajJjP8U2R9](url)

**Comment by dstango** [comment]
I think it is related to the distance of the pen to the surface and the timing of letting go of the button:

- If I hold the button for erasing, keep hold while lifting the button off the screen quite high, the tool doesn't toggle
- If I hold the button for erasing, lift the pen and more or less simultaneously let go of the button the tool *might* toggle

Sometimes I had the impression it even depended on whether I was approaching the screen with an already pressed button, but I couldn't steadily reproduce it.

Anyhow: the combination of sequence, timing and distance seem to be related to the unwanted toggle.

**Comment by ddvk** [comment]
the timing is at 500ms (if you hold it longer than that then it was a hold to erase, otherwise a click). 

moving towards/away from screen is not really relevant but at some distance the pen get recognized, thus the button click gets registered (if it was pressed out of range). (to test press the button and then quickly erase and move the pen away, it gets registered as a click)

**Comment by Tridens92** [comment]
Thanks, @ddvk and @dstango, but I feel something has changed, as I never had this issue before.  Another user just reported the same issue here:

[https://github.com/ddvk/remarkable-hacks/issues/193#issuecomment-763759339](url)

Any chance there's a bug here?

**Comment by llinfeng** [comment]
I'd like to after @Tridens92 for the following: after rM2 updated itself to 2.5.XXX, buttons on the pen (Lamy, Samsung) started to function differently. For now, after using the eraser for a brief period of time (around a few seconds), I may end up with another brush unexpectedly.

I guess the timing was a bit shorter than 500ms before? For now, I need to actively monitor the icon in case there should be another accidental switch of brushes.

**Comment by ddvk** [comment]
this should work now.
toggling should be a new issue
