### ISSUE TITLE
Zoom enhancements: page navigation proportional to swipe distance, disable two-finger down swipe

### ISSUE THREAD

**Issue by chimpdude** [ddvk/remarkable-hacks#127]
Pinch-and-zoom, along with swiping to navigate around the page, has become one of my most-used features because of all the math I do on the tablet. It's so useful to zoom in and write the tiny sub/superscripts and other symbols, as well as for giving more width to the page for writing out long equations! There are a few little quirks that have popped up after heavy use of the feature that would greatly enhance it if fixed. 

1. The biggest thing is that swiping while zoomed in moves the view box around the page a constant amount. I often only want a to nudge the view slightly left or right to center it better or to see more of the equation; however, swiping left/right results in the same amount of movement (about 60% of the page) whether a short or a long swipe. It would be wonderful if navigation were proportional to swipe length, i.e. a long swipe moves you a large distance across the page, and a short swipe will only push the view slightly. 
Although, I just realized that I can't think of anything on this tablet that acts according to swipe length, so maybe this isn't a straightforward addition?

1. When I try to do the two-finger zoom out, about 40% of the time I accidentally activate the two-finger downwards swipe for switching to the most recently opened document. Would it be possible that the two-finger downward swipe be disabled while zoomed in, or that it could be modified to not be quite so easy to mistake it with two-finger zoom out?

**Comment by dronedad** [comment]
Hi guys. I just installed the last patch on Friday. Getting used to all the features with my RM2. For some reason, the two-finger zoom in or out is not working. Or maybe I am not aware of how to use it. Or how to verify if the patch was correctly installed for the pinch-and-zoom feature.
Appreciate it if someone sends me some tips for the best user experience when using pinch-and-zoom. I have disabled and enabled again but still no difference. 
Thanks in advance,

**Comment by ddvk** [comment]
@dronedad you have to enable it in the share menu

@chimpdude no way to know what the distance of swipe was (atm it is just swipe or no swipe)

**Comment by chimpdude** [comment]
@ddvk I was afraid of that - but it makes sense given that no other features seem to make use of swipe distance. No worries!

What about the accidental switching to the most recently used document when attempting pinch to zoom out? Just now, I can try lots of different variations of pinch to zoom out, and it is not very hard to activate switch to most recent document, even though my thumb is clearly moving in a upwards-right direction. Could that be a bug? It's weird that two-finger swipe down would get activated when one finger is moving in a north-east direction (probably more sideways than upward, but it's definitely with an upward component).

**Comment by ddvk** [comment]
i ll look into it

**Comment by Foxei** [comment]
I can confirm, that Pinch-and-zoom does not work on the rm2 on version 2.4.1. All other feature as far as i have notices are working fine.

**Comment by katiebobus** [comment]
Works fine on mine. Do you have 2.4.1.30?

**Comment by Foxei** [comment]
Remarkable 2 with Version 2.4.1.40 and patch_16.2.03. I can not use Pinch as I would on a normal smartphone or trackpad. I tried it in a pdf and a notebook. Zooming with the build in zoom function works fine pinching results in no reaction at all. 

My Steps:
Open a pdf -> use the quick settings to enable pinch to zoom -> use two fingers to zoom the pdf.

**Comment by ddvk** [comment]
the fingers should be very close at the start

**Comment by Foxei** [comment]
I testet some more and u are right. I am an absolut idiot... Have a nice late evening all together. 🤦🏼‍♂️

**Comment by dronedad** [comment]
Same here. I didn't know how to use it and thought it was not working. Another tip....move the fingers away fast.

**Comment by dronedad** [comment]
The only thing I still struggle with RM2 and need to master is the swipe left and right to undo and redo respectively when in zen mode. Any tips????

**Comment by ddvk** [comment]
> The only thing I still struggle with RM2 and need to master is the swipe left and right to undo and redo respectively when in zen mode. Any

here is a demo

https://imgur.com/gallery/jHB3yPh

**Comment by sersorrel** [comment]
are the undo/redo/switch-pen swipe gestures only available on rm2? or are they meant to be enabled on the rm1 as well?

**Comment by ddvk** [comment]
they should work on rm1 as well

**Comment by sersorrel** [comment]
hm, ok, I can't get them to work

**Comment by ddvk** [comment]
what version are you running?

**Comment by dronedad** [comment]
> > The only thing I still struggle with RM2 and need to master is the swipe left and right to undo and redo respectively when in zen mode. Any
> 
> here is a demo
> 
> https://imgur.com/gallery/jHB3yPh

Thanks. Much appreciated

**Comment by sersorrel** [comment]
fw 2.4.1.30, patch 16.1.06-0-gae0990f

**Comment by Halmex** [comment]
> fw 2.4.1.30, patch 16.1.06-0-gae0990f

For RM1 the swipe left and right to undo and redo on the top only work for patch 17.1.01. Switch tool, switch eraser, and undo in the area under the menu icon should work on patch 16.1.06.

**Comment by ddvk** [comment]
rendered obsolete by the new zoom logic
