### ISSUE TITLE
Bugs found

### ISSUE THREAD

**Issue by PkW4v3** [ddvk/remarkable-hacks#130]
I found these bugs:

- When I swipe in a notebook to create a new page, the middle button only works if Pressed twice;

- I don't know the reason, but sometimes the page number disappears despite being enabled from settings;

- The clock disappear from corner when I open a pdf file;

- I think it would be better to activate the eraser with Lamy pen button before checking for how many milliseconds the button is pressed, otherwise writing quickly you risk making mistakes using the pen instead of the eraser during those few milliseconds.

Thanks in advance for your great work

**Comment by ddvk** [comment]
the swipe /home is bug in the stock sw it seems, but i can probably fix it

the page numbers are shown only if the menu is not visible, is this the case?

can't reproduce, it just disappears if it is selected and if pressed for a longer time

the lamy pen can behaviour can be changed.

**Comment by PkW4v3** [comment]
For the page number, you are right, my mistake!

Instead for the clock problem, I attach you a video: https://streamable.com/23ihov
This happens only when I open a pdf or ebook file. Switching from any notebook to another notebook, the clock keeps enable without problem.

Thanks again!

**Comment by ddvk** [comment]
how is the latest version?

**Comment by PkW4v3** [comment]
It seems that swipe / home bug was not fixed by reMarkable

I tried doing a factory reset and the clock problem was solved!
