### ISSUE TITLE
make the default notebook name be iso formatted datetime

### ISSUE THREAD

**Issue by ddvk** [ddvk/remarkable-hacks#131]
default notebook name to `yyyymmdd_hhmmss`

toggleable

**Comment by manuelinux67** [comment]
Very helpful

**Comment by llinfeng** [comment]
How to toggle the default notebook name? I tried patch 17.2.02 on rM2 Version 2.4.1.30 but did not find any new button to click/toggle on the side-menu. Do I have to wait for an update for rM2 first?

**Comment by ddvk** [comment]
there is no toggle yet, and yes only in the 2.5 version
