### ISSUE TITLE
What will happen when software updates drop?

### ISSUE THREAD

**Issue by unphased** [ddvk/remarkable-hacks#134]
I think all's needed is a note about what we can expect when this happens. E.g. if I leave automatic updates setting on, I can expect one day for hacks to get replaced, and the automagic command will need to be run again to bring the hacks back. So it may be advisable, I guess, to disable automatic updates?

**Comment by ddvk** [comment]
norhing happens, if you happen to get the new version you'll have to wait until the patches get ported (the automagic will say unsupported until then). i ll add this to the faq

in some cases autoupdate can be a good thing (eg ssh screw ups)

**Comment by unphased** [comment]
So when auto updates happen we'll lose the hacks? Yeah I already disabled mine since I figured that's what'll happen. Just good to have a note for this in readme. Thanks!
