### ISSUE TITLE
What is the function of Set/Rst in the numpad? What is being indicated by "Adj is <number>"?

### ISSUE THREAD

**Issue by unphased** [ddvk/remarkable-hacks#135]
I have figured out all of the functionality except for this one.

It's clear that Rst means reset and sets Adj to the current page. Set sets Adj to the value entered, and zeros the value entered. ~Hitting Go goes to the page that is the value entered (1 if it's 0).~ Negative values can be set to Adj. 

None of this helps me understand what Adj is used for.

**Comment by unphased** [comment]
It looks like when you hit Go, the page advances by `(value set - Adj)` from the current page. I don't know why this works like this but I guess i can see it being helpful in some contrived ways (still can't figure out what the use case is).

**Comment by dstango** [comment]
it's useful for pdfs with a page numbering that doesn't start with page 1 -- e.g. you have an index and a foreword and only then comes "official page 1".
you then can easily enter "5", press "go" and you will be on the pdf with page 5 written in the bottom corner (or whereever the layout has it).

**Comment by unphased** [comment]
Gotcha, thanks.

**Comment by ddvk** [comment]
closing this as resolved

**Comment by unphased** [comment]
Can someone explain how to use this feature? I'm really struggling. 

I have page 25 open. Page 23 is the labeled page 1, so that means I'm on page "3". 

I open the panel, and i might want to do one of two and only two things:

- go to the pdf page X
- go to the labeled page Y

But when I open the panel it prefills Adj with whatever number was last entered. And you have to take it into account. I cannot conceive of any way in which this is productive. Can someone kindly walk me how this is supposed to work?

I just want to be able to go to PDF page X or PDF page Y+23. Right now I can't even do that. I have to take into account what page I am on and what delta I applied last in the menu in order to work out what the offset to apply to go to page X. It's frankly beyond absurd.

**Comment by unphased** [comment]
The only thing I can imagine that lies within reason is that it's a bug for the Adj to update to last entered value.

**Comment by ddvk** [comment]
you want to go to page 20, you enter 20, but the pdf shows 30. 
you enter 30 and press `Set` which sets the Adjusted page to 30.
you enter 20 again and end at page 20 in the pdf.

**Comment by unphased** [comment]
Thank you. I knew I was being daft. Now I can finally read a book on this device.
