### ISSUE TITLE
Is there a way to export the bookmarks when I expot the note as PDF?

### ISSUE THREAD

**Issue by llinfeng** [ddvk/remarkable-hacks#136]
I find the bookmarks very helpful, and wonder if I can keep it with the notes as I stop actively editing them? For now, I tried the following ways to export the notebook as PDF, and none has a populated bookmark panel when I view the document in Sumatra PDF viewer (together with Adobe Acrobat and PDF XChange Viewer).
* Export as PDF using RCU (neither exporting as Bitmap nor exporting as Vector works)
* Export as PDF using the reMarkable desktop client

I wonder if all I need is a rsync hack? Please advise.

**Comment by ddvk** [comment]
the bookmarks are just a json file, but they dont get uploaded, you could probably wite a script or something (after rsyncing)

**Comment by llinfeng** [comment]
Where exactly is this JSON file stored? Do all notebooks + PDF files write to the same JSON file, or there are separately stored? 

I am not familiar with how things are stored, and did not find any `json` file in `/home/root/.local/share/remarkable/xochitl`. Source:  [tech:filesystem - reMarkableWiki](https://remarkablewiki.com/tech/filesystem)

**Comment by ddvk** [comment]
look for .bookm files in .local/.../xochitl

**Comment by llinfeng** [comment]
Clarified, thank you! I was only looking for recent files with `| head` flag. The `.bookm` extension helps to pin it down!
