### ISSUE TITLE
Is it possible to add a page to a pdf? 

### ISSUE THREAD

**Issue by unphased** [ddvk/remarkable-hacks#137]
I imported my notes from iCloud as a PDF, and it included an extra blank page in the pdf. I realized after adding a bunch of notes on this new page, and struggling for a while to figure out how to add another new empty page that it's just not supported. It looks to be a rM software (xochitl) built-in limitation. That sucks, and I can now finally commiserate with the redditors that I've seen whining about this. 

As a developer myself I cannot fathom how this software can be considered by a sane project manager as being ready for release. Is there any workaround for this? 

I suppose for the time being, I'll just need to leverage the recent files menu and file switching a lot to just spread my work across more files then.

**Comment by ddvk** [comment]
this is not possible, the pdf is static and used as a template, no editing facilities (could be scripted from the outside with some tool probably)
