### ISSUE TITLE
Bug when importing page from pdf

### ISSUE THREAD

**Issue by unphased** [ddvk/remarkable-hacks#138]
I made a new notebook and went to a pdf to bring it into my new notebook. Once I did this, going to that page shows in the background 

> **Unable to load document background**
> Try restarting your reMarkable or contact support if the problem persists.

It's possible to get this to go away by hiding the Template layer on this page.

**Comment by unphased** [comment]
I can confirm that the "Unable to load" message basically replaces the PDF content from the pdf that the page got moved in from. So this workflow is not going to really work for being able to bring pages from an imported pdf into an actual notebook...

**Comment by unphased** [comment]
I can also confirm that if you take the bugged page from the pdf and move it back from the notebook to the original pdf, it restores the background...

**Comment by dstango** [comment]
I don't think moving pdf pages to regular notebooks is supported by the rm at all. Don't think the rm hacks can do anything about it without lots of effort.

**Comment by ddvk** [comment]
yes, it is just a gack to export the pdf page into a notebook, the background cant possibly work, but it is a bug that it was not reset to blank

**Comment by ddvk** [comment]
fixed or who knows
