### ISSUE TITLE
Not clear when installation via ssh is finished.

### ISSUE THREAD

**Issue by UnchartedSystems** [ddvk/remarkable-hacks#140]
<img width="1294" alt="Screen Shot 2020-12-07 at 7 46 22 PM" src="https://user-images.githubusercontent.com/20145459/101431831-e4e6ab80-38c4-11eb-88e8-18f0c3dfb92c.png">

If I'm not mistaken, the installation finishes when we reach the event: "evdevtouch: Updating QInputDeviceManager device count: 1  touch devices, 0 pending handler(s)", but to the end user, this is ambiguous as to whether the process has finished or is simply hanging. I'd suggest a simple change here that explicitly says the process is finished.

**Comment by Eeems** [comment]
If you read through the text in your screenshot you'll find the following:
> Trying to start the patched version...
> You can play around, press CTRL-C when done.

So when you are done trying it out you can CTRL-C to quit out and it will ask you if you want to make it permanent.

**Comment by ddvk** [comment]
this is a failsafe, so that if it fails to start for some unknown reason nothing gets changed.

**Comment by Eeems** [comment]
@ddvk it might be good to make the message a bit clearer about what next steps are, and to make it pop out more with colour or something.

**Comment by ddvk** [comment]
i made it blink, it should be visible enough now i think
