### ISSUE TITLE
UI Suggestion: Provide an "x" on the top right to close a file

### ISSUE THREAD

**Issue by mgsoloway** [ddvk/remarkable-hacks#142]
This is just a UI suggestion. Please provide an "x" on the top right to close a file.

**Comment by ddvk** [comment]
you can swipe down to close the file, also a lot of people complain that they trigger it

**Comment by dstango** [comment]
it would probably interfer with setting bookmarks in the top right corner

**Comment by mgsoloway** [comment]
After reading the feedback, I'm satisfied that a swipe to close the file is a good UI/UX design choice for closing the file, instead of the "x".

I am noticing that a swipe does not always work well for me, but that may be me and require practice. If I determine there is a repeatable issue with swipe to close, I will report it.

I'm closing this issue.
