### ISSUE TITLE
Eraser to Pen switch with button on RM1 2.5.0.27 is inconsistent

### ISSUE THREAD

**Issue by fsw0422** [ddvk/remarkable-hacks#146]
on notepad, when I click the left button, the eraser to pen switch was almost immediate in the previous version, but now it works sometime and sometimes not at all. I experience this especially when I use the utensil and want to switch immediately

**Comment by ddvk** [comment]
sorry, forgot the pen proximity disable

**Comment by ddvk** [comment]
fixed in 17.1.02

**Comment by fsw0422** [comment]
@ddvk saved my day thanks
