### ISSUE TITLE
Options poppup distored when text set to large

### ISSUE THREAD

**Issue by LeifAndersen** [ddvk/remarkable-hacks#148]
When the text is set to large (in the accessibility menu), this is what the popup options dialog looks like:

![signal-2020-12-11-172254](https://user-images.githubusercontent.com/285926/101960832-4dd86700-3bd6-11eb-90ae-66a86db6bb7e.jpeg)

(Sorry about the low-quality picture, I haven't yet figured out how to screen-cap the framebuffer...)

This is on an rm2 running 2.4.1, with the font size set to large.

**Comment by ddvk** [comment]
i dont use and i ve never tested the large fonts,i will try to fix it
