### ISSUE TITLE
Mirroring clipboard?

### ISSUE THREAD

**Issue by Steff1964** [ddvk/remarkable-hacks#149]
Hi, thx for this great work.
I'm using my RM2 for technical sketches. Is there any way to implement a "mirror feature" along a single axis (e.g. vertical axis) in the clipboard when pasting anything? That would be very helpful!

I also couldn't get pinch2zoom to work on the RM2, but everything else seems to work perfectly.
Maybe I'm missing something?

Thanks & cheers, Stefan

**Comment by ddvk** [comment]
messing with the clipboard is quite hard and beyond my capabilities
