### ISSUE TITLE
patch.sh

### ISSUE THREAD

**Issue by dronedad** [ddvk/remarkable-hacks#150]
I am on RM2 2.4.1.30 patch 16.2.03....and trying to get the latest features / patch. 

I see 2.5.0.27 patch_17.2.02 is out...when I try to install by selecting patch_17.2.02, it doesn't work. 

Already tried to uninstall and install rmhacks again from start, but it always go back to RM2 2.4.1.30 patch 16.2.03. I thought a new and fresh install will pick the latest 2.5.0.27 but not in my case.

Any tips?

Thanks

**Comment by pstemper** [comment]
You need to install the rm 2.5 update,  THEN reapply the patch..

Paul

Sent from a Samsung S10
________________________________

**Comment by llinfeng** [comment]
I guess the newer patches can only work with newer rM2 software.

Linfeng Li

Doctoral Candidate in Behavioral and Experimental Econ
School of Information
University of Michigan
Phone:   (+1)7344179355
Skype:   llinfeng1900

**Comment by dronedad** [comment]
Precisely. 
My device is still with the old one. So I will wait till it get the update. 
Cheers.
