### ISSUE TITLE
[Feature Request] Add New Page Icon

### ISSUE THREAD

**Issue by cschwartz85032** [ddvk/remarkable-hacks#151]
It would be really nice to have a plus (+) icon somewhere on the page to add a new page to the current notebook.  I think the ideal location would be in the lower right corner of the page so that as you're writing and get to the end of the page simply hit the plus and goto the new page.  The next best would be adjacent to the page close icon, though that would require your hand to move the entire length of the page to add a page.

**Comment by LeifAndersen** [comment]
If its in the lower right then many right handed people will bump it when writing with the menu is open.

**Comment by ibahson** [comment]
If you are on the last page in a notebook, a swipe to the left (rM1|2) or next page button (rM1) will add a new page to the notebook.

**Comment by ddvk** [comment]
as commented, a nrw page is inserted automatically if there are changes on the current one.
