### ISSUE TITLE
Procedure for testing against new official rm sw versions

### ISSUE THREAD

**Issue by ttrine** [ddvk/remarkable-hacks#152]
Hi,

Potential interested contributor here, new to the project, have used it for a spell and love the features.

I'm wondering if there is any process/workflow around identifying breakages against new official sw versions? Is there potential benefit to establishing some CI/CD around this? I'm happy to look into it but would love input from ddvk or other contributors first.

If this has been asked before, apologies - any links to relevant info would be most appreciated.

**Comment by ddvk** [comment]
as this mangles the binary itself and i dont have the source code and dont know how you would do that. 

it either runs or segfaults on the device
