### ISSUE TITLE
Change first page on version 2.5

### ISSUE THREAD

**Issue by leifan89** [ddvk/remarkable-hacks#153]
Hello!

First off - thank you so much for your work on these set of hacks. Amazing - can't live without them now, especially table of contents.

Second, with the new update to 2.5, original RM firmware lets me change first page of a PDF (even ePUB it seems). However, that functionality seems broken with these patches applied (no effect after changing that setting in UI). I think that was one of the original functionalities of these patches (to force cover to be first page of PDF), maybe now that part of the code can be removed in favor of using the original RM firmware functionality?

Thanks so much once again!

**Comment by ddvk** [comment]
it can be toggled (use 1 or that from doc)

**Comment by zelomel** [comment]
If I understand, your setting applies to all documents but RM firmware setting applies to the document where it is set.
Can it be to possible that your setting is the general setting and RM setting is the local document setting ?

**Comment by ddvk** [comment]
it seems that this was a bug, the document setting was ignored and i'll fix it

**Comment by leifan89** [comment]
Thank you!
