### ISSUE TITLE
How is this done.

### ISSUE THREAD

**Issue by vale981** [ddvk/remarkable-hacks#154]
Hi,

This a rather naive question, but what is your method when creating these patches.
Do you disassemble the binary and go through the assembly and overwrite part of the code? (I am guessing that the new features are written over the onboarding.)

I have never done such a thing but find it very intriguing and would like to start hacking on the rm software myself.
Do you have any pointers to reading material to get me started?

Thank you very much :}

**Comment by Eeems** [comment]
https://github.com/ddvk/remarkable-hacks#how-do-you-make-the-patches

**Comment by vale981** [comment]
Yay, RTFM. But this seems a little sparse :)

**Comment by Eeems** [comment]
That's intentional as sharing anything else would technically be breaking the EULA.

**Comment by LeifAndersen** [comment]
Hello,

If you have experience with programming, but not with reverse engineering (or systems in general), I recommend going through a bunch of labs in CS:APP:

http://csapp.cs.cmu.edu/3e/labs.html

In particular, the Bomb Lab and the Attack/Buffer labs.

It won't tell you a single thing about how these hacks, or even the remarkable works, but it _will_ help you get started with both some reverse engineering tools and mindsets in an environment where you can ask questions and get help.

**Comment by vale981** [comment]
Thank you a lot. This is exactly what I was looking for :)
