### ISSUE TITLE
Feature request: restore sleeping.png and transparent wallpaper support

### ISSUE THREAD

**Issue by sersorrel** [ddvk/remarkable-hacks#157]
fw 2.5 removed the ability to modify the light-sleep wallpaper `sleeping.png`, and also broke transparent suspend/poweroff wallpapers (they're now placed on top of a white background). i don't know if it's feasible for you to do, but it would be awesome if remarkable-hacks could restore the ability to use transparency in wallpapers and to modify the light-sleep wallpaper.

**Comment by dstango** [comment]
I thought I were the only one missing exactly these removed unofficial "features" ...
I totally second it, if it's feasible in any way.

**Comment by dstango** [comment]
wow, thanks!

**Comment by Pemo11235** [comment]
I tested and trasparancy still  doesn't work on mine (2.5)


p.s. I love other new features ! Thanks a lot!

**Comment by tsang** [comment]
Wow would be awesome, excited for this fix too.  But judging from the patch it seems like its only for rm1.  I'm sure @ddvk will get around to rm2 soon enough :-)

**Comment by tsang** [comment]
Got the update, works for me.  Great work, can’t imagine the RM software without your enhancements @ddvk

**Comment by dstango** [comment]
sleeping.png and suspended.png doesn't work with the patch for the version 2.6 (rm1) any more :-(. Any chance to resurrect the support?

**Comment by technicalguy** [comment]
My sleeping.png has working transparency only if I press the sleep button. If I leave it for 20min to auto-sleep then it appears against a white background. :cry:
