### ISSUE TITLE
Pinch-to-zoom -- different start-zoom-factor

### ISSUE THREAD

**Issue by dstango** [ddvk/remarkable-hacks#158]
I like the pinch-to-zoom, yet I'm wondering if it's possible to have a different start-zoom factor. The rm normaly starts with 200% but if you go on "-" it switches to 133%.
Can we have
- either a different start zoom factor (133%) - maybe configurable for different people's needs
- or the option when "pinching backwards" from 200% to go to 133% instead of 100%

Besides that it would be cool to be able switch on the swipe gestures for zoom separately (I have them usually turned off because of acidental activation, but while zooming I would be happy to have them).

**Comment by ddvk** [comment]
obsolete
