### ISSUE TITLE
Need help!! Possibly relevant - power button nonresponsive rM2 2.5.0.27

### ISSUE THREAD

**Issue by katiebobus** [ddvk/remarkable-hacks#160]
I'm not sure whether it has worked since I installed the last patch (it may have once or twice), but there's nothing physically wrong with the button. Gestures and pen all worked fine yesterday, but noticed I couldn't suspend. Finally it fell asleep and now I can't wake it. It was at 85% charge or more when this happened. Tried various button press durations, charged overnight on a different charger, no luck. Can't connect SSH with it asleep. Any advice??? I did leave a msg with Customer Svc but I don't think they'll get back to me soon (or like that i've rooted it). https://drive.google.com/file/d/1KTi9Ll5xUm1kfq0_e9fF1AT79ErvLxeB/view?usp=sharing

**Comment by Eeems** [comment]
Technically you haven't rooted the device. It comes pre-rooted from reMarkable.

I see you closed this an hour later, I guess that means you've sorted it out? The file you linked requires extra permissions to open.

**Comment by katiebobus** [comment]
I got it responding so I closed it out. Thanks!
