### ISSUE TITLE
Pinch to zoom not working (?)

### ISSUE THREAD

**Issue by jdschw** [ddvk/remarkable-hacks#162]
Pinch to zoom doesn't seem to work on my Remarkable. It doesn't have any effect. I'm wondering if I'm doing something wrong - do I need to initiate the "pinch" in a particular part of the screen, like the undo swipe left?

**Comment by llinfeng** [comment]
Before anything, the pinch needs to be pretty fast. This is intended to reject palm motion as pinching. (Credits: https://github.com/ddvk/remarkable-hacks/issues/149#issuecomment-743745780)

The trick is to use the index fingers at the same time and to perform the motion horizontally. Both for zooming in and for zooming out. Note, this is not meant to be a continuous zoom: the first pinch gets you 200% zoom. The next pinch motion gets you to 400%.

**Comment by ddvk** [comment]
also make sure only 2 finger are making contact i.e not resting your palm

**Comment by jdschw** [comment]
You're right! It works! Thanks!
