### ISSUE TITLE
Tap to Change Page Too Sensitive

### ISSUE THREAD

**Issue by craneml** [ddvk/remarkable-hacks#164]
I'm using a remarkable2, used to left- and right-swiping to change page.  I installed ddvk this morning and suddenly, my pages are jumping all over the place.  I find that when I'm writing, I'm putting my hand down on the tablet, and I'm actually triggering the page turns.

Is there a way to disable this functionality?  Thanks.

**Comment by sersorrel** [comment]
you can disable the swipe gestures in the share menu (immediately above the eye symbol), though it sounds like you maybe accidentally activated reader mode – if you see a "M" at the top of the menu, that means you are in reading mode, so the page-turn gestures are just a tap, not a swipe (which is prone to accidental activation if you're writing, hence "reading mode"). you can turn off reader mode by long-pressing that M.

**Comment by craneml** [comment]
OMG genius.  Yes, I was somehow in Reading mode.  Wow, sorry about that.
