### ISSUE TITLE
Update issue: Remarkable 2 update and bookmark stop working

### ISSUE THREAD

**Issue by analeighgui** [ddvk/remarkable-hacks#167]
Hi! I updated my remarkable 2 system and reinstalled the hack, then found out the bookmark can't work anymore. Does it happen to anyone else? Thanks!

**Comment by ddvk** [comment]
are the bookmarks enabled in the share menu?

**Comment by analeighgui** [comment]
It's my bad. I didn't enable my bookmarks in the share menu. Thanks!
