### ISSUE TITLE
Patch kills thumbnails in list view.

### ISSUE THREAD

**Issue by cipioh** [ddvk/remarkable-hacks#169]
In 2.5.0.27, rM has enabled the ability to use the first page or last page as the cover... probably stealing your code to do it lol. However, in their implementation, it actually shows the cover image in list view (not just in grid view).  After applying patch 17.2.04, the list view image has been replaced with a generic notebook image rather than displaying the first/last page as selected.  Grid view continues to work as expected.  

![image](https://user-images.githubusercontent.com/30559882/103412616-0e9d9600-4b44-11eb-8616-a6560f0798eb.png)

**Comment by ddvk** [comment]
yes, i'll add an option. it is just that the height is reduced to pack more lines
