### ISSUE TITLE
Reading mode - page turns backwards?

### ISSUE THREAD

**Issue by Tridens92** [ddvk/remarkable-hacks#17]
Hi, two questions re: reading mode:

1) When I tap the screen, it appears that page turns are backwards.  If I tap the left side of screen, it advances to next page, and when I tap the right side of screen it goes to prior page.  Am I doing something wrong?  Perhaps this is because I'm a lefty, and have the UI in left-handed mode?

2) Besides the obvious answer of "for reading", can you explain functions (or restrictions) of reading mode?

Thanks again for this incredible hack!

**Comment by ddvk** [comment]
1. most probably, forgot about left handers, will fix it.

2. yes, i use the tablet mostly for reading and also as an experiment

**Comment by Tridens92** [comment]
Great, thanks for the info!

**Comment by ddvk** [comment]
should be fixed now

**Comment by Tridens92** [comment]
Great!  Thanks so much for your work.
