### ISSUE TITLE
pinch to zoom on remarkable 2

### ISSUE THREAD

**Issue by AqsaKashaf** [ddvk/remarkable-hacks#170]
I am not able to zoom in or out on remarkable 2 using gestures.

**Comment by Eeems** [comment]
https://github.com/ddvk/remarkable-hacks#quick-doc
Pinch to zoom.

**Comment by daendeleon** [comment]
Pinch-to-zoom is an option that isn't enabled by default.  You have to open the "Share" menu and make sure "Pinch Zoom" is on.  

@ddvk I may have missed it in the readme but in case I didn't could you maybe mention the above?  It confused me, too.  Really love this patch!

![20210101_182622](https://user-images.githubusercontent.com/3653187/103443472-d9866600-4c5f-11eb-9701-67907f6b9c70.jpg)

**Comment by Eeems** [comment]
> @ddvk I may have missed it in the readme but in case I didn't could you maybe mention the above? It confused me, too. Really love this patch!

@daendeleon You should open a PR adding it to the readme ;)

**Comment by ddvk** [comment]
i added a remark in the readme
