### ISSUE TITLE
Feature request: landscape mode for pdfs

### ISSUE THREAD

**Issue by zampanoo** [ddvk/remarkable-hacks#172]
Thanks for the useful features which I was able to add to my new RM2. 

I wonder whether it would be possible to rotate pdf files into landscape mode. Many of the academic papers I wish to read and annotate on the device are A4 and come out on the small side when displayed in A5. Landscape mode would allow one to read an A4 page in two parts - top first and then the bottom. This works well (for me) on another e-ink device with the same screen size. Thanks!

**Comment by ddvk** [comment]
sorry, beyond my capabilities. 

also there are external tools that can do that sort of thing, eg https://www.mankier.com/1/mutool#Poster
or https://sourceforge.net/projects/briss/

**Comment by zampanoo** [comment]
Thanks for looking into my suggestion. I have no coding insight, so I wasn't aware that I'd ask for something difficult. -
Enjoying the existing features on a daily basis...
