### ISSUE TITLE
How do you "activate" the "Extras" ?

### ISSUE THREAD

**Issue by lakicsv** [ddvk/remarkable-hacks#174]
This is a fantastic piece of software!! Thanks a million for ddvk and anyone who helps him to maintain it!

Reading the "Quick docs" I noted the following feature:

Extras:
email and hwr for scribbles on pdfs
extract scribbles from pdfs into new notebook

Especially extracting scribbles from pdf into a separate notebook would be very useful, but I cannot figure out how to do it...

Can anyone tell me how to use this feature?

Thanks a million in advance:

-Viktor

**Comment by ddvk** [comment]
those should just work

eg to extract from pdf overview, move, moveout, new notebook

**Comment by damian0815** [comment]
it works, but it unfortunately messes up the scribbles on the pages following the selected pages..
