### ISSUE TITLE
Layer visibility bug

### ISSUE THREAD

**Issue by thagotaberry** [ddvk/remarkable-hacks#176]
I think I found a bug/weird behaviour: when pressing the layer visibility eye, it hides all but the current layer (so far so good). When I press the eye again, it toggles to the background layer only (Template). When pressing again, it toggles back to the layer I originately came from, with all other layers hidden.
I don't understand this behaviour - why would I want to toggle to the background layer only, w/o any of my marks?
Would't be toggling between "all on" and "current only" be more useful? Or was it the intention but there is a but?
Thanks for the good work!

**Comment by dstango** [comment]
This might be a duplicate: https://github.com/ddvk/remarkable-hacks/issues/74

**Comment by ddvk** [comment]
the general idea was to write on a document and toggle the background visibility, before recent files were added (also it is a bit faster) and then export to a new notebook.

**Comment by thagotaberry** [comment]
> This might be a duplicate: #74

Ah, right. Sorry I missed that.

> the general idea was to write on a document and toggle the background visibility, before recent files were added (also it is a bit faster) and then export to a new notebook.

Got it. Was just wondering... Now it makes sense.
Thanks for you!
