### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by kosmosu** [ddvk/remarkable-hacks#177]
I've installed this hack with no issue outside of the timezones not exactly syncing correctly. I'm currently in the America/Los Angeles timezone, but the time appears to be incorrect.

**Comment by dstango** [comment]
You have to set the timezone manually: https://github.com/ddvk/remarkable-hacks#timezones

**Comment by kosmosu** [comment]
I did, it took an hour or so but it appears that the time corrected itself.
