### ISSUE TITLE
Lamy Button Stops Working under Toltec/Oxide

### ISSUE THREAD

**Issue by Snowflake6** [ddvk/remarkable-hacks#180]
I will be creating an issue in the Toltec/Oxide repository as well, but wanted to give a head's up here just in case there is something related or something that needs to be done on both sides to correct this.

When running a remarkable-hacked xochitl under Toltec with the Oxide launcher, the Lamy button hack no longer works.  Other hacks (extra icons in the menu, zen mode, etc.) all seem to work fine, but the button press on the Lamy is not recognized anymore.

A clean restart of xochitl outside of Toltec/Oxide returns the functionality, so this is likely something Oxide is doing... But on the off chance it's not, I wanted to pass it on.

**Comment by Eeems** [comment]
This likely should be opened on the oxide repo as I don't think it's an issue with remarkable-hacks. More likely it's that oxide isn't launching xochitl with the required environment variables, or arguments to ensure that the button works.

**Comment by ddvk** [comment]
correct, a param is missing. the plugin could be made global, but then it would load in any qt app

**Comment by Eeems** [comment]
> correct, a param is missing. the plugin could be made global, but then it would load in any qt app

Is there a reason that wouldn't be ideal?
