### ISSUE TITLE
Possible [Bug] found + [Feature Request] 

### ISSUE THREAD

**Issue by MBrablc** [ddvk/remarkable-hacks#183]
I am using the rm-hacks in combination with the Funkey's jagged line fix (it is a good solution to the problem, maybe consider including it in the rm-hacks? It's not the best solution possible - there are better algorithms than moving average filter, but it is good enough).

I found a possible BUG - when you choose the battery indicator ON, it overlays over the "notebook settings" button, and make it not accessible, which is quite annoying. I would suggest omitting some of the less used buttons (like page numbers or previous/next page arrow) to make space for it.

Also, I find the line thickness number, which is shown over the small menu button (when the toolbarr is hidden) quite annoying. How about making something like the reading mode without the page-turning so that it can be used for writing too.

Otherwise, it's a great hack, hoping for new features :-)

**Comment by ddvk** [comment]
what do you mean with not accessible, it should be still clickable

**Comment by MBrablc** [comment]
I meant that the battery icon is printed over the other button, which means you cannot click it., I will post an image later this afternoon.

**Comment by MBrablc** [comment]
![image](https://user-images.githubusercontent.com/47245656/104172506-adf44000-5404-11eb-861b-c525058d1e08.png)

**Comment by MBrablc** [comment]
As you can see, the only thing I changed was clicking the Battery ON/OFF icon. It is the same for Right-handed settings.

**Comment by cgr02** [comment]
It is just an alternative Icon, it should still have the same functionality. Did you try to actually tap on it?

**Comment by MBrablc** [comment]
@cgr02 , I did, I must have missed the tap because it works fine now.

Sorry to bother you guys, my bad, very big bad :-D
