### ISSUE TITLE
pagenum on notebooks

### ISSUE THREAD

**Issue by Brun059** [ddvk/remarkable-hacks#184]
awful extensions, really useful and designed from the users perspective : yet . page n of m is not showing anymore - and the little number on the top left next to the "round collapse" icon stays fix to 2, does not change as I swipe through the notebook.

wishful AC : page n of m is displayed again - or the number next to the the collapse icon shows the current page number

**Comment by dstango** [comment]
the "2" on the "round collapse" icon is the pen width

**Comment by Brun059** [comment]
Thx, then i miss the page nbr even more...

**Comment by ddvk** [comment]
you can enable the page x of y when the menu is hidden from (Page Numbers)

**Comment by Brun059** [comment]
workarounds exist....
