### ISSUE TITLE
Pen sizes - can you add Highlighter sizes as well?

### ISSUE THREAD

**Issue by Tridens92** [ddvk/remarkable-hacks#185]
Any chance you can add the ability to choose highlighter width?  This is a bizarre omission from rM.  Depending on what text one is reading, the highlighter can be too wide -- underlining multiple lines, or too narrow.  This would be a great addition if you could pull it off!

**Comment by ddvk** [comment]
i dont think  I can

**Comment by Tridens92** [comment]
OK, I figured I'd ask, as this seems like a weird exception for the rM stock tools (that only this pen wouldn't have width setting).

**Comment by ddvk** [comment]
they use a different way of drawing
