### ISSUE TITLE
Using with Remux or Oxide causes major issues

### ISSUE THREAD

**Issue by nullstalgia** [ddvk/remarkable-hacks#188]
So, I will be posting my findings on their issue threads as well in case the fault lies with them, feel free to poke in!

I installed [toltec](https://github.com/toltec-dev/toltec) to my rM1, which had entware, and a lot of other gunk just sitting around, so I did a reflash of my device with your `uuu` repo. (I don't think this is the cause of any of these issues, especially since I did `uuu upgrade` to see if the issue would be there if I re-applied the update, and everything runs fine until I combine the hack with a Launcher)

First, Remux.

https://streamable.com/ws4ep2 

(sorry for background 3d printer noise)

Sometimes, when my hand and pen touch at the same time (which is common when writing), part of the screen will refresh, and sometimes will launch an app from Remux without the menu having time to show.

It looks like Remux is listening to the input events and somehow my marker and hand equal a home button hold?

Second, Oxide.

This I don't have as much testing with, as I preferred Remux.

The behavior I saw, was that after enabling Zen Mode, pressing any of the physical buttons would act as if I was holding it down, regardless of how long I actually touched it.

**Comment by Eeems** [comment]
Oxide creator here. Oxide handles buttons differently than other launchers, it only emits a button press to the underlying application if it's released before 700ms has passed. Which makes it odd that you are seeing it as if the button is being held down, as I don't experience that behavior on my device.

Any chance you could grab some log files from tarnish while this is happening and perhaps from xochitl as well?

**Comment by nullstalgia** [comment]
Remux's dev has found that disabling their launcher's swipe gesture fixed the issue on their side.

And currently, I am unable to reproduce this issue right now. Apologies for not doing more testing beforehand.

However, the shortcut of pressing L and R at the same time to enable Zen Mode does not work when using Oxide.

**Comment by Eeems** [comment]
> However, the shortcut of pressing L and R at the same time to enable Zen Mode does not work when using Oxide.

Can confirm, could you open an issue on the oxide repo as it's an oxide issue: https://github.com/Eeems/oxide/issues

**Comment by ddvk** [comment]
closing this...
