### ISSUE TITLE
Eraser toggle on Lamy button press

### ISSUE THREAD

**Issue by bordaigorl** [ddvk/remarkable-hacks#19]
I got a [Lamy pen](https://www.lamy.com/en/emr/), which is compatible with reMarkable tips and works really well.
The pen has a handy button which would be useful as an eraser toggle, but unfortunately the remarkable ignores its events.
In `/dev/input/event0` you get:
- `type: 1 code: 331 value: 1` on button down
- `type: 1 code: 331 value: 0` on button up

Would it be possible to patch the event loop so that these events are properly handled?

For me this solution would be even superior to the new Marker with eraser since I would be able to use the precision of the marker tip to erase...

**Comment by ddvk** [comment]
i have to get my hands on one.
i think you can get this to work without patching xochitl much

you can load qpa plugins e.g (
`QT_QPA_GENERIC_PLUGIN=evdevtablet xochitl`
or `QT_QPA_GENERIC_PLUGIN=evdevkeyboard:/dev/input/event0 xochitil`

will have to modify the plugin to emit some keycode (https://code.woboq.org/qt5/qtbase/src/platformsupport/input/evdevtablet/qevdevtablethandler.cpp.html)

**Comment by dstango** [comment]
I'm willing to sponsor you a Lamy as a little thank you for your great work. Send me a private message and we'll work out how you get one.

**Comment by ddvk** [comment]
> I'm willing to sponsor you a Lamy as a little thank you for your great work. Send me a private message and we'll work out how you get one.

thanks, really appreciate it, but no need. i’ll order one

**Comment by slowan** [comment]
> I got a [Lamy pen](https://www.lamy.com/en/emr/), which is compatible with reMarkable tips and works really well.

Thanks for the pen tip. Luckily they just have it now on "a____n de" for just 29.

It would be awesome to have the eraser switch on the button.

**Comment by Tridens92** [comment]
Wow, this would be an incredible feature.  Having no eraser is my biggest grip with rM v. 1.  Just ordered a Lamy two weeks ago.  I would be so grateful for this addition to an already incredible hack.

**Comment by ddvk** [comment]
while i'm waiting for the pen to arrive, i did some experiments. you can try if it works (early prototype) 

https://github.com/ddvk/remarkable-stylus

the latest patches should respond to ctrl-u for toggling the eraser

**Comment by burgarth** [comment]
They do- amazing!!!! Thanks so much!!!

**Comment by dstango** [comment]
Great, it works!!!
Suggestion (might be personal preference): 
(right now a single button press toggles pen/eraser) -- it might be handy to have the button act like "while button pressed = eraser, while button released = pen", because the button is right in the reach of the index finger.
caveat: that might get tricky when lifting the pen while the button is still pressed, and then releasing the button too high up in the air.

**Comment by bordaigorl** [comment]
Thoroughly impressive!!!

Maybe I'm misunderstanding something: is this supposed to work with standard xochitl or only with a patched one?
If the latter: what is the minimal patch needed to make this work?

**Comment by ddvk** [comment]
> Thoroughly impressive!!!
> 
> 
> 
> Maybe I'm misunderstanding something: is this supposed to work with standard xochitl or only with a patched one?
> 
> If the latter: what is the minimal patch needed to make this work?

only with the lastest patch

**Comment by bordaigorl** [comment]
I can confirm it works.
I would also prefer the eraser to be toggled back on button lift.
Well done!

**Comment by ddvk** [comment]
try try patch (with hold to erase)
```
sh -c "$(wget https://raw.githubusercontent.com/ddvk/remarkable-hacks/master/patch.sh -O-)" _ patch_06_01
```

**Comment by burgarth** [comment]
Thanks! It should be 

> sh -c "$(wget https://raw.githubusercontent.com/ddvk/remarkable-hacks/master/patch.sh -O-)" _ patch_06_1

I suppose (without a 0). But this patch did not work for me, the button does not do anything with it. patch_06 works wonderfully though.

Cheers Daniel

**Comment by dstango** [comment]
Patch 06_1 works like a charm for me -- eraser toggle back when lifting the button -- great!!!!
Thank you!

**Comment by slowan** [comment]
> 
> 
> try this patch (with hold to erase)
> 
> ```
> sh -c "$(wget https://raw.githubusercontent.com/ddvk/remarkable-hacks/master/patch.sh -O-)" _ patch_06_1
> ```

Button doesn't work with this patch. Note: I have installed  ddvk/remarkable-stylus

**Comment by ddvk** [comment]
> 
> Button doesn't work with 06_1 patch (switch nor hold). Note: ddvk/remarkable-stylus is installed on the device.
> 
> 
> 
> Patch 06 works flawlessly.

getting mixed feedback here, it should select the eraser as long as the button is kept pressed

**Comment by burgarth** [comment]
Just tried again, definitely does not do anything when button pressed with 06_1 while 06 works just fine. Restarted device in-between, did not help.

**Comment by ddvk** [comment]
my pen should arrive today so i ll be able to test it

**Comment by slowan** [comment]
> 
> 
> > Button doesn't work with 06_1 patch (switch nor hold). Note: ddvk/remarkable-stylus is installed on the device.
> > Patch 06 works flawlessly.
> 
> getting mixed feedback here, it should select the eraser as long as the button is kept pressed

I have tried it again too with same results.

**Comment by AaronDavidSchneider** [comment]
In my case both options work flawlessly

**Comment by falevian** [comment]
> Thanks! This patch did not work for me, the button does not do anything with it. patch_06 works wonderfully though.

Yo have to install also this:
sh -c "$(wget https://raw.githubusercontent.com/ddvk/remarkable-stylus/master/patch.sh -O-)"

**Comment by ddvk** [comment]
> > > Button doesn't work with 06_1 patch (switch nor hold). Note: ddvk/remarkable-stylus is installed on the device.
> > > Patch 06 works flawlessly.
> > 
> > 
> > getting mixed feedback here, it should select the eraser as long as the button is kept pressed
> 
> I have tried it again too with same results.
you sure you ran the patched version with the `-plugin` argument? anyway, added to install script

**Comment by burgarth** [comment]
> you sure you ran the patched version with the -plugin argument? anyway, added to install script
> 

Right, that must have fixed it. Thanks!!!!

**Comment by ddvk** [comment]
closing this one as fixed

**Comment by slowan** [comment]
Now it works. Possibly I haven't used the -plugin argument.
