### ISSUE TITLE
bug on rm2 -- Screen doesn't refresh

### ISSUE THREAD

**Issue by aidanjalili** [ddvk/remarkable-hacks#191]
The screen starts to "layer" very quickly after install as nothing is ever fully cleared away from it.

**Comment by aidanjalili** [comment]
I get "Pan failed: Invalid argument" infinitely...

**Comment by ddvk** [comment]
make sure you are not running 2 xochitl instances (started by a laumcher, e.g oxide)

**Comment by aidanjalili** [comment]
No unfortunately I don't think there are two instances running, I'm using remux which I don't think has one running anyway, but even preceeding the installation with "systemctl stop xochitl" doesn't fix the issue

**Comment by ddvk** [comment]
you should stop remux first, before the installation. after the installation you can stop xochitl and run remux again.

**Comment by aidanjalili** [comment]
That worked, thanks!

**Comment by aidanjalili** [comment]
That worked, thanks!
