### ISSUE TITLE
Missing documentation about features related to buttons and rM2

### ISSUE THREAD

**Issue by Gaibhne** [ddvk/remarkable-hacks#194]
As I understand, the rM1 had buttons, and some functionality is apparently tied to them. The rM2 does not have buttons, but it is unclear from the readme what that means. Does the rM2 not support many of the "best" features such as going to first/last page, switching to eraser, undo, or the whole 'reading mode' at all ?

If there is another way to access those features, it would be cool if that could be added to https://github.com/ddvk/remarkable-hacks/blob/master/docs/features.md

If there is no way to access those features at the moment, it would be nice if we could get some info on whether there are plans on adding them to the rM2 in the futures or anything like that.

**Comment by dstango** [comment]
I'm a rm1 user and button fan, so I'm no great help -- but: I've noticed quite some discussions about button-functions having equivalent realizations by swipe gestures - in certain areas of the screen, or with two finger, or in certain directions, or the likes. Maybe do a search in issues with the keyword "swipe", see what you come up with, and maybe even create a pull request with the condensed information you collect.

**Comment by dstango** [comment]
even better: just noticed in the readme.md of the current patch level some swipe gestures mentioned. I'd recommend checking these readme-files out to find out more!

**Comment by dstango** [comment]
even better, better: check out the readme.md of the main page -- there you have them swipe-gestures!

**Comment by Gaibhne** [comment]
Thanks, that is awesome!
