### ISSUE TITLE
Zoom selection tool bizarre consequences on pen selection

### ISSUE THREAD

**Issue by rayanelhelou** [ddvk/remarkable-hacks#195]
### Consider this scenario (Zen or otherwise):
The current pen is X and the previous pen is Y. (for any X & Y)
Then, I select the Zoom selection tool, **and I actually use it**. It zooms in, great. However, now the current pen is Calligraphy (might be different for you), and it's neither pen X nor pen Y (previous two).

Please let me know if you understood what I meant. I expected it to behave in one of the following ways if it was working:

Select Zoom selection tool >> use it >> previous pair of pens restored.
    OR
Select Zoom selection tool >> use it >> Zoom selection tool remains active & last pen becomes previous.

### On a separate note:
When the Zoom selection tool is selected, the icon on the top left (I'm right-handed) is the icon of a Ballpoint pen (not of a square with a magnifying glass). Assuming the pen issue above is resolved, this icon issue here is still relevant as we might accidentally zoom when thinking we're using the Ballpoint pen as suggested by the icon.

**Comment by ddvk** [comment]
this seems to be a bug in the stock version, on the rm2

**Comment by rayanelhelou** [comment]
I should have clarified, I'm using rm1, not rm2.

1. It looks like the first issue is fixed, yet with a minor low-priority issue: after applying zoom selection, pen order is flipped which means one needs to click the right button (on rm1) to switch back.

2. The icon problem remains: Say for example you hide the menu bar after clicking on the Zoom selection tool (to see left of screen), the tool looks like a Ballpoint pen, not like a zoom icon.

Other than those, your patch has significantly improved the experience so far. Thanks, and I'm very appreciative of your hacks!!! :)

**Comment by ddvk** [comment]
the icon should be fixed now

**Comment by rayanelhelou** [comment]
All problems solved perfectly!
I'm closing this issue - thank you so much for your help!
