### ISSUE TITLE
Is there a way to turn the X to close document in upper right back on?

### ISSUE THREAD

**Issue by Crash331** [ddvk/remarkable-hacks#197]
The only way I can see to close a document is by swiping.  Is there a way to re-enable the X in the top right corner?

**Comment by ddvk** [comment]
there is a close button (X) in the document options menu (bottommost  icon). most people complain (me included) that the X button gets in the way. also the upper right corner is used for bookmarks...

**Comment by Crash331** [comment]
Ah, found it!  Wish it wasn't 2 clicks, but that works.  Thanks!
