### ISSUE TITLE
Recent files shows permanently deleted files

### ISSUE THREAD

**Issue by JJKR1968** [ddvk/remarkable-hacks#199]
My recent files list shows files that I have permanently deleted, i.e. moved to the trash bin and emtying the trash bin. I am also still able to open them. 

I have the impression that this is the case since I stopped syncing to the cloud (for company security reasons).

(I would prefer that the deleted files that are still in the trash do not show up in the recent files list anyway.)

**Comment by ddvk** [comment]
i think that it was mentioned somewhere that "deleted" files don't get deleted, if the device is not syncing (they stay in the filesystem). 

i'll remove files in the trash from recent files

**Comment by JJKR1968** [comment]
Is there a way to delete the deleted files from the filesystem? Where are they located?

I do appreciate it if you remove them from the recent files.

**Comment by ddvk** [comment]
this should be fixed now i.e files in the trash should be no longer visible
