### ISSUE TITLE
mv: write error: No space left on device

### ISSUE THREAD

**Issue by m-shiokawa** [ddvk/remarkable-hacks#2]
This warning pops out for me when trying to make it permanent, then the tablet crashed and reverted me back to 1.8. I believe it is due to the limited space available in /usr, and how previous installed binary patches take up spaces.

**Comment by ddvk** [comment]
Thanks for the report. The root partition getting full is a known problem, i'll add a check.

The patched file has the same size, so it's strange that it can't just get replaced.
