### ISSUE TITLE
Feature Request - Eraser footprint

### ISSUE THREAD

**Issue by Tridens92** [ddvk/remarkable-hacks#20]
One of the things that I find difficult about the rM eraser is that there's no indication, visually while erasing, of the footprint of what will be erased.  Is there any chance you could add something like Photoshop's visual indicator of eraser footprint, as shown in this video?

[https://youtu.be/NpKOcPIK2oY?t=30](https://youtu.be/NpKOcPIK2oY?t=30)

Perhaps the refresh rate of the e-ink screen makes this unworkable, but I figured I'd ask.  Thanks so much for considering this addition to an already fantastic hack!

**Comment by ddvk** [comment]
this is way beyond my level

**Comment by Tridens92** [comment]
Thanks for letting me know, and for your great work.  It's all way beyond my level!  :)
