### ISSUE TITLE
Accidental zooming out

### ISSUE THREAD

**Issue by Cindy-Jie-01** [ddvk/remarkable-hacks#200]
When I'm using pinch-to-zoom, sometimes while zoomed in and I'm writing, it would randomly zoom out. What I think is happening is that maybe it's picking up my wrist movement slightly sliding across the screen as pinching. Is there a way to maybe finetune the sensitivity to trigger zooming out?

**Comment by ddvk** [comment]
it is finicky, that's way there is a toggle. pinching is just 2 points that have a decrease in distance in some amount of time. i'll see if some refinement is possible.

**Comment by folofjc** [comment]
@ddvk Ah, it is time based. Does this mean that slower or faster pinching is better? Thanks!

**Comment by ddvk** [comment]
zoom in stock sw
