### ISSUE TITLE
25027 on rM2 causes strange visual artifacts with remux running

### ISSUE THREAD

**Issue by jdkruzr** [ddvk/remarkable-hacks#201]
It seems like things aren't redrawing correctly. This is while running the install script with no specific version selected (without setting permanently, obviously).
![signal-2021-01-25-024353_001](https://user-images.githubusercontent.com/618198/105682028-e8a7af00-5ebf-11eb-8b09-6035adb6d427.jpeg)

**Comment by Pemo11235** [comment]
Try to use testing version of Remux

**Comment by jdkruzr** [comment]
This is the testing version.

**Comment by ddvk** [comment]
if you are starting it through remux, stop xochitl first to prevent 2 xochitl instances runing, because the installscript is unaware

**Comment by jdkruzr** [comment]
if I make it permanent, how do I un-make it permanent if it's still messed up?

**Comment by Eeems** [comment]
> 
> 
> if I make it permanent, how do I un-make it permanent if it's still messed up?

https://github.com/ddvk/remarkable-hacks#revert-in-case-things-go-terribly-wrong
