### ISSUE TITLE
Port22

### ISSUE THREAD

**Issue by marraccinom30** [ddvk/remarkable-hacks#205]
I have an issue where when I type ssh root@10.11.99.1 into my cmd prompt it gives me an error stating "ssh: connect to host 10.11.99.1 port 22: Connection timed out"

**Comment by Eeems** [comment]
Is your device connected via USB?

**Comment by ddvk** [comment]
out of scope

**Comment by marraccinom30** [comment]
> Is your device connected via USB?

yes

**Comment by Eeems** [comment]
Does it show up as a device?

**Comment by marraccinom30** [comment]
> Does it show up as a device?

no it is not

**Comment by Eeems** [comment]
From the "Copyrights and Licenses" menu what IP addresses are listed on the bottom? (Hint, it should have 10.11.99.1 if it's connected properly).

**Comment by marraccinom30** [comment]
yeah no it's a different ip address

**Comment by marraccinom30** [comment]
> From the "Copyrights and Licenses" menu what IP addresses are listed on the bottom? (Hint, it should have 10.11.99.1 if it's connected properly).

it won't let me turn on usb interface

**Comment by Eeems** [comment]
> yeah no it's a different ip address

You should be able to connect over wifi (the other IP address).

> it won't let me turn on usb interface

Sounds like one of the following might be happening:

1. Third party USB cable that doesn't do data transfer.
2. Computer isn't doing a proper handshake with the device to let it know it's properly connected so it's not bringing up the network interface.
3. You are using a USB hub that doesn't play nice with the device.
4. Something is wrong with the USB port on the device.

I would suggest looking at dmesg on the device when you plug the USB in to see what's happening. What OS are you running on your computer?

**Comment by marraccinom30** [comment]
my usb connection has been a little messed up for a while now. Can I do it without the usb connection. And I'm not sure where to see the dmesg but I am using windows 10.

**Comment by marraccinom30** [comment]
> > And I'm not sure where to see the dmesg but I am using windows 10.
> 
> You'd run dmesg on the **device**.
> 
> > I would suggest looking at dmesg on the **device** when you plug the USB in to see what's happening.
> 
> > my usb connection has been a little messed up for a while now. Can I do it without the usb connection.
> 
> Have you tried with another cable, other ports on your computer, or with another computer?

I've tried other cables and the other suggestions but I think my usb port is messed up.

**Comment by Eeems** [comment]
Does `dmesg` on the device report anything?

**Comment by marraccinom30** [comment]
no it doesn't but it's charging

**Comment by Eeems** [comment]
So there is no output on dmesg at all when you plug in the device?

**Comment by marraccinom30** [comment]
no

**Comment by Eeems** [comment]
Could you paste the output? I find it hard to believe that there would be nothing yet the device starts charging.

**Comment by marraccinom30** [comment]
![IMG_1617](https://user-images.githubusercontent.com/55815428/111799498-7476ff80-88a1-11eb-8a51-49b8c99de412.jpg)

**Comment by Eeems** [comment]
That isn't `dmesg` output. You'll need to SSH into your device using the other IP address and run the `dmesg` command.
