### ISSUE TITLE
No support for Version 2.5.1.45

### ISSUE THREAD

**Issue by ctuesday** [ddvk/remarkable-hacks#206]
My device came with the latest version of the software, and the script ran from the repository says "The version the device is running is not supported, yet. 20201216142449"

**Comment by ctuesday** [comment]
SHA1 of version is c5337f952554ae40f0c97d81cf1c4a126c9cc593

**Comment by philpalmieri** [comment]
came here to post the same thing..  happy to share anything needed to support it

**Comment by ddvk** [comment]
can you upload the xochitl binary somewhere?

**Comment by philpalmieri** [comment]
sure, is it a copyright issue to post it publicly? i can share a private link too

**Comment by philpalmieri** [comment]
@ddvk https://1drv.ms/u/s!AqE7Oo4FHrVai4osvt16q9C7T3TrOA?e=KVDcSB

**Comment by ddvk** [comment]
based on the infos provided, I pushed something that should work, but feedback is appreciated.

**Comment by philpalmieri** [comment]
awesome, thank you.. ill test tonight after work - just in case it messes up, i need my rm2 today

**Comment by Tridens92** [comment]
Just upgraded to an rM2, and am currently testing this fix.  Will report back. Thanks, @ddvk !

**Comment by ddvk** [comment]
i guess it is working, because noone complained

**Comment by philpalmieri** [comment]
sorry, i haven't had a chance to test it yet... avoiding risk while in meetings

**Comment by ctuesday** [comment]
Yep! This works so far for me. Thanks, @ddvk !

**Comment by philpalmieri** [comment]
![image](https://user-images.githubusercontent.com/170333/106928133-deb45600-66e0-11eb-873e-7dd8be4e71fc.png)
confirmed, thanks

**Comment by Tridens92** [comment]
Confirming that it's working for me as well.  Thanks for rapid rollout, @ddvk !

**Comment by antoniogois** [comment]
Hi! I noticed some issues, but I haven't tried previous versions (so I don't know if these issue are exclusive to 2.5.1.45)
- pinch to zoom is quite unresponsive. often it doesn't work, or only works if I pinch twice
- after I zoom-in, I can't use my finger to act on that little map of the page [which changes the region of the page currently displayed]

If it makes a difference, I'm using the left-handed config (so the tiny map appears on the left-hand side, not right-hand)

**Comment by Eeems** [comment]
@antoniogois First look through existing issues, if you can't find an existing issue for what you've found, open a new issue instead of commenting on a closed issue.

**Comment by codetoimprove** [comment]
> @ddvk https://1drv.ms/u/s!AqE7Oo4FHrVai4osvt16q9C7T3TrOA?e=KVDcSB

Many thanks 
I'm a fool! Can you please explain how I can install this xochitl on my remarkable 2 version 2.5.1.45
I know how to connect to the ssh/FileZilla, many thanks !

**Comment by dstango** [comment]
@codetoimprove: check out the README.md of this repository and look for the headline "Automagic" -- it tells you how to install the hacks.
