### ISSUE TITLE
Feature Add:  Project Workbook and progress bar

### ISSUE THREAD

**Issue by deMontfort** [ddvk/remarkable-hacks#207]
New Addition Functionality:  The “Project Workbook Folder”.

Summary:  Folder functionality allowing for a project notebook and rudimentary status tracking.

Within Remarkable: 
Add a Project Workbook folder.  New Project Workbook folder appears next to all other folders.

Tap into project folder.  Page layout view of project pages.  First page is a project summary.  Tap into summary page.  Enter titles of milestones in designated line-item list to track.  Dropdown Select optional template to use when generating corresponding subsequent project pages, or none to do manually.  Each line item entry will auto-generate a new template project page with corresponding title.

Exit Summary Page; return to Project Workbook showing all pages in Page Layout view.  All project note/milestone pages, with corresponding titles, appear alongside Summary Page, having been auto generated.  Editing the line item list from the Summary Page automatically changes the title, removes the page, or adds an additional note/milestone page.

Within each milestone page is a Checkbox toggle indicating completion of that milestone page.  That task progress status is reflected within the Summary Page with a checkbox next to the completed item. 

At the higher level, both the Summary Page Preview and the Project Workbook icon would reflect either a small status bar underneath or a check Mark in the top right indicating either “in progress” or “completed” status of the project.  All Individual Project Statuses become visible right next to each other at the highest folder level.

Note:  Having e-ink is instrumental to removing excess stimulation and keeping me focussed.  Need some basic integrated Planning/Organizing functionality that centers around the current platform.

Audience:  All Remarkable users.  Folder function easily adapted.  Flexible for multiple projects, managing ongoing client notes, major assignments, home projects, planning vacations, etc.  Particularly suited for adults who heavily multi-task, have ADD, or have no place to track project oriented notes.

**Comment by ddvk** [comment]
this is way too complicated. Now, with clickable pdf you can almost have it like described
