### ISSUE TITLE
RFE: Preference dialog to disable certain features

### ISSUE THREAD

**Issue by tomtom** [ddvk/remarkable-hacks#208]
Your hacks collection could be really awesome if there were a way to disable certain features. E.g. "Gestures: tap left or right side of screen to change pages" drove me nuts (on a RM2), which is why I uninstalled the hacks. It would be great if I could use all other hacks except this one.

**Comment by Eeems** [comment]
This already exists. Do you mean that you'd like more granular control?
![2021-02-04T075432 867](https://user-images.githubusercontent.com/1176979/106910310-558c2780-66be-11eb-968c-cdf6222f4a66.png)

**Comment by ddvk** [comment]
tap left right works only in readingMode, which you have to activate manually by tapping the M (and exit by holding the top of the menu)
