### ISSUE TITLE
Feature Add:  Calendar Integrated Workbook Folder

### ISSUE THREAD

**Issue by deMontfort** [ddvk/remarkable-hacks#209]
Additional Feature:  Calendar Integrated Workbook Folder.

Summary:  Workbook which organizes your daily notes/goals around your currently scheduled daily events.  Quick Menu access to current day.

Functionality:
Add “Calendar Workbook” to folders.  Click into calendar workbook.  A yearly summary page is contained.  Enter your yearly goals and objectives broken down by month will be tracked on the Summary Page as they are checked off on the monthly goals/objectives.

Along with the Summary Page are Twelve Monthly page previews.  Click into January.  A January month calendar appears.  Your monthly goals and objectives also appear here.  Check off objectives/goals as as they are reached or at month-end self inventory.  Click on any day in the calendar.

The day page presents your day’s schedule synced directly from your iCal, Google Calendar, etc.  Tap on any of your day’s scheduled events.  A new Note Page appears with corresponding date stamp and event heading at the top, pulled from the calendar entry.  Take meeting notes, client notes, classroom notes, parent/teacher conference notes, etc.  Assign the note to the appropriate folder.

**Comment by ddvk** [comment]
a lot of calendar/planner templates now
