### ISSUE TITLE
Bookmarks not updating

### ISSUE THREAD

**Issue by RAM-22** [ddvk/remarkable-hacks#21]
Firstly thank you for your work with this and the excellent tools.

I bookmarked & labelled some pages in a notebook and then added some new pages to the notebook. The existing bookmarks still referred to the original page numbers rather than updating to account for the new pages.

The notebook is in portrait mode.
In the "known issues" I see that "bookmark position stays the same in landscape mode" which implies that it isn't usually an issue in portrait mode.

Should this be working? If so I'll try running the latest version (the current one was installed a few weeks ago once the 2.1 update came through and I could use SSH.

Otherwise, is there an easy way to change the pages bookmarks refer to without deleting the old ones and adding new ones?

Thank you!

**Comment by ddvk** [comment]
if you meant that you inserted or moved pages, yes the boookmarks do not change, they just point to numbers, i'll add it to "known issues" (also they do not get deleted)

the bookmark positioning seems to work now and is no longer an issuse

currently there is no other way to change the page (besides manually editing the `.bookm` json file where the bookmarks are stored)
