### ISSUE TITLE
Poor palm rejection

### ISSUE THREAD

**Issue by ksaccullo** [ddvk/remarkable-hacks#214]
Palm rejection is much degraded. Just normal text entry got to next page. In several instances, it would insert / goto two to three pages in rapid succession.
 
Remarkable 2
right-hand user. 

Makes me sad. Your UI is much better than the factory, but the palm rejection problem made it unusable.

**Comment by sersorrel** [comment]
have you inadvertently enabled "reading mode" (is there an "M" at the top of the menu)? in that mode, a single tap on the screen will change page.

**Comment by ksaccullo** [comment]
You are correct. I feel a bit stupid. Sorry to have bothered you.
