### ISSUE TITLE
[Feature Request] Turning pages while zoomed in zen mode

### ISSUE THREAD

**Issue by folofjc** [ddvk/remarkable-hacks#215]
This has somewhat been mentioned in #127, #133, and #159 but this is specifically for one feature.

When zoomed in, page swipes move around the canvas. Right now, everything works great except for two things:

1. I cannot swipe down to toggle the menu. This I do not care about and I think it would be near impossible to "interpret" whether you want to pan up or to toggle the menu. Tapping in the top left is perfectly fine for me.
2. I **can** still swipe down from the very top to close the notebook while zoomed in (rM gesture). So the rM does know the difference between a swipe near the edge and not (otherwise it pans up). My problem is that when I am zoomed in and in zen mode, I cannot change the page. I have to zoom out and then swipe (assuming rM2; rM1 would require the same, OR turning off zen mode and pressing button).

Would it be possible that while zoomed in to enable some logic like:

- If swipe left AND swipe start was on right edge THEN turn page
- Same thing for the other side

So it would only move to the next page while zoomed in if you begin the swipe from the very edge (similar to how a swipe down from the top closes). If that has too many "false positives", then could also add logic that it only turns the page when you are already panned all the way to one side (right side for next page; left side for previous page).

Thanks!

**Comment by katiebobus** [comment]
For #2, it makes sense to me that the zoom function would clear with the
page change (you'd see the whole page).

I have a related zoom issue, hope you don't mind my adding it here: would
love to be able to move the zoom map/box, maybe via a long press and drag?
Rare issue, but I have had times I couldn't with on the top right corner in
zoom bc of the zoom box 😕.

**Comment by folofjc** [comment]
Yeah, it doesn't bother me if it returns to 100% on page change, as long as I can change pages! Although I do have a related request #120 to retain the zoom when returning to a page.

**Comment by ddvk** [comment]
i could add 2 finger swipe left/right for page turning while zoomed

**Comment by folofjc** [comment]
@ddvk That works for me, thanks!

**Comment by martinhess-at** [comment]
> i could add 2 finger swipe left/right for page turning while zoomed

sounds great!

**Comment by ddvk** [comment]
is this still an issue? the new zoom actually allows changing pages

**Comment by folofjc** [comment]
Sorry @ddvk, I forgot to remove this after the update in 2.6. No, this is no longer needed, the rM page turn while zoomed functionality works for me. Thanks!
