### ISSUE TITLE
Unable to cycle back to my default keyboard layout (NB_no) 

### ISSUE THREAD

**Issue by gabriofr** [ddvk/remarkable-hacks#216]
First of all, thank you so much for the hacks, really love em! 

Now to the issue: If I start cycling between keyboard layouts, I never get back to the original layout. As of now I have to restart my device to get back to it. Guess you wouldn't notice if you are using the en_US layout by default

Can the extra layouts be an option we can turn off? I've hit the button a few times by accident...

**Comment by ddvk** [comment]
should be fixed now

**Comment by gabriofr** [comment]
Can confirm the option to disable the cycle button works on RM2, also found I'm able to get back to NO_nb via the Settings->Languages menu. Thank you again!
