### ISSUE TITLE
rM2 Version 2.5.1.45

### ISSUE THREAD

**Issue by remarkable2021** [ddvk/remarkable-hacks#217]
Hi, I'm wondering if there's an available patch for version 2.5.1.45? My new rM2 tablet arrived with the update and I miss functionality of the old hacks on my rM1 (version 2.5.0.27). Thanks in advance for responding.

**Comment by Eeems** [comment]
Duplicate of #206

**Comment by remarkable2021** [comment]
Eeems, thanks a lot for the response. The patch is now working on my new device.
