### ISSUE TITLE
[Feature Request] Add plank page to pdf

### ISSUE THREAD

**Issue by Pilotprojekt** [ddvk/remarkable-hacks#218]
First of all, I really love your patches, they improve the remarkable significantly and I wouldn't want to use it without them anymore!
Thank you very much for your work.

Would it be possible to have the "add page" function in the page overview window which inserts a blank page at a set location in notebooks for PDFs as well? 
This would be useful, as there is often not enough space to do make sketches or notes.

**Comment by ddvk** [comment]
sorry, this is not possible, it would involve either generating a new pdf file every time or some other convulted way of mapping note pages to the pdf
