### ISSUE TITLE
[Enhancement] Add blank page after this one...

### ISSUE THREAD

**Issue by mig2** [ddvk/remarkable-hacks#219]
Thanks for all the amazing work here. It would be awesome if there were a hack to add a blank page to a PDF. The use case is e.g. working through a math paper where I run out of room in the margins (:-)) and would like to continue scribbling.... you may be able to do this with installation of pdftk...

**Comment by pstemper** [comment]
I believe this is a duplicate of #218
https://github.com/ddvk/remarkable-hacks/issues/218

**Comment by ddvk** [comment]
sorry, not possible, closing as duplicate
