### ISSUE TITLE
Feature request - power saving book reading mode

### ISSUE THREAD

**Issue by dstango** [ddvk/remarkable-hacks#22]
I just stumbled upon your hacks this week and love them! Great work.

I'm wondering if it's possible to make better use of the key feature of eink: not needing power to display anything.

*Idea: add a power saving book reading (not annotating) mode:*
* turn wifi off
* rm displays page, but goes to sleep mode (disable the used overlay png or use a totally transparent one)
* when pressing the left or right of the button rm wakes up, turns the page and goes to sleep again
* middle button could come back to regular mode

(if it's not possible to detect which button woke up from sleep, a double press could do: first one to wake up, second for page turn)

I'm wondering if this could result in any significant power savings, so - just for reading - the rm could actually last for days ...

(as for the regular reading mode: I'd like to be able to disable the "tapping" feature to turn pages -- I prefer the buttons, and even disabled swipes ...)

Thanks again for the great work!

**Comment by ddvk** [comment]
i tried something like that with plato, I was not very satisfied with the result, it is  still a better alternative, and yes you get which button was pressed.


then you don't need reading mode, unless you are irritated by the menu icon.
there will be no buttons on the rm 2

**Comment by dstango** [comment]
thanks, I know there will be no buttons on rm2 :-( -- bad move IMHO.

so you tried to implement such a thing with plato? Not satisfied meaning: no significant effect on battery life? Okay then ... :-/

**Comment by ddvk** [comment]
anyway, disabled the touch when swipes are disabled

**Comment by dstango** [comment]
great, thanks!
How do I update? Just do the automagic again? Or do I first have to revert to stock version and then do the automatic again?

**Comment by ddvk** [comment]
do the automatic update
