### ISSUE TITLE
RGB patches for versions newer than 24130

### ISSUE THREAD

**Issue by suushiemaniac** [ddvk/remarkable-hacks#220]
There is a patch in `tools/other` that enables `rm2fb` to expose the framebuffer in full color, as per https://github.com/rien/reStream/issues/28#issuecomment-729119025.

I'd like to use this feature to stream my display in color (see also https://github.com/rien/reStream/issues/47) but I cannot seem to find a way to patch recent versions like `patch_17.2.x` (my rm2 currently runs on version `2.5.0.27`).

Would it be possible to provide patches for newer software versions as well?

**Comment by ddvk** [comment]
you too ;)? i'll add it

**Comment by ddvk** [comment]
i pushed a patch, that should work

**Comment by mehalter** [comment]
Should this patch work for `2.5.1.45` as well?

**Comment by Eeems** [comment]
Patches are version specific. So no that wont work. @ddvk will need to provide a new version for that.

**Comment by mehalter** [comment]
Ok yeah that's what I thought. Thanks!

**Comment by dstango** [comment]
Actually the hacks have been adopted for 2.5.1.45 on the rm2 already last month.

**Comment by dstango** [comment]
https://github.com/ddvk/remarkable-hacks/tree/master/patches/25145_rm2

**Comment by Eeems** [comment]
Right, but the question was if the patch linked in https://github.com/ddvk/remarkable-hacks/issues/220#issuecomment-790082595 would also work against 2.5.1.45 or not. To which the answer is that it doesn't.

**Comment by dstango** [comment]
@Eeems: sorry ... didn't read that far up ;-).

**Comment by ddvk** [comment]
there is a patch for 2672 so closing
