### ISSUE TITLE
Kbd and Donations

### ISSUE THREAD

**Issue by Bricewilliamsinc** [ddvk/remarkable-hacks#221]
You may have addressed this, but what is Kbd (switch on or off) used for?  Also, I have to say how grateful I am for you work, you have made my remarkable2 what is should have been from the manufacture!  I do not intend to use Github for anything else but my remarkable2.  I do not write code, or have any skill set that would contribute to the community, just a "super" user, if that is a accurate description.  Is there any way to make a onetime donation to you?  If not, can I set a limit or stop being a sponsor since I am not sure how long i will use Github. Thanks again

**Comment by ddvk** [comment]
kbd disables keyboard layout switching (because the layouts were static)

about the donations, just do what feels good for you
