### ISSUE TITLE
rM2 USB-C port mode switch

### ISSUE THREAD

**Issue by tg-x** [ddvk/remarkable-hacks#222]
On the rM2 the USB-C port can be switched between host & gadget mode manually.
It'd be nice to have an UI button for this somewhere that indicates the state and allows switching via the following commands:

`cat /sys/bus/platform/devices/ci_hdrc.0/role`
`echo host > /sys/bus/platform/devices/ci_hdrc.0/role`
`echo gagdet > /sys/bus/platform/devices/ci_hdrc.0/role`

See also this [wiki page](https://remarkablewiki.com/tech/rm2_otg_pogo)

**Comment by tg-x** [comment]
Here's a [simple](https://rmkit.dev/apps/sas) UI to switch the USB-C port mode:
https://gist.github.com/tg-x/91c3af24311671544475b5b02c3877fb

**Comment by ddvk** [comment]
there is now way to execute external commands atm (there is a way, but i dont have time to experiment atm)

**Comment by Eeems** [comment]
@tg-x I'd suggest using a launcher to get a UI "button". Oxide or remux could easily have an entry that does this for you.

**Comment by tg-x** [comment]
yes i did it that way, put it in the remux launcher.
first thought a setting in xochitl would be handy but remux + simple UI works well.
