### ISSUE TITLE
[Enhancement] work in landscape but print as if portrait

### ISSUE THREAD

**Issue by cavemanesq** [ddvk/remarkable-hacks#223]
Is there a way (or hack) to use the Rm2 in landscape mode but save the document as if it were created in portrait mode. That way, you could get the advantage of having the wider page width (almost actual paper size) when writing? (Hope this makes sense)

**Comment by ddvk** [comment]
i dont get it, yet 
there is only portrait mode (landscape just moves the toolbar, but the document stays the same)

**Comment by cavemanesq** [comment]
I guess I'd like to be able to rotate the portrait-oriented page to work in landscape orientation. it would give one the ability to write longer lines of handwritten text.

**Comment by ddvk** [comment]
but what hinders you from
writing in landscape mode?

if it is the export / hwr you could use external tools

**Comment by ddvk** [comment]
I still don't get it
