### ISSUE TITLE
Unable to update ddvk

### ISSUE THREAD

**Issue by fereous** [ddvk/remarkable-hacks#224]
Any way out of this except waiting for an rm2 update?

https://pastebin.com/2SRxLe6s
rm2 2.5.0.27-patch_17.2.04-0-g41b4f55

/etc/version
20201127104549

sha256
031080d2d9bb38ae16db0fa3062f8b0f084017f09c1964badc559b735475a202  /usr/bin/xochitl

(Usual excuses apply: First time I’ve submitted an issue to Github.)

**Comment by Eeems** [comment]
Did you remove/replace the backed up original xochitl file?

**Comment by fereous** [comment]
Yes, most probably I did something stupid, though I can’t remember what or indeed why.

**Comment by Eeems** [comment]
Well if you can find the link to the current update you'd be able to get xochitl from there and replace the file.

**Comment by fereous** [comment]
Ay, there’s the rub. Going link hunting. Thank you for nudging me in the right direction.

**Comment by ddvk** [comment]
ok, here you go: https://a.uguu.se/NTbVyEbv.tgz

**Comment by fereous** [comment]
Just to be sure: shouldn’t the new xochitl (assuming that is the original) go into /home/rmhacks? Because the script still complains "/home/rmhacks/xochitl.25027_rm2 is not the original file".

**Comment by fereous** [comment]
To answer my own question: Yes, it should. Thanks mucho, ddvk, you made my day. Even the Remarkable looks happier.
