### ISSUE TITLE
Tutorial request

### ISSUE THREAD

**Issue by filipeisho** [ddvk/remarkable-hacks#225]
Hey! First of all thank you for all the features you have been working on, they are amazing! 

My thought was to do a feature request but seeing the work load... I prefer to ask if you have any resources/tutorials on how to do these patches you do for the remarkable. 

In case you want to know what I am trying to implent, I want the notebooks to be in an infinite scroll fashion.

**Comment by dstango** [comment]
Your implementation idea seems to be much more than a patch -- have a look at the file-format, especially the lines-file:
https://remarkablewiki.com/tech/filesystem#user_data_directory_structure
and you'll see you'll gonna have to do lots of work from scratch for your requirement.
(The only workaround you might try by a "patch"-approach might be to zoom in to a page at a very high zoom factor, and thus have a kind of gigantic canvas, though not infinite ...)
But maybe I misunderstood your requirement ...

**Comment by Eeems** [comment]
> I prefer to ask if you have any resources/tutorials on how to do these patches you do for the remarkable.

See #198, #94 and #154

**Comment by filipeisho** [comment]
Thanks! It is clear for me now. I will close the issue :)
