### ISSUE TITLE
Pencil v1 and Paintbrush v1 are slower

### ISSUE THREAD

**Issue by SMUsamaShah** [ddvk/remarkable-hacks#227]
On rm2. I set their width to 13 and draw with tilted pen.

Pencil draws in splashes, visible one after another and makes a repeating pattern.
Brush is more slow follows the pen far behind even after lifting the pen.

Default pencil and brush are not slow. Also default pencil does not create a repeating pattern.

**Comment by ddvk** [comment]
those were in older versions of the software and got removed, they are using a different algo probably

**Comment by SMUsamaShah** [comment]
Oh! I thought you made these brushes.
