### ISSUE TITLE
Bookmarks doesnt seem to do anything

### ISSUE THREAD

**Issue by MauPalantir** [ddvk/remarkable-hacks#23]
I click on the bookmark, icon goes black, but nothing else happens, not sure if this is how its intended to work. Im on 2113, just installed latestpatch.

**Comment by ddvk** [comment]
you have to bookmark some pages first (upper right or left corner)

**Comment by MauPalantir** [comment]
Okay, that wasn't clear. I have searched the readme on how to use bookmarks, but havent found anything like that. Thanks!
