### ISSUE TITLE
Splash Screens

### ISSUE THREAD

**Issue by nathanwinklepleck** [ddvk/remarkable-hacks#231]
I've replaced the suspended.png file as well as the sleeping.png file via FileZilla on my Mac, but all the splash screens remain the same. Am I missing something?

Sorry all; I'm a total beginner here and just got my rm2 yesterday. Loving all of you all's work on this! Amazing stuff!

**Comment by nathanwinklepleck** [comment]
By the way, I'm running the 2.5.1 patched version. Everything is working flawlessly other than that.

**Comment by Eeems** [comment]
Reboot the device?

**Comment by nathanwinklepleck** [comment]
Yep. Rebooted it. Same thing.

**Comment by Eeems** [comment]
Sounds kind of like the files haven't been replaced. Have you read them back from the device to confirm your changes are in place?

**Comment by StLa1** [comment]
This is not an issue related to the patch.
I ran into this issue, renamed the problematic files to something else, forced the rM to enter a situation where the files are displayed, then renamed them properly. No idea if it's this process that fixed the issue.
