### ISSUE TITLE
[Feature lost?] There is no way on change the writing or drawing color after install the automagic

### ISSUE THREAD

**Issue by wutever123** [ddvk/remarkable-hacks#233]
For old documents that had been used other colors, it keeps the feature on change colors to white, gray and black.  But every new documents and the old documents, that have never been changed written colors, have lost this feature.

**Comment by ddvk** [comment]
are you sure you are not using a pencil tool (mechanical or the other)? they dont have other colors except black

**Comment by ddvk** [comment]
any update?
