### ISSUE TITLE
Inadvertently installed on new version 2.5.1.45 — works fine

### ISSUE THREAD

**Issue by RhvdG** [ddvk/remarkable-hacks#234]
I didn't realise my brand new rM2 was running software version 2.5.1.45, not 2.5.0.27. The hacks installed just fine. This might be good to know for you coders.

**Comment by ddvk** [comment]
well because supported was added, but the readme was not updated

**Comment by Eeems** [comment]
Duplicate of #230, #206 and #217

**Comment by ddvk** [comment]
i updated the readme
