### ISSUE TITLE
PDF view permanently zoomed in

### ISSUE THREAD

**Issue by jamessui1** [ddvk/remarkable-hacks#236]
PDF was zoomed in prior to applying patch @ ~200%. When patch was applied, PDF was stuck zoomed in and was reporting that it was at 100% zoom. Could not pan around the page per usual.

**Comment by ddvk** [comment]
are you sure you didnt use "adjust view" to zoom the pdf? if yes, you should use that to restore the original view

**Comment by jamessui1** [comment]
you are 100% correct.....thanks!
