### ISSUE TITLE
Interlinear Annotation for Japanese Language (Furigana)

### ISSUE THREAD

**Issue by clackbib** [ddvk/remarkable-hacks#237]
Hi!
First of all thanks a ton for this remarkable collection of hacks. I followed the steps to install the Japanese font, but there is an issue when it's trying to render interlinear characters. Those characters are supposed to be rendered above the Japanese Kanji, like so:

![Example Furigana](http://ask.libreoffice.org/upfiles/14105772588630256.png)

Instead, there are rendered next to the character when reading epubs, which can make the reading quite confusing. Is there any chance this could be hacked around?

Thanks again for the amazing stuff :)

**Comment by ddvk** [comment]
i dont think so, it seems the epub renderer is buggy. 

cant you convert them to pdf first eg calibre?

**Comment by clackbib** [comment]
PDF conversion fails with some round and messes up a lot of the content formatting/page cropping :/. Epub is great, other than that particular issue

**Comment by ddvk** [comment]
i can't do anything about the rendering
