### ISSUE TITLE
Feature request - Optional pen colours

### ISSUE THREAD

**Issue by StillANixRookie** [ddvk/remarkable-hacks#24]
I wondered if it would be possible to use actual colours for the pens, highlighters etc. in a similar way to how the Sony DPT-RP1 does. The colours obviously show in grayscale on the reMarkable when you're using them, but show true on the output document when viewed on computer/smartphone etc. It would be great to have colourful notes!

**Comment by ddvk** [comment]
the colors are just a number. getting them to show would mean changing all the apps

**Comment by ddvk** [comment]
closing this as not possible at the moment
