### ISSUE TITLE
Update to 2.6.1.71

### ISSUE THREAD

**Issue by CrazyEasy** [ddvk/remarkable-hacks#242]
Please update remarkable-hacks to Version 2.6.1.71.

Thanks!

**Comment by ddvk** [comment]
i'm aware, i hope i'll have time in the next couppe of days

**Comment by RhvdG** [comment]
> i'm aware, i hope i'll have time in the next couppe of days

That would be great, thanks.

**Comment by espoirMur** [comment]
Is there a way to downgrade... I accidentally updated to 2.6 and I lost my funcitonanlity

**Comment by dstango** [comment]
There should be a backup of the original rm app for each version of the hacks you installed. You could try to restore that and reinstall the hacks. 

Btw: did you check out the beta of the hacks for the 2.6 release? Maybe that renders your request unnecessary ;-) ...

**Comment by espoirMur** [comment]
I think we can get this closed... I just installed my beta version today.

**Comment by mochar** [comment]
Does this also work for 2.6.2.75?
