### ISSUE TITLE
Quick Doc does not mention Swipe Down for thickness

### ISSUE THREAD

**Issue by StLa1** [ddvk/remarkable-hacks#243]
There is a gesture to cycle between pen thickness in the upper right corner not mentioned by the QD

**Comment by Baccanno** [comment]
Would love to use it but never got it working though ... on  2.5.1.45

**Comment by Baccanno** [comment]
I actually work great, just misreaded "upper right" corner. Btw, up gesture will cycle colors and down will cycle sizes.
