### ISSUE TITLE
Cover setting overrides native one

### ISSUE THREAD

**Issue by StLa1** [ddvk/remarkable-hacks#244]
A few versions ago the native software gained the ability to set the cover as last or 1st page.
The hack got this option long ago, but it's now redundant. In addition its setting overrides the native one, which creates a UX conflict.

**Comment by ddvk** [comment]
there is a setting go get the cover from the doc setting (Cover Page from Doc)

**Comment by StLa1** [comment]
Oh, didn't see it, thanks
Isn't it still redundant ? The system setting covers both cases (1st + last), and your button offers 1st and Follow system

**Comment by ddvk** [comment]
i am too lazy setting all by books to use the cover page

**Comment by ddvk** [comment]
i'm closing this one
