### ISSUE TITLE
Feature request: Enable handwriting/text recognition for PDF-files

### ISSUE THREAD

**Issue by dstango** [ddvk/remarkable-hacks#25]
I like to use PDF-files as forms to fill out. Unfortunately I realized I couldn't find the magic "A"-button to do text recognition on my handwritten notes. Any chance to make it available for pdf-files, too?

**Comment by ddvk** [comment]
you can test if that works for you

**Comment by dstango** [comment]
Great, works like a charm!
Thank you!!!
