### ISSUE TITLE
Anyone else using this hack having issue with the chrome extensions.

### ISSUE THREAD

**Issue by espoirMur** [ddvk/remarkable-hacks#250]
Anyone having the same issue with the chrome extension?

I am using the read on remarkable chrome extension or send to remarkable on both chrome and brave, sometimes I am sending the pages to my device but anything reached the device. But sometimes only a few reached the device. I can say 1/10 of the articles send arrives.

Yesterday I tried without the hack and I was able to get a document on my device.

I am thinking it may be related to the hack but I am not 100 % sure, just sharing in case someone else is facing the same issue. If you are sure it cannot be related feel free to close this issue.

**Comment by ddvk** [comment]
this is mostly a cloud issue

**Comment by espoirMur** [comment]
Any ideas on how to debug it?

**Comment by ddvk** [comment]
any update? this is a general cloud syncing issue

**Comment by espoirMur** [comment]
I will investigate the cloud issue this weekend.. yeah.. you can close this.
