### ISSUE TITLE
Latest Remarkable 2 Update + Patch

### ISSUE THREAD

**Issue by nirrm2** [ddvk/remarkable-hacks#252]
Hi i wanted to know if the latest update from remarkable 2 is included on the latest patch (pinch to zoom + new reader features)?
And if there's a problem installing specific patches because it didn't work, only worked with the main one

THANK YOU :)

**Comment by llinfeng** [comment]
You can check it yourself, in two steps:
1. Check your current Software version on rM2, and
2. Jump to the [homepage](https://github.com/ddvk/remarkable-hacks) for this repo and check the line that says something like "Versions 1.8.1.1-2.6.2.75" (2021-03-23). This should be at the very beginning of the ReadMe.

-----

If your Software version is included, then you are good to go. As mentioned in the [Automatic](https://github.com/ddvk/remarkable-hacks#automagic) section, you can first try out the hacks by running the following from the rM2 command-line (you'll need to SSH into it first).
```
sh -c "$(wget https://raw.githubusercontent.com/ddvk/remarkable-hacks/master/patch.sh -O-)" 
```
Once this line executes, the hacks are temporarily loaded on your rM2.

**Comment by RM2beginner** [comment]
Hi I tried to reinstall the hack to my RM2 (updated to version 2.6.2.75) by running the suggested command line but failed, it returned with a system message "TLS certificate validation not implemented", please kindly advise what to do to resolve this issue. Thanks a lot!

**Comment by ddvk** [comment]
> Hi I tried to reinstall the hack to my RM2 (updated to version 2.6.2.75) by running the suggested command line but failed, it returned with a system message "TLS certificate validation not implemented", please kindly advise what to do to resolve this issue. Thanks a lot!

is this the only measage? that is just a warning

**Comment by RM2beginner** [comment]
![RM2_hacks_cmd_line_executed](https://user-images.githubusercontent.com/78586755/113908322-fc995680-9808-11eb-9fae-5fdf8c32c0a8.JPG)
It appears that the patch.sh in my RM2 is updated but I still couldn't use it.

**Comment by sersorrel** [comment]
you need a capital `O` at the end (`-O-` not `-o-`), try copy-pasting the command

**Comment by RM2beginner** [comment]
@sersorrel Thanks for your advice and it started running...
![RM2_rmhacks_insufficient_free_space](https://user-images.githubusercontent.com/78586755/113963166-b6211780-985b-11eb-8d24-1911fd59a33e.JPG)

However, another issue came up saying that the space in /run/log/journal is less than 3MB and the operation is aborted finally. I tried to delete the system.journal to free up space and run the command again but the operation failed again as the system.journal file reappeared and took up space in /run/log/journal/.
![RM2_run_log_journal_f0a7e46ef23f41048cf75e37de64f092](https://user-images.githubusercontent.com/78586755/113963309-eff21e00-985b-11eb-8116-46bc1c5cd83e.JPG)

**Comment by Eeems** [comment]
Do you have other things installed? Like custom templates?

**Comment by RM2beginner** [comment]
@Eeems I installed the Funkey's jagged line fix and the calculator before my RM2 was auto-updated to version 2.6.2.75, but all these hacks were all gone after the update.

I tried to uninstall the remarkable-hacks using the command lines below but things are getting worst and now it comes to a point that the system returns a "bad address" message, and my RM2 is now frozen at the "reMarkable is starting" screen :(
I have already tried to hold the power button for 15 seconds and then another 2 seconds to reset the device but the RM2 still couldn't complete the starting process.

![RM2_wget_bad_address](https://user-images.githubusercontent.com/78586755/114117783-03fc5500-991a-11eb-8174-29ab275861e6.JPG)
![RM2_hacks_uninstall_cmd_line](https://user-images.githubusercontent.com/78586755/114117894-34dc8a00-991a-11eb-9a40-516aae8fee5c.JPG)
![RM2_hacks_uninstall_executed](https://user-images.githubusercontent.com/78586755/114117938-4de53b00-991a-11eb-9d04-6922703a4a83.JPG)

**I would highly appreciate it if anyone can help me to resume my RM2 back to normal.**

**Comment by Eeems** [comment]
Bad address is because you aren't connected to the internet.
You'll just want to ssh in over usb and restore the original xochitl file. By the looks of it you have done that. Is there anything in the logs that could tell you what is going wrong? `journalctl -eu xochitl`. You can also try running xochitl directly to see what the output says.

Likely you are just out of space and things are failing to run due to that. In which case you will need to remove some files. Like templates you added or something else. The output of `mount` and `du -hs /*` will help provide some information about where the extra files are.

**Comment by RM2beginner** [comment]
@Eeems It is strange that the system returns "bad address" as I am pretty sure that my computer is connected to the internet when executing the command line. Frankly speaking, I am just a beginner and know nothing about Linux commands, thanks for your help in diagnosing the issue, here below is the results after running the `journalctl -eu xochitl`, `mount`, `du -hs /*` and `xochitl `. 

![RM2_journalctl-eu_xochitl_results](https://user-images.githubusercontent.com/78586755/114254604-f1018780-99e2-11eb-9cd7-9616e5dc9710.JPG)
![RM2_mount_du-hs_xochitl_results](https://user-images.githubusercontent.com/78586755/114254614-037bc100-99e3-11eb-82db-301dc896094a.JPG)

To the best of my understanding of the results, it appears that a share library "libcrypt.so.1" is missing in the /usr/bin/xochitl directory and the system keeps on attempting to load the missing library endlessly and couldn't start the main application, and as a result the RM2 is always on the "reMarkable is starting" stage.

I have no idea why the share library "libcrypt.so.1" is missing and I would be pleased if anyone could send a copy to me for fixing the issue.

**Comment by Eeems** [comment]
The command isn't running on your computer. It's running on the reMarkable. Which isn't connected to the internet as the software that does that isn't running.
What you could do is grab the libraries from the system update image and copy them to the device. I think it's supposed to be placed somewhere in `/lib`

@ddvk where is the information on how to open an update file again?

**Comment by ddvk** [comment]
so you updated, but didnt have enough free space to install the hack

then you overwrote xochitl with an older version (2145), which doesnt work

i suggest just booting the old partition, uldating to 2672 again and then applying the patch

**Comment by RM2beginner** [comment]
@ddvk Do you mean that there are two partitions in the RM2, one is new and the other is an old one? How can I get access to the old partition and reboot from it? Please advise.
In case that the system keeps on returning bad address message and the RM2 failed to connect to the internet for some reasons, can I get the xochitl version 2672 manually? Where can I get it? Your help is greatly appreciated.

**Comment by dstango** [comment]
Did you checkout the /home/rmhacks directory? It contains the various backup version, and maybe you can delete some old ones.

**Comment by RM2beginner** [comment]
> Did you checkout the /home/rmhacks directory? It contains the various backup version, and maybe you can delete some old ones.

@dstango  Yes, I did. There is only one file called xochitl.25145_rm2 in the /home/rmhacks directory

**Comment by ddvk** [comment]
so, get: https://github.com/ddvk/remarkable-update/blob/main/switch.sh
copy it to your rm> `scp switch.sh root@10.11.99.1:~`  
make it executable> `chmod +x switch.sh`  
run it: `./switch.sh`
reboot: `reboot`
