### ISSUE TITLE
Toggle for PDF links on/off

### ISSUE THREAD

**Issue by Tridens92** [ddvk/remarkable-hacks#253]
Summary: Please add a toggle to turn PDF links on/off

Explanation: I'm thrilled reMarkable finally added support for internal links in PDFs in update 2.6.  However, now there are certain documents I'd love to turn them off for, simply because they get hit accidentally too often.  For instance, I use an organizer / planner that has graphic "tabs", like file folders, along both edges.  They work as links to navigate the PDF (by month, meeting notes section, etc.).  But I end up hitting them inadvertently all the time due to placement.

Any chance this is possible?  Thanks!

**Comment by ddvk** [comment]
this is doable

**Comment by ddvk** [comment]
added in the laat patch

**Comment by Tridens92** [comment]
Fantastic!  Thanks so much, @ddvk !
