### ISSUE TITLE
Support for non-Remarkable pens no longer works with newest update

### ISSUE THREAD

**Issue by tdrunn** [ddvk/remarkable-hacks#254]
I use a Samsung S Pen and prior to this update the button on the side of my pen functioned pretty well as an eraser. Hold press would toggle the eraser, and a short press would switch between the two most recent pen-types. Would greatly appreciate the restoration of this feature or reference to another script that has the same function.

Thank you.

**Comment by ddvk** [comment]
did you reinstall the remarkable-stylus hack?

**Comment by Tridens92** [comment]
Giving feedback on this issue as it relates to the Lamy pen.  I'm having no issues with reMarkable OS 2.6.2.75 and the remarkable-stylus hack.

**Comment by tdrunn** [comment]
> 
> 
> did you reinstall the remarkable-stylus hack?

I never had to install that hack in the previous iteration...but I'm also unclear on how to install the remarkable-stylus hack. Do I need linux? Because that's not an available option for me.

**Comment by dstango** [comment]
Check out the github repository remarkable-stylus. You'll find a description of the appropriate automagic command there. No extra linux needed. 
It always had to be installed for the button to work. But it's a one-liner and easy to forget one had to do it once, as it only needs to be done with new stock firmware, but usually not with in-between updates of the patches.

**Comment by ddvk** [comment]
it has never worked without patching and the stylus plugin
