### ISSUE TITLE
Issue RM1 2.6.2.75: switching between sidebar buttons doesn't always work 

### ISSUE THREAD

**Issue by PkW4v3** [ddvk/remarkable-hacks#255]
1) When I try to switch from pen to eraser or other tool with the rm1 buttons, while the physical pen is near to the screen, the switch attempt doesn't work. 
2) Also if I try to press any icon form the sidebar, immediately after writing, the icon isn't selected. To be able to do it, I have to wait, maybe one second or less.
3) still tied to this thing, I noticed if I keep my palm (or whole hand) attached to the screen, the upper buttons of sidebar, doesn't work.

these last two problems are also present in the stock version. Could you fix them?

ps. another thing I noticed (which is insignificant), is the lack of the bottom edge of the stroke list when using the mechanical pencil.

Thanks in advance!

**Comment by StLa1** [comment]
Just noticed this, very annyoing. You really need to lift the pen far, wait for 1 second, then press. Really kills the workflow.

**Comment by ddvk** [comment]
sorry, i forgot again to remove the button rejection

**Comment by ddvk** [comment]
this should work now on the rm1. 2 and 3 can't be fixed, if something is contact with the screen, then it counts as multiple touch events
