### ISSUE TITLE
DDVK update not working

### ISSUE THREAD

**Issue by laszlokenez** [ddvk/remarkable-hacks#259]
Hello All, 

I'm trying to upgrade my rM2, using Windows. 

My first ddvk automagic patch was 2.5.0.27 (17.2.07), it worked perfectly.

Now I would like to upgrade to ddvk 2.6.2.75 (patch_20.2.02), but Automagic keeps downloading the existing rM2 Version 2.5.0.27 - patch_17.2.07. The script runs from beginning to end, but rM version remains 2.5.0.27.

I couldn't get this line working at all: sh -c "$(wget https://raw.githubusercontent.com/ddvk/remarkable-hacks/master/patch.sh -O-)" _ patch_xxx

Thank you in advance!
Laszlo

**Comment by Eeems** [comment]
Does it give you an error? It should run the patched version, wait for you to quit with ctrl-c and then prompt you to save it or not.

That said, have you upgraded your system to 2.6?

**Comment by pstemper** [comment]
The DDVK patches do not upgrade your RM to a different version.  It just patches whatever version is currently installed on your RM.  You need to let your RM upgrade "naturally" through the RM interface.  Once that is done, then you can reapply the DDVK patches to the new RM version..

**Comment by laszlokenez** [comment]
Thank, pstemper, this I completely misunderstood. Thank you!

So, if I let RM upgrade, and ddvk features will (temporarily) be lost, will I lose my bookmarks?

**Comment by Eeems** [comment]
I believe bookmarks are preserved so you will get them back when you reinstall the hacks.

**Comment by laszlokenez** [comment]
Thank you both! I let RM upgrade, applied DDVK new patch, bookmarks preserved. 
PERFECT!

**Comment by Eeems** [comment]
So safe to close this issue?
