### ISSUE TITLE
Bookmark location for lefties

### ISSUE THREAD

**Issue by Tridens92** [ddvk/remarkable-hacks#26]
As a lefty, when I am writing toward the top of the page, I constantly find that the edge of my hand is toggling bookmarks off and on, and often, opening the edit bookmark function.  The latter obviously interrupts my writing, as I need to close the edit bookmark menu before continuing.  And I end up removing and adding bookmarks by accident.

Without the hack installed, I have a similar problem with the close document button, which rM put in the same place.

Is there any way to relocate the bookmark location for lefties?  Perhaps just to the left of the menu toggle in the upper right corner?  Or maybe relocating for everyone, if there are righties who are having a similar issue?

Thanks so much for a great hack!

**Comment by ddvk** [comment]
you can disable the bookmarks from the "Share menu"

**Comment by ddvk** [comment]
hm, at first it was in the lower right corner. some wanted it in the upper right corner ( which is the most intuitive place given koreader and kindle have like that)

i’m sure there is no postion that would be ok for everyone.

i could just disable the bookmarks in zen mode

**Comment by slowan** [comment]
I agree it is most intuitive at upper corner opposite to toolbar.
It sounds as good compromise to disable it in the zen mode. It is mostly for editing anyway.

**Comment by Tridens92** [comment]
Yes, upper right does make sense given kindle etc. have it there, but given that those are read-only devices, your hand doesn't tend to rest there.  The problem presents itself when writing.
