### ISSUE TITLE
Writing near the toolbar-icon

### ISSUE THREAD

**Issue by q-ki** [ddvk/remarkable-hacks#262]
If I turn off the toolbar and start writing near the toolbar-icon nothing happens. A little bit further out  to the right I can write.
When I start with a blank screen and do the same thing but first draw a line from right into the corner it works... it also works after I've done this the other way around and in every place of the corner.
This happens in both orientation-modes (landscape and portrait). 

I cannot say if this happens also without the ddvk-patch.

Cheers...
qki

**Comment by dstango** [comment]
also with the stock firmware it's hard to draw close to the toolbar-icon. The hacks make the icon a little smaller, if I'm not wrong -- I don't know if the area of "insensitivity" is adjusted accordingly.

Workaround: If you go to zen mode you can easily draw in the corners.

**Comment by ddvk** [comment]
it is how it works. the button reacts to pen events, its area is larger than the visible icon.  you can start outside and draw on the transparent part. 
in reading mode there is no icon at all, 2.6 seems much better with palm rejection, but still

**Comment by q-ki** [comment]
Ok... good to know.

Thanks to you both
