### ISSUE TITLE
No effect of jagged-line-improvment (2.6) with ddvk? 

### ISSUE THREAD

**Issue by q-ki** [ddvk/remarkable-hacks#263]
Hi there.

Could it be that the little improvements of the "jagged-line-issue" of the latest firmware 2.6 are gone after installing the ddvk-patch?... or am I hallucinating?

Thanks... 
qki

**Comment by ddvk** [comment]
you are hallucinating :>, the improvments can't be gone

**Comment by q-ki** [comment]
I tend to ;-)
