### ISSUE TITLE
Zen mode gestures hard to use

### ISSUE THREAD

**Issue by thrmfan** [ddvk/remarkable-hacks#264]
Last weekend installed ddvk and absolutely love it on my rm2. Only gripe is about the gestures in Zen mode, that it is hard to find the active area for toggling pen/eraser. I'm wondering if it can override the toggling side bar gesture (swipe down in the middle) for this functionality. Just in Zen mode, that is.

**Comment by oren** [comment]
I can't even make it work. where exactly do I need to swipe? i tried so many times...

**Comment by ddvk** [comment]
the swipe speed plays a role

**Comment by thrmfan** [comment]
I can barely make it work, maybe 1 in 20 times. That's why I recommend that in Zen mode, we can swipe down in the middle screen to toggle pen/eraser. To me this gesture of swiping down in the middle is much easier to handle, and its original functionality for toggling side menu bar is against the intention of Zen mode anyway. We can always tab to icon (upper right corner) to expand the side menu bar if needed.

**Comment by oren** [comment]
i would not even use swipe. it would be faster to be able to toggle between pen/eraser but also pen/undo with a tap instead of a swipe. we can have one spot for pen/erasure and another for pen/undo. 

Can we send pull requests to this project?

**Comment by thrmfan** [comment]
I see the developer checked the post hours ago. So he's fully aware our suggestions. No idea any other way.

**Comment by sersorrel** [comment]
i would be super annoyed if the swipe-down toggle-sidebar gesture changed, fwiw. i use zen mode everywhere to see the current pen/size/colour without having the entire sidebar open.

the toggle-eraser gesture is very easy for me; imagine the sidebar is open, then swipe quickly upwards, starting around where the "move" button is, ending somewhere close to the top of the screen. (i am in right-handed mode, and the eraser gesture is in the top-left, unlike what the picture in the readme says – i don't know if this changed in an update, i'm using an rm1 on fw 2.5.0.27 with patch 17.1.10-0-gf3b5e6b.)

**Comment by oren** [comment]
for me it's working when i start swiping near the stroke icon. but it only works 1 out of 10 attempts. maybe because it's such a narrow area i have to follow. this is the reason I can't use it. 

Here is my perfect workflow in Zen Mode:
1. tap somewhere to 'undo'.
2. tap somewhere to 'erase selection'. tap somewhere to switch to pen. 
3. tap somewhere to 'selection tool'. tap somewhere to switch to pen.

Anyone knows how to program the rm2 to do that?

**Comment by tzcone** [comment]
For me it works 8 out of 10. It all depends where you start the swipe, how long and fast it is. I use the eraser icon location as a visual reference. Either I flick my finger downwards to the eraser tool or upwards from it.

Your suggestion for a tap area is risky. I rotate the device constantly when I draw. I don't want to trigger an action by accident. Remember the X (close document) button? It was extremely frustrating.

**Comment by ddvk** [comment]
yes, most people will be annoyed, there is a high probability of activating them unintentionally. people keep their arm in a variety of positions, ask left handers.

i'll fix the menu open/close area so it does not get activated.

**Comment by thrmfan** [comment]
Many thanks for the tips. With all your guidance, my success rate increases dramatically, close to 80%. I found that if I only swipe upward, there is a great chance to make it work, while much less chance to swipe down, always triggering the collapse of side menu bar as @ddvk realized and is trying to fix.

Other than that the whole package is excellent and no complaint.

**Comment by ddvk** [comment]
here is a video of gesture activation: https://imgur.com/gallery/QgnuTgN

**Comment by thrmfan** [comment]
Thanks a lot! Now I'm getting more successful on this gesture. I would recommend to put this video link to your code description page. Time to close this topic.
