### ISSUE TITLE
Page overview shortcut by swiping up in the bottom right corner

### ISSUE THREAD

**Issue by Arut-A** [ddvk/remarkable-hacks#267]
Would be amazing to have a shortcut in zen mode to quickly check the page overview (to easily find needed pages). The bottom right corner could be used for swipe actions

**Comment by ddvk** [comment]
ok, i'll add it

**Comment by ddvk** [comment]
well, bottom left, up

**Comment by Arut-A** [comment]
wow, thx so much.

**Comment by F5JSD** [comment]
Thanks ddvk for this useful new feature, bottom left indeed (comment on release note still says bottom right ;-)
