### ISSUE TITLE
Issue with the cheat sheet

### ISSUE THREAD

**Issue by gerithebiker** [ddvk/remarkable-hacks#269]
Hi, 
I think the cheat-sheet displays the "toggle eraser" on the wrong side. I created a pdf that shows it on the left side, also added the "exit document" swipe (which is original rM). Pls use the file if you think it is correct.
Cheers,
G
[DDVK_CheatSheet.pdf](https://github.com/ddvk/remarkable-hacks/files/6274870/DDVK_CheatSheet.pdf)

**Comment by gerithebiker** [comment]
![DDVK_CheatSheet - page 1](https://user-images.githubusercontent.com/32972403/113969192-8691f100-9802-11eb-9bf0-8d72d2209997.png)


Here it is in png...

**Comment by ddvk** [comment]
if you use lefthanded mode, then those are reversed

**Comment by ddvk** [comment]
ok I updated it
