### ISSUE TITLE
Remember eraser type for documents

### ISSUE THREAD

**Issue by siraben** [ddvk/remarkable-hacks#27]
When I switch documents, the eraser type (e.g. selection erase) is reverted to the default eraser. Having the eraser type persisted would save having to set it manually each time.

**Comment by siraben** [comment]
On closer inspection, if the eraser is selected before switching, it is preserved upon switching back. However if the pen is selected, the type is not preserved.

**Comment by ddvk** [comment]
the eraser gets saved, but does not get restored. i’m trying some work arounds

**Comment by StLa1** [comment]
Any news about this issue ?

**Comment by ddvk** [comment]
nope,  hoping they'll fix it in the next patch

**Comment by ddvk** [comment]
it got finally fixed in 2.4
