### ISSUE TITLE
[bold feature request] could there be a way for user calibation of the touchscreen?

### ISSUE THREAD

**Issue by thagotaberry** [ddvk/remarkable-hacks#270]
Hi, thanks for the awesome work in the update!
I have a bold feature request: user calibration of the touchscreen: is there a table or something that could be modified, to calibrate the mapping of actual touchscreen xy coordinates to captured and used coordinates to get rid of some mid-screen and edge errors?
If there is a modifiable table I could imagine somithing like displaying a bunch of lines and the user has to draw along them with a ruler... Could something like this be achivable?

**Comment by ddvk** [comment]
this is really low level, but the hacks are not needed

it could be achieved by using a custom kernel with a modification of the input driver + a separate calibration ui in order to populate an offset table.

**Comment by ddvk** [comment]
closing this as out of scope, too difficult, other ways to achieve it

**Comment by thagotaberry** [comment]
got it. Thanks!
