### ISSUE TITLE
[feature request] presentation pointer pen

### ISSUE THREAD

**Issue by mehalter** [ddvk/remarkable-hacks#273]
I have been really enjoying the remarkable-hacks for my remarkable coupled with streaming the remarkable to my computer. It has been a great presentation tool for PDFs and the ability to draw on them live. I would like to have a pen option that's just a pointer. So a little dot as I move the pen on the screen without drawing a line so that I can easily point out things on slides. Would this be a possible addition?

**Comment by dstango** [comment]
possible workaround right now: maybe the selection tool can be something you'd like to check out. It's not exactly what you're asking for, but might be useful

**Comment by ddvk** [comment]
this is possible, but no hacks are needed. it depends on the presentation software (liveview, restream, rmview etc). 
a vnc server had such a feature to render the pen as a pointer.

**Comment by mehalter** [comment]
Ah awesome, thank you so much. I didn't realize rmview had a feature as such. I'm going to close this now
