### ISSUE TITLE
Remove Notebook cover forced to first page for version >=2.5

### ISSUE THREAD

**Issue by giorgio-arena** [ddvk/remarkable-hacks#277]
Hi and thank you so much for this awesome hack you're providing for the community!

With previous software versions you could only have the last visited page set as the notebook's cover, so the hack's feature to always set it to First Page made sense, but with the software update 2.5 we got the possibility of choosing whether to put the notebook's first page or last page visited as notebook's cover, which made this hack's functionality more of a malus rather than a bonus. Is there any plan of removing this?

Thanks again :)

**Comment by ddvk** [comment]
there is an option to disable it: Use Cover from Page iirc
