### ISSUE TITLE
swipe up toggle page overview 

### ISSUE THREAD

**Issue by q-ki** [ddvk/remarkable-hacks#278]
Hi there. 

Just updated to the newest patch version (rm2 / patch_20.2.03).

"hide recent files menu on touch" ... this works.

"lower right corner, swipe up to toggle page overview" ... this doesn´t work... at least for me.
All other swipes are working for me. 

Best regards ... 
qki

**Comment by q-ki** [comment]
ahhh ...it´s lower left corner ;-) 

right corner would be better

**Comment by ddvk** [comment]
fixed it in the readme
