### ISSUE TITLE
pen tips

### ISSUE THREAD

**Issue by s-engel** [ddvk/remarkable-hacks#280]
Some pens, especially the calligraphy pen, do not draw cleanly with thicker tips (frayed edges). The same pens draw cleanly in the original rM OS.

**Comment by ddvk** [comment]
i've only enabled those. the way they are rendered is a limitation of the underlying implementation.
rendering of 1 to 3 should be excatly the same as that of the original

**Comment by ddvk** [comment]
can't do anything
