### ISSUE TITLE
"Stuck" tutorial dots in upper left corner of tool(s)

### ISSUE THREAD

**Issue by Tridens92** [ddvk/remarkable-hacks#283]
Hello, I'm running the most recent version of the hack on top of rM 2.6.2.75.  Presently there's a dot in the upper left corner of my pen icon and the eraser icon.  They seem to be permanently there now.  What do they signify?  Someone on fb suggested that they indicate the tools that can be toggled back and forth.  However, if that's the case, something's not working correctly, as they are always on for the pen tool and eraser.  For instance, if I switch to the selection tool, a dot never appears on the selection tool.  Thanks in advance for any help.

**Comment by Tridens92** [comment]
I just figured it out with some more troubleshooting! They are related to the reMarkable tutorial. There was a dot next to each tool that would disappear after you selected that tool and dismissed that part of the tutorial. For some reason (either related to the interaction with remarkable-hacks or just a bug in the rM OS), they wouldn't clear for those two tools, but also wouldn't trigger that part of the tutorial. So there was no indication of their purpose, and no way for the tutorial to complete.  I uninstalled the hack, and on restart of xochitl there was a dot next to each tool! I successively pressed each tool, completed the tutorial, and then reinstalled the remarkable-hacks. The dots are gone 🙂  Is this a bug in remarkable-hacks or just with the rM OS?

**Comment by Tridens92** [comment]
Someone in fb user group stated that remarkable-hacks removes tutorial files.  If true, my guess is that the hack was installed while the sub-tutorials (signified by the dots) weren't yet completed, and therefore they got "stuck" in the "on" position.

**Comment by ddvk** [comment]
> Someone in fb user group stated that remarkable-hacks removes tutorial files. If true, my guess is that the hack was installed while the sub-tutorials (signified by the dots) weren't yet completed, and therefore they got "stuck" in the "on" position.

yes, this correct, kind of a bug because the tutorial was removed (no longer needed but ), but in some places ther were leftovers and you see the dots if the tutorial was not completed. there are a couple of lines in /etc/xochitl.conf that can be set to true.

**Comment by ddvk** [comment]
should have been fixed in the last patch
