### ISSUE TITLE
Firmware 2.7.30

### ISSUE THREAD

**Issue by DirkStegemeyer** [ddvk/remarkable-hacks#287]
Trying the Beta (2.7.30) - re install the hack is blocked - I assume on purpose - should we give it a try to install "as is" or do you need to have a deeper look into it first?
Thanks a LOT for all your work!!!

**Comment by Eeems** [comment]
According to the EULA for the beta you aren't allowed to install third party software while being part of it.

**Comment by DirkStegemeyer** [comment]
Fair point 👍

**Comment by dstango** [comment]
So what's new and noteworthy to expect in 2.7.30? ;-)

**Comment by ddvk** [comment]
the patches are tied to the version, and have to be ported. given that this is beta and prone to frequent change I would rather wait for the offical stable version.

**Comment by jensuj** [comment]
It also looks like un-enrolling leaves the device with the beta firmware, so people shuld thnk about that before enrolling. I'm stuck now, without the hacks, which I should have forseen.

**Comment by DirkStegemeyer** [comment]
> the patches are tied to the version, and have to be ported. given that this is beta and prone to frequent change I would rather wait for the offical stable version.

Thanks! Will wait patiently 😊👍

**Comment by DirkStegemeyer** [comment]
> It also looks like un-enrolling leaves the device with the beta firmware, so people shuld thnk about that before enrolling. I'm stuck now, without the hacks, which I should have forseen.

Yes - good point, similar here. The hack is geat and you notice how useful it is when you lost it...

**Comment by ddvk** [comment]
> It also looks like un-enrolling leaves the device with the beta firmware, so people shuld thnk about that before enrolling. I'm stuck now, without the hacks, which I should have forseen.

there is a way to revert to the older version of the software

**Comment by jensuj** [comment]
Following the "everything messd up" instructions, right? I was just reading those before.

**Comment by ddvk** [comment]
> Following the "everything messd up" instructions, right? I was just reading those before.

no, i meant, booting the previous version like that:

```
fw_setenv "bootcount" "0"

OLDPART=$(fw_printenv -n active_partition)
if [ $OLDPART  ==  "2" ]; then
    NEWPART="3"
else
    NEWPART="2"
fi
echo "new: ${NEWPART}"
echo "fallback: ${OLDPART}"

fw_setenv "fallback_partition" "${OLDPART}"
fw_setenv "active_partition" "${NEWPART}"
reboot
```

**Comment by jensuj** [comment]
That's what I ended up doing, using the switch script from the Update repository.
So how many old partitions are kept?

**Comment by Eeems** [comment]
There are only two root partitions. The active one, and the previous version.

**Comment by ddvk** [comment]
> There are only two root partitions. The active one, and the previous version.

Always two there are, an active and a fallback

**Comment by jaredgoodman03** [comment]
Couldn't the hacks be developed for 2.7 by enrolling in the beta, upgrading, and un-enrolling? This would be a legal way to develop and use it for 2.7, right?

**Comment by pstemper** [comment]
That MAY be a legal loop hole, but I believe ddvk said it best when they said "the patches are tied to the version, and have to be ported. given that this is beta and prone to frequent change I would rather wait for the official stable version."
Otherwise ddvk could be releasing "beta" patches every week, day, or who knows, maybe even more often.
I think it is reasonable to wait until the firmware is in a RELEASE state before ddvk goes to the work of porting the changes, legal loop hole or not.

**Comment by sersorrel** [comment]
fwiw, there is no legal problem as far as i can see: the eula i saw only says "We recommend that users do not install third-party software on the devices used in the Program as there could be unforseen consequences.", which is a long way from forbidding it

but nevertheless there's not much point putting in the work to port the hacks to short-lived beta builds that few people are using.

**Comment by DirkStegemeyer** [comment]
Closing this thread here, would be great if you could updated to the latest official version once it is there and you have a chance to get this going again (currently I am on 2.7.0.51 - cannot see if it is still beta or final) - Thanks!
