### ISSUE TITLE
Ability to draw straight lines

### ISSUE THREAD

**Issue by martin-braun** [ddvk/remarkable-hacks#289]
Great project, deserves a thump up. I'm not sure it's planned on the end of rm2 devs, but I miss a way to draw straight lines. I know I can carry a ruler around, but it would be nicer if there was a software solution. Would make things easier.

**Comment by Eeems** [comment]
Duplicate of #202

**Comment by martin-braun** [comment]
@Eeems Yes it is, thank you.
