### ISSUE TITLE
The temporary page indicator is missing while toolbar hidden

### ISSUE THREAD

**Issue by slowan** [ddvk/remarkable-hacks#29]
The temporary page indicator is shown for 5 seconds after page changed in original Remarkable software (as in a picture below).
It's completely disabled with remarkable-hacks. 
I don't mind having it disabled while toolbar enabled (there is page indicator "x of y"). However it would be really useful while the toolbar is hidden.

Could you please put it back while toolbar is hidden? If it's not possible to differentiate the state it would be better to have it there as in original Remarkable software.

![image](https://user-images.githubusercontent.com/60142747/83922540-c15d6f80-a780-11ea-9b98-b11fb84a6eec.png)

**Comment by dstango** [comment]
I found the default page indicator annoying since it appeared in a recent update. Thus I'd vote for making it somehow optional ...

**Comment by ddvk** [comment]
i ll make it a toggle
