### ISSUE TITLE
Page swiping too sensitive

### ISSUE THREAD

**Issue by martin-braun** [ddvk/remarkable-hacks#290]
I installed remarkable-hacks recently and love it so far, but I noticed that I started to swipe my pages to the right, accidentally. On close inspection I notice that I am able to swipe the page one or multiple pages to the right when I attempt to place my hand on the screen into the resting position. This never happened to me on the stock version. 

Here are two videos showing the issue:

- https://photos.app.goo.gl/7VLo8MWv1JJuCuY56
- https://photos.app.goo.gl/N8LjTPf5dJs848or5

I cannot produce it every time I attempt it, but it happens quite often. Maybe the swiping sensitivity was improved in stock but this hack still uses an old method?

**Comment by sersorrel** [comment]
i think the "M" in the top-left means that you are in reading mode, so a single tap will change page – if you long-press the "M" that should exit reading mode and stop the accidental page-changes

**Comment by martin-braun** [comment]
@sersorrel Oh yes I am and this shows that I was unaware what reading mode features altogether. 

Thank you!
