### ISSUE TITLE
feature suggestion: modes remembered by the document types

### ISSUE THREAD

**Issue by mrwth** [ddvk/remarkable-hacks#291]
In the current hacks, if I change the mode (normal/zen/reading), it gets changed in every document. It would be nice if each of the 3 document types (pdf, epub, notebook) remembered its mode, and mode switching was done only for the current type. I'm often switching between pdfs (for reading) and notebooks (for notes & calculations), and keeping pdfs in the reading mode and notebooks in the zen mode would be very helpful.

This is similar to #104, but maybe easier to implement (and for me, actually, more useful).

**Comment by ddvk** [comment]
i'll implement #104 i it is better and easier

**Comment by mrwth** [comment]
thanks - that will be really great !
