### ISSUE TITLE
Landscape and Split screen side by side hack

### ISSUE THREAD

**Issue by akif5723** [ddvk/remarkable-hacks#294]
Hi everyone, I would know if any hack exist who can does split screen side by side in landscape mode. 
I know you don’t have a really landscape mode like boox note aire or Fujitsu quaderno, but that will be great to have that … 

thanks in advance

**Comment by martin-braun** [comment]
I cannot answer your question, but I'd like to point out that you are one swipe away for toggling the two most recent documents with this hack. Try two finger swipe down in the center, it's almost as fast as looking left or right.

**Comment by akif5723** [comment]
Hi Martin-braun, 

thank you for your reply and these information :)

**Comment by ddvk** [comment]
sorry, not possible
