### ISSUE TITLE
Update to version 2.7.0.51

### ISSUE THREAD

**Issue by CrazyEasy** [ddvk/remarkable-hacks#295]
Please update remarkable-hacks to version 2.7.0.51! Thanks!

Working Machine ID for installing the Update on rM2: `ddf83d910e834f9fa2fc2351b6f1ce80`

**Comment by ddvk** [comment]
it may be a couple of a days (holidays etc)

**Comment by martin-braun** [comment]
@ddvk Take the time you need. We appreciate your work. :)

**Comment by ddvk** [comment]
so there is a preliminary version

**Comment by Eeems** [comment]
> 
> 
> Great! Can we try it?

Yes, that's why he said it's available: https://github.com/ddvk/remarkable-hacks/blob/master/patch.sh#L95-L106

**Comment by CrazyEasy** [comment]
Great! Thank you @Eeems and especially @ddvk! Keep up the great work!

**Comment by DirkStegemeyer** [comment]
Great! Thanks a lot!

**Comment by ilbonte** [comment]
I'm having trouble installing this version:
when trying to install it with the automagic script it installs the version 2.6.2.75
This is the output:

```
Connecting to raw.githubusercontent.com (185.199.108.133:443)
wget: note: TLS certificate validation not implemented
writing to stdout
-                    100% |********************************|  8244  0:00:00 ETA
written to stdout
Disk space seems to be enough.
rM2 Version 2.6.2.75 - patch_20.2.03
Connecting to github.com (140.82.121.3:443)
wget: note: TLS certificate validation not implemented
Connecting to raw.githubusercontent.com (185.199.110.133:443)
saving to '/home/rmhacks/patch_20.2.03'
patch_20.2.03        100% |********************************| 62820  0:00:00 ETA
'/home/rmhacks/patch_20.2.03' saved
Failed to stop rm2fb.service: Unit rm2fb.service not loaded.
killall: remarkable-shutdown: no process killed
killall: xochitl: no process killed
Cleaning up...

**********************************************
Trying to start the patched version...
You can play around, press CTRL-C when done!
**********************************************

Registering exit handlers
Reading waveforms from /usr/share/remarkable/320_R327_AFEC21_ED103TC2M1_VB3300-KCD_TC.wbf
Running INIT (135 phases)
32:23.228 qt.qpa.input             evdevtouch: Using device discovery
32:23.235 qt.qpa.input             evdevtouch: Adding device at /dev/input/event2
32:23.236 qt.qpa.input             evdevtouch: Using device /dev/input/event2
32:23.242 qt.qpa.input             evdevtouch: /dev/input/event2: Protocol type B  (multi), filtered=no
32:23.243 qt.qpa.input             evdevtouch: /dev/input/event2: min X: 0 max X: 1403
32:23.243 qt.qpa.input             evdevtouch: /dev/input/event2: min Y: 0 max Y: 1871
32:23.244 qt.qpa.input             evdevtouch: /dev/input/event2: min pressure: 0 max pressure: 0
32:23.244 qt.qpa.input             evdevtouch: /dev/input/event2: device name: cyttsp5_mt
^CShutting down...
Cleaning up...
If everything worked, do you want to make it permanent [N/y]? y
Making it permanent, DON'T DELETE /home/rmhacks/xochitl.26275_rm2 !!!
Starting the UI...
```


when trying to install it specifying the version I get 404:

```
reMarkable: ~/ sh -c "$(wget https://raw.githubusercontent.com/ddvk/remarkable-hacks/master/patch.sh -O-)" _ patch_21.2.04
Connecting to raw.githubusercontent.com (185.199.110.133:443)
wget: note: TLS certificate validation not implemented
writing to stdout
-                    100% |****************************************************************************|  8244  0:00:00 ETA
written to stdout
Disk space seems to be enough.
rM2 Version 2.6.2.75 - patch_21.2.04
Connecting to github.com (140.82.121.4:443)
wget: note: TLS certificate validation not implemented
wget: server returned error: HTTP/1.1 404 Not Found
```

**Comment by ddvk** [comment]
the patches are version coupled, and you can install only patches for the version you have. there are multiple patches per version, and that is how you can rollback and forth, but for the same version. 

you have to update to the official 2.7.0.51 first, the. you can apply the patch

**Comment by acompte** [comment]
I cannot install remarkable-hacks after the latest update. When I run automagic I get:

The backup /home/rmhacks/xochitl.27051_rm2 is not the original file (was it replaced/ deleted?), cowardly aborting...

and I cannot get it to work. Any tips? I need to get this working again, I can't live without bookmarks!

**Comment by Eeems** [comment]
> 
> 
> I cannot install remarkable-hacks after the latest update. When I run automagic I get:
> 
> The backup /home/rmhacks/xochitl.27051_rm2 is not the original file (was it replaced/ deleted?), cowardly aborting...
> 
> and I cannot get it to work. Any tips? I need to get this working again, I can't live without bookmarks!

See #224 among others if you search the issues list for your error message.

**Comment by acompte** [comment]
Thanks! I followed #47, using the latest patch and it worked nicely.
