### ISSUE TITLE
internal pdf links menu timer

### ISSUE THREAD

**Issue by faroit** [ddvk/remarkable-hacks#296]
Since 2.6 we have internal pdf links. Very often I use them to jump to the reference section of a paper. However, I need to be quick since the go back menu at the bottom disappears after a couple of seconds. 

It looks like we are looking for an 8000ms delay. I thought this would be a good fit for new hack...?

**Comment by dstango** [comment]
is there/could there be maybe a gesture to return to the original place? Something like swipe left in a certain area of the screen?

**Comment by faroit** [comment]
That could be nice, indeed. . But that would require that they keep track of all the links one would follow. I guess they don't keep more than one route

**Comment by ddvk** [comment]
there are already existing controls for jumping back and forward

**Comment by ddvk** [comment]
closing this
