### ISSUE TITLE
Version 2.7.0.51 gesture problem

### ISSUE THREAD

**Issue by Fabpir** [ddvk/remarkable-hacks#298]
Hi. I am not an expert at all but a happy user of my rM2 and of the hack indeed. I installed the last hack yesterday and I noticed that swipe down gesture from the top doesn’t close the document anymore and I have to touch X in the side menu (notebook). 
Also it seems to me that the left to right gesture in the top of the screen doesn’t “undo” any more. 
Thank you very much for the work. 
Fabrizio

**Comment by ddvk** [comment]
just try the newest patch, 3, it was fixed t here

**Comment by Fabpir** [comment]
Thank you! 🙏
