### ISSUE TITLE
Accessibility -> Font size always reverts to Normal after reboot

### ISSUE THREAD

**Issue by mhantsch** [ddvk/remarkable-hacks#299]
I have set Accessibility -> Font size to "Large". However after each restart, it now reverts to "Normal"; the setting does not stick.

**Comment by ddvk** [comment]
fixed in 04

**Comment by ddvk** [comment]
i assume this is ok

**Comment by mhantsch** [comment]
> i assume this is ok

Yes, I can confirm this works now with the latest version. Thanks.
