### ISSUE TITLE
Custom Installer

### ISSUE THREAD

**Issue by 1094** [ddvk/remarkable-hacks#30]
You have created a lot of wonderful tweaks, but I use the bookmarks, recent documents, and I enjoy the show first page in thumbnails. Can you separate the tweaks so they each have their own installer or make an installer that allows me to pick which tweaks are installed onto my device?

Something like:
```
Install bug fixes? [y/N]
Install Zen Mode? [y/N]
Install Bookmarks? [y/N]
Install $LAYER-SWITCHER? [y/N]
Move "Go to Page" to toolbar? [y/N]
Resize toolbar icons? [y/N]
Make thumbnails show first page? [y/N]
```

And so forth for all of the different tweaks.

**Comment by AaronDavidSchneider** [comment]
I don't think thats feasable. @ddvk uses binaries. In your example he would need to provide 128 different binaries for each possible combination (for each version).

**Comment by 1094** [comment]
Oh, if that's the case, it's not feasible at all.
