### ISSUE TITLE
need help w/install issue stdout full

### ISSUE THREAD

**Issue by katiebobus** [ddvk/remarkable-hacks#300]
![image](https://user-images.githubusercontent.com/41344773/118408762-8a5c3300-b64c-11eb-8ac3-d85f853132df.png)
I had koreader in there and removed it; not sure what else is taking up space. The rM2 only has 1.77 G disk space used. I do have some custom templates loaded - could that be the issue?

**Comment by katiebobus** [comment]
nm I see this is a duplicate issue to 275, will delete sleepscreens/templates.

**Comment by Eeems** [comment]
> The rM2 only has 1.77 G disk space used. I do have some custom templates loaded - could that be the issue?

It's complaining about the root partition not the data partition. So everything outside of `/home`. Xochitl reports disk usage in `/home`. More information can be found here: https://remarkablewiki.com/tech/filesystem

Have you installed any templates or fonts?

See #257
