### ISSUE TITLE
Sidebar navigation buttons sometimes fail with pen

### ISSUE THREAD

**Issue by presheaf** [ddvk/remarkable-hacks#302]
Occasionally, the sidebar buttons will fail to respond to input, and require toggling the sidebar to accept input. I think I have seen this with several buttons in more natural usecases, but a method which seems to consistently reproduce it for the forward/back buttons is the following:

1. Open a PDF which has a table of contents. 
2. Using the stylus, tap the ToC button and jump to a section. 
3. Tap the back-button which was just enabled, still using the stylus.
4. Tap the forward-button, still using the stylus.
5. Now, the back-button will not register inputs, whether via stylus or via fingers. Opening/closing the sidebar fixes this.

I verified this after reinstalling the hacks today. Apologies if this is a known issue, and thanks for the very useful features!

**Comment by ddvk** [comment]
i'll try to reproduce it

**Comment by ddvk** [comment]
I could reproduce it, and it should work now

**Comment by presheaf** [comment]
With the latest patch it works great. Thanks a lot again!
