### ISSUE TITLE
Reloading of suspend.png

### ISSUE THREAD

**Issue by schmidje** [ddvk/remarkable-hacks#303]
Hi,

Based on the changelog of patch_17.2.05, are the remarkable-hacks allowing the automatic updating of the supsend screen time by a simple replacement of the suspend.png file in the right folder (as it was possible prior to rM 2.5 update)? In fact, now we have to reboot the device to get our suspend.png replacement taken into account.

I am asking because I am experimenting the dynamic change of the suspend screen (e.g. a todo list taken from a notebook page).

Thanks!

**Comment by Eeems** [comment]
I believe this feature has already been added back by ddvk-hacks.

**Comment by Eeems** [comment]
The capability to have the instantaneous change of the suspend screen by the simple replacement of the suspend.png without reboot.

**Comment by schmidje** [comment]
Sweet, It works, thx. I wonder however how it works :) Probably the new image is written directly in memory.

I guess I can close this issue.
