### ISSUE TITLE
Marker Plus built-in eraser too rough when zooming in

### ISSUE THREAD

**Issue by martin-braun** [ddvk/remarkable-hacks#307]
The Marker Plus from reMarkable has a build-in eraser which was the key feature to get a reMarkable instead of any other tablet for me. It allows to erase stuff using the back of the pen. This is an official feature.

With pinch-to-zoom, we are finally able to zoom in, but zooming in will never change the size of pens and not the size of the eraser, too.

However, here I think it should be different for the build-in eraser of the Marker Plus pen. It's used to mimic the behavior of an classic eraser on the back of a pencil and I would welcome it would keep its area the same relative to the view port instead of relative to the document size. 

Sometimes I just want to remove a letter, but using the back of my pen will erase too much. Then, I have to select a fine eraser on the tool menu that defeats the purpose of the build-in eraser. If I could simply zoom in to erase a smaller area (that would be the same size relative to the actual pen size) I would be able to do finer erasing with the back of the pen.

Would it be possible to implement such feature with this hack?

**Comment by ddvk** [comment]
not feasable, too much effort

tilting the eraser decreases the area

**Comment by martin-braun** [comment]
@ddvk Ok alright, it was worth a shot. Tilting helps a little, at least.
