### ISSUE TITLE
Feature Request: Change default pens for PDF files

### ISSUE THREAD

**Issue by rayanelhelou** [ddvk/remarkable-hacks#308]
Hi there, thanks for the useful hacks!

Would it be possible to set up some sort of system which lets users decide the default pen(s) for new PDF files?

Every time I'm about to read a new document (e.g. journal paper) and want to take notes/highlight, I switch from Mechanical to Ballpoint Pen, as a consistent preference. Ideally, I'd like to have the default pens as Ballpoint and Highlighter, i.e. when I click the right button on RM1, it moves to a highlighter.

Thanks!

**Comment by martin-braun** [comment]
I'd love that feature, at least that it uses the ballpoint as default.

**Comment by ddvk** [comment]
the client can set the default pen while uploading a pdf, so if you used `rmapi` to upload files it would be easy.

**Comment by rayanelhelou** [comment]
> the client can set the default pen while uploading a pdf, so if you used `rmapi` to upload files it would be easy.

Hi @ddvk, I didn't understand your suggestion. Can you elaborate please, or point me to a resource that describes this feature?

**Comment by pstemper** [comment]
Rumor has it that the 2.8 beta release currently out has the concept of setting a default pen for a new notebook, so this may be a moot point soon.  Hopefully.

**Comment by rayanelhelou** [comment]
@pstemper you're right, and it's now implemented! I'll close this issue, thanks!

For everyone's reference, from Release 2.8 Notes:
> Notebooks will now remember the last writing tool you used every time you open a new one.
