### ISSUE TITLE
Update to version 2.7.1.53

### ISSUE THREAD

**Issue by CrazyEasy** [ddvk/remarkable-hacks#311]
Please update rM-Hacks to version 2.7.1.53, thanks! :)

**Comment by Eeems** [comment]
Duplicate of #304

**Comment by CrazyEasy** [comment]
@Eeems The difference between #304 and this issue is, that Version 2.7.1.53 is now officially released and in the other issue it was only available as a beta preview, which is why it hasn't been updated yet.

**Comment by katiebobus** [comment]
So I enrolled in beta and couldn't live without the hacks, so I unenrolled but was too late and both my partitions now have the beta version. Is there a way to tell if/when I get the official release of 2.7.1.53? Will the device alert me, or do I need to just keep trying to reinstall the hacks?

**Comment by Eeems** [comment]
> 
> 
> So I enrolled in beta and couldn't live without the hacks, so I unenrolled but was too late and both my partitions now have the beta version. Is there a way to tell if/when I get the official release of 2.7.1.53? Will the device alert me, or do I need to just keep trying to reinstall the hacks?

You can manually downgrade to an official version: https://github.com/ddvk/remarkable-update

**Comment by MatthewJamesCooper** [comment]
Yup, I just reinstalled this awesome hack only to accidentally click the update version at the bottom of the screen. Now I'm forced to use the .53 software and can't rehack. Anyway, looking forward to when this one is supported. Surely @ddvk you'll be offered a job at RM once they wake up and realise that what you're offering is essential functionality and not bloat!? Thanks for the good work.

**Comment by Eeems** [comment]
> Now I'm forced to use the .53 software and can't rehack.

You could always downgrade as per my previous comment.

**Comment by pstemper** [comment]
Which, I have had to do a few times.  I can't work without the DDVK hacks!  :)

**Comment by ddvk** [comment]
version 2.8 is rolling out

**Comment by pstemper** [comment]
ddvk, Looking forward to the new features of 2.8, and hopefully the hacks for it.  Thanks so much for all your hard work!

**Comment by MatthewJamesCooper** [comment]
@Eeems Thanks but I took a look and that's out of my skill set! >_<

**Comment by pstemper** [comment]
@MatthewJamesCooper You are probably selling yourself short...  If you applied the original patch, you can revert to the previous update.  Look at issue #304 for my post, starting with "No Problem!".  It outlines steps to revert to the previous partition (which held the OS before your most recent update.)  It really is not that hard (there is a script to do it also, but I find issuing the steps manually help understand what is going on.)
Check it out, and if you have any questions, let me know.  Then you don't have to suffer without the ddvk hacks!  ;)

**Comment by MatthewJamesCooper** [comment]
@pstemper Awesome, ok I'll take a look. Thanks for the encouragement. If I get stumped I'll give you a shout. Thanks.

**Comment by MatthewJamesCooper** [comment]
@pstemper Fantastic instructions and that's worked perfectly. Thanks for the help!

**Comment by pstemper** [comment]
@MatthewJamesCooper Wonderful!!  Don't forget, if you like the ddvk hacks and the support provided here, you can always donate to ddvk for all his hard work!  Just click on the SPONSER button at the top of the screen.

:)

**Comment by MatthewJamesCooper** [comment]
@pstemper Sponsored, thanks for highlighting, I only come to Github for this so Im not that used to how it works. 🤜💥🤛
Thanks @ddvk, your hack makes the RM2 soooooo much better.

**Comment by CrazyEasy** [comment]
> version 2.8 is rolling out

Alright I didn't know that! Then I'm excited waiting for the 2.8 update 😄

**Comment by ddvk** [comment]
so, I was wrong about 2.7.1.53 being a beta or at least it is official now, still as I dont find a pressing need to update, I would hold off for the 2.8 release

**Comment by CrazyEasy** [comment]
> so, I was wrong about 2.7.1.53 being a beta or at least it is official now, still as I dont find a pressing need to update, I would hold off for the 2.8 release

That totally makes sence! Thank you so much for your time and work!

**Comment by mhantsch** [comment]
What's changed in 2.7.1.53 (from previous release)? The only note I could find on the remarkable site is "Software release 2.7.1 contains an updated touch driver." Did this perhaps fix the spontaneous restarts that occurred with both 2.6 and 2.7 versions?

**Comment by ai212983** [comment]
> That totally makes sence! Thank you so much for your time and work!

Seriously? That would make sense if anyone would be able to downgrade/upgrade when he chooses, which is not the case. One updated to 2.7.1.53 now should wait til 2.8 will be pushed to his device, and it can be weeks. The only way to get rm-hacks working for him is to mangle with boot partitions as described in comments on #304. 

Skipping support for 2.7.1.53 may have its points, but imo it should be clearly communicated on the main page to prevent people from false assumptions when updating their device.

**Comment by sersorrel** [comment]
@ai212983 ...it is? 
![Screenshot_20210607-123301](https://user-images.githubusercontent.com/9433472/121009872-94291000-c78c-11eb-83d3-ee2b811c31a4.png)

**Comment by pstemper** [comment]
And, here: 
![image](https://user-images.githubusercontent.com/11776059/121010200-bace5300-c75a-11eb-8478-1b98b54caebd.png)

**Comment by ai212983** [comment]
@sersorrel Can't see anything about skipping support for 2.7.1.53. One can assume patch for 2.7.1.53 is in the works, but not out yet. There are 4 tickets already asking for 2.7.1.53 support.

**Comment by CrazyEasy** [comment]
2.7.1.53 is now available for RM2. Thanks @ddvk!
