### ISSUE TITLE
New RM2 Software Version Released - 2.7.1.53

### ISSUE THREAD

**Issue by hmgreen1953** [ddvk/remarkable-hacks#312]
Hi.  I am new to jacking my RM2 and had just finished applying 2.7.0.  There is now a newer release of the software.  Any idea if the 2.7.0 version will still work if reapplied to the 2.7.1 release, or if there is an upcoming update to match the new version?

Thanks in advance!

**Comment by pstemper** [comment]
It will not.  Due to the nature of the hacks (binary patches), the hacks are SPECIFIC to the exact version.  That being said, 2.8.x.x. is rolling out now, so hopefully @ddvk will have an update soon.

**Comment by hmgreen1953** [comment]
I hadn't heard about 2.8.  Does anyone know what has been added to that release?  Also I have the separate hacks for the Lamy EMR stylus eraser, the time display, and a separate pdf reader app.  Are those hacks tied to the release also?  I don't want to "brick" the RM2 but those hacks have been useful to me.  If I need to wait until the main DDVK hack is adapted for 2.8 I will wait.  Thanks in advance!

**Comment by pstemper** [comment]
From what I have heard about 2.8 ("Quoted from the release page): Added the ability to merge layers within your documents, Notebooks will now remember the last writing tool, line color, and thickness you used every time you open a new one
As for the "other" hacks, I cannot answer that (I haven't looked into them in depth yet even though I also use all the ones you mentioned, I just wait until I know @ddvk supports a version before i update)   The other option is to roll back to the last "hack supported" version of 2.7.0.51 (so you can use the hacks), and then turn off auto-update and wait for @ddvk to release a new version of the hacks.
