### ISSUE TITLE
Installation unsuccessful on latest software update (2.8.0.98)

### ISSUE THREAD

**Issue by Shyma1** [ddvk/remarkable-hacks#318]
Tried earlier today. Thanks.

**Comment by martin-braun** [comment]
@Shyma1 Of course it is unsuccessful, because there is no patch listed for that version. I'm pretty sure @ddvk is working on it, unless this is a beta version, let's stay patient.

**Comment by pstemper** [comment]
Now that 2.8 is out of beta (according to reMarkable), I am sure @ddvk will work on it when he has time.

**Comment by ddvk** [comment]
try again

**Comment by mfelsenfeld** [comment]
Will you have a patch for RM1?

**Comment by Shyma1** [comment]
Thanks @ddvk! Works now. I disabled auto updates, gotten too used to your features to risk losing them unexpectedly :)
