### ISSUE TITLE
Previous document gesture not working in 2.8.0.98

### ISSUE THREAD

**Issue by martin-braun** [ddvk/remarkable-hacks#319]
Two finger swipe down to jump to the recent document seems to be broken in the latest patch 2.8.0.98.

**Comment by mmbcorley** [comment]
doesn't seem to work for me either

**Comment by ddvk** [comment]
indeed, i will fix it

**Comment by esa372** [comment]
Thanks, ddvk!

**Comment by martin-braun** [comment]
Thank you very much @ddvk, now it's working. I'm very thankful you're so active on this project. :)
