### ISSUE TITLE
Version 2.2

### ISSUE THREAD

**Issue by ZacharieALES** [ddvk/remarkable-hacks#32]
Hello,

Version 2.2 has just been installed on my remarkable. The hack does not yet seem supported with it. Can I do anything to make it work? (e.g., downgrade my remarkable version or something else)

**Comment by skatsaros** [comment]
Hello ddvk-- I love the tools you created! They made reMarkable incredible. 

I accidentally updated to 2.2 and lost your tools. The above thread is beyond my capability. Is there a forthcoming update that is compatible with 2.2, or is there a way to downgrade back to 2.1?

A million thanks to you from Denver, Colorado!

**Comment by ddvk** [comment]
here is somthing easier:
```
cp /usr/bin/xochitl xochitl.22048
mkdir -p other
mount -v | grep 'on / ' | cut -f1 -d ' '
# will show /dev/mmcblk1p2 or /dev/mmcblk1p3 use the opposite (e.g. if p3 use p2) below

mount /dev/mmcblk1p2 other
cp other/usr/bin/xochitl /usr/bin/xochitl
systemctl restart xochitl
```

**Comment by skatsaros** [comment]
ddvk.
It worked. You are amazing!
Do you have a a patreon account? Or paypal to support you? Thanks for the time you spend on this suite of useful tools--it's great!
With huge appreciation from Colorado!
Steve

**Comment by basmets** [comment]
Hi ddvk.

Thanks so much for creating the hack and for helping everyone with this.
Unfortunately I only discovered the hack now – I already updated to 2.2 and have thus never previously used the hack.

I know it must be super annoying to answer, but do you have any plans on updating to 2.2? :-)

Thanks!

**Comment by ddvk** [comment]
try again with the automagic, the official version has some bugs and was waiting for them to fix them, but anyway here's something

**Comment by basmets** [comment]
It worked! Thanks so much. Epic tweaks, very much appreciated :-)

**Comment by PkW4v3** [comment]
[2.2.0.48 - patch_01]
I've noticed that after pressed eraser button, pen button does not work.
For the rest it seems perfect!
Thanks for all you're doing ♡

**Comment by ddvk** [comment]
sorry about that, fixed in patch_02

**Comment by Tridens92** [comment]
Which version is installed right now using the automagic code on the home page of the hack?  I recently upgraded to rM OS 2.2, so reinstalled the hack.  My rM is reporting Version 2.2.0.48, with hack version patch05_1...

**Comment by ddvk** [comment]
well, depends on your version, the patches are version specific

**Comment by Tridens92** [comment]
OK, so the automagic code on home page, if I'm running rM OS 2.2.0.48 is automatically going to install the 22048 version of your hack?  And even though the above thread says that the eraser problem was fixed in patch_02, it's normal that mine is reporting patch05_1?  Sorry, I'm not at all Linux literate, so the only thing I know how to do is SSH in and use your automagic script.  Thanks!

**Comment by ddvk** [comment]
correct, if the eraser is working then it s fixed ;). ignore the version in setting (for problem reporting only)

**Comment by Tridens92** [comment]
Perfect!  Thanks so much for letting me know, and once again my thanks for this incredible hack!

**Comment by ddvk** [comment]
updated readme, patches ported to 22048

**Comment by cyh002** [comment]
> here is somthing easier:
> ```
> cp /usr/bin/xochitl xochitl.22048
> mkdir -p other
> mount -v | grep 'on / ' | cut -f1 -d ' '
> # will show /dev/mmcblk1p2 or /dev/mmcblk1p3 use the opposite (e.g. if p3 use p2) below
> 
> mount /dev/mmcblk1p2 other
> cp other/usr/bin/xochitl /usr/bin/xochitl
> systemctl restart xochitl
> ```

Hi. i did this to revert to an earlier version so i could use your hacks. How do i revert back to the latest version? 

Also, i would like to thank you for your contributions. :)
I really love what you have implemented and i wouldn't have love my tablet as much as i do, without your hacks.

**Comment by ddvk** [comment]
just apply the pach should probably work

or to revert (if you followed the instructions exactly)
‘’’
cp xochitl.22048 /usr/bin/xochitl
systemctl restart xochitl
‘’’
