### ISSUE TITLE
[patch_23.2.02] Regression: Long press does not cycle back to normal mode

### ISSUE THREAD

**Issue by rogiervandenberg** [ddvk/remarkable-hacks#322]
Long press on the "toggle menu" (uppermost) used to cycle between 'normal mode', Zen mode and Reading mode.

Since the last patch on my RM2, it goes from normal mode to Zen, and from Zen to Reading mode, but then back to Zen again. With Long presses it is **now not possible anymore** to leave Zen mode and/or Reading mode. ([The quickdoc says "Enter/Exit: (...) long press on the "toggle menu" (uppermost)"](https://github.com/ddvk/remarkable-hacks#zen-mode))

_Workaround: The only way out is to go to Reading mode, open the menu item in the bottom left en hit the M to go back to normal mode._

Furthermore, thank you so much for building this, especially the gestures/swipes for side menu, quickly jumping documents, changing pencils and undo are a huge time saver. 🙏

**Comment by ddvk** [comment]
yes, sorry about that. 

normal mode doesnt make sense in the rm2, as there are no physical buttons and it was requested to remove it in the rm2, i left it by sccdient but i can revert it

**Comment by mrwth** [comment]
I am actually really happy with this regression, since I'm switching between the zen and the reading modes all the time and don't need the normal mode (on rm2).

**Comment by rogiervandenberg** [comment]
Interesting.. Because of this 'issue' I have been basically forced into a new workflow (just use Zenmode all the time) and I really like it too now, just like @mrwth Why? Because when swiping to hide the toolbar, you always have info on what tool is being used and switching tools + eraser is very quick.

So yes, I like Zenmode as default too now and I never use 'normal mode' anymore. So maybe this is just a new 'feature' and not a 'bug'. I would not mind if it stays the way it is now. 😋

**Comment by dstango** [comment]
if you like zen as a new workflow you might like to check out the lamy pen: erasing is just a press on the little button away, as is toggling between the tools.

Anyhow: I would really like to be able to see the tool like in zen mode in the normal mode ... Then I would have instant confirmation if my tool toggling with the pen button worked (it's a little tricky timing-wise....), and could still use the rm1-buttons for page turning

**Comment by martin-braun** [comment]
To be honest, why do rm1 users need Zen mode anyways? Why not simply improving the normal mode to have the features of Zen mode? Is there really an issue on rm1 that people press buttons accidentally? 

Instead of having a third mode, I would just improve normal mode to indicate the current tool in the very top left corner and that's it. 

I also don't understand why the letter "M" stands for reading mode. If we just use have the top left tool inspector in normal mode, a [book icon](https://fontawesome.com/icons?d=gallery&p=2&q=book&m=free) would be great for the reading mode.

**Comment by rogiervandenberg** [comment]
I agree on “normal mode doesnt make sense in the rm2, as there are no physical buttons”
