### ISSUE TITLE
Installation Permission denied ‘/home/rmhacks’:

### ISSUE THREAD

**Issue by django23** [ddvk/remarkable-hacks#325]
When running:
sh -c "$(wget https://raw.githubusercontent.com/ddvk/remarkable-hacks/master/patch.sh -O-)"                                        ─╯

This is the output.
--2021-07-02 17:14:13--  https://raw.githubusercontent.com/ddvk/remarkable-hacks/master/patch.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8889 (8,7K) [text/plain]
Saving to: ‘STDOUT’

-                                 100%[=============================================================>]   8,68K  --.-KB/s    in 0,008s  

2021-07-02 17:14:13 (1,11 MB/s) - written to stdout [8889/8889]

mkdir: cannot create directory ‘/home/rmhacks’: Permission denied

**Comment by Eeems** [comment]
Are you running this on the reMarkable itself?

**Comment by LuYutum** [comment]
i'm getting this Error while installing the newest patch.

reMarkable: ~/ sh -c "$(wget https://raw.githubusercontent.com/ddvk/remarkable-hacks/master/patch.sh -O-)"
Connecting to raw.githubusercontent.com (185.199.109.133:443)
wget: note: TLS certificate validation not implemented
wget: short read, have only 0: Connection reset by peer
wget: error getting response: Connection reset by peer

**Comment by django23** [comment]
> Are you running this on the reMarkable itself?

I think this was yes. Appartently @LuYutum experience the same.

Kind regards,

**Comment by Eeems** [comment]
> > Are you running this on the reMarkable itself?
> 
> I think this was yes. Appartently @LuYutum experience the same.
> 
> Kind regards,

Based on the error message you received being a permission denied error, I would expect you were running the script on your computer instead of the reMarkable. On the reMarkable the root user has all permissions and thus wouldn't encounter this error.could you try running it again and confirm that you are on the device. A screenshot would be helpful.

**Comment by Eeems** [comment]
> i'm getting this Error while installing the newest patch.
> 
> reMarkable: ~/ sh -c "$(wget https://raw.githubusercontent.com/ddvk/remarkable-hacks/master/patch.sh -O-)"
> Connecting to raw.githubusercontent.com (185.199.109.133:443)
> wget: note: TLS certificate validation not implemented
> wget: short read, have only 0: Connection reset by peer
> wget: error getting response: Connection reset by peer

@LuYutum this is unrelated to the current issue. Please open a new issue.

**Comment by LuYutum** [comment]
> > i'm getting this Error while installing the newest patch.
> > reMarkable: ~/ sh -c "$(wget https://raw.githubusercontent.com/ddvk/remarkable-hacks/master/patch.sh -O-)"
> > Connecting to raw.githubusercontent.com (185.199.109.133:443)
> > wget: note: TLS certificate validation not implemented
> > wget: short read, have only 0: Connection reset by peer
> > wget: error getting response: Connection reset by peer
> 
> @LuYutum this is unrelated to the current issue. Please open a new issue.

sry, i'm gonna opening a new one

**Comment by django23** [comment]
It seems like a reboot was necessary. I find it very strange too.

Close this topic. Thanks
