### ISSUE TITLE
stuck in M mode with disabled swipe

### ISSUE THREAD

**Issue by joachimkock** [ddvk/remarkable-hacks#33]
First of all: thanks so much for your work. You are transforming the rM into what it ought to be!

Reporting from 2.1.1.3, patch 5_1-10:

In M mode, with menu toggled off, there is no minimised icon to restore the menu. The only way to toggle back the menu is with swipe down. If swipes are disabled, there is no way to get the menu back -- or at least I could not find any :-( (I have tried to hold the left and right buttons pressed for some time but it does not help. Restart restores the menu.)

I admit this might count as a user error, but I thought I should report it anyway.

**Comment by ddvk** [comment]
you can taggle by pressing both buttons left and right

**Comment by ddvk** [comment]
pressing simultaneously the left and right buttons should change the mode

**Comment by joachimkock** [comment]
Thanks -- I don't know why I didn't find that.

In conclusion, to get the menu back (in M mode with swipes disabled):
change to default mode using left-right-buttons-press; restore the default-mode menu using minimised icon; return to M mode in the usual way (in the notebook-submenu).

I withdraw the issue. Sorry for the noise.
