### ISSUE TITLE
Toggle bookmark gesture is not working on 2.8.0.98 patch_23.2.02

### ISSUE THREAD

**Issue by F5JSD** [ddvk/remarkable-hacks#336]
Hi,

on rM2 OS 2.8.0.98 patch_23.2.02, the toggle bookmark gesture (tap top right for right handed person) no longer works.

Thanks for your work and support.

best regards

Pascal

**Comment by pstemper** [comment]
It is working for me on my rM2..

**Comment by F5JSD** [comment]
Yes sorry fat fingers ;-) I updated my post.
interesting it is working for you. You still do a long press TOP RIGHT of the screen? nothing happens since I upgraded to 2.8

**Comment by F5JSD** [comment]
My mistake: I just realized "Bookmarks" was set to "Off" in Extra UI menu. I feel dumb.

**Comment by pstemper** [comment]
Don't worry about it, it happens to ALL of us!  :)  Just glad it is working for you now.
