### ISSUE TITLE
Screen sharing doesn't work with latest patch_24.2.02 on RM2

### ISSUE THREAD

**Issue by i-am-shodan** [ddvk/remarkable-hacks#344]
Running 2.9 with hacks for rm2 2.9.1.217 and patch_24.2.02.

When using screen sharing I can correctly see the screen, see hover (red dot) stylus updates but if I make a change to the notebook this does not appear on the remote screen.

If I run the original binary in /home/rmhacks/xochitl.291217_rm2 screen updates correctly appear.

**Comment by ddvk** [comment]
what red dot stylus updates?

**Comment by Ameb** [comment]
> what red dot stylus updates?

The pen position when hovering the screen with it.

**Comment by ddvk** [comment]
is that with the official desktop app, which version?

**Comment by i-am-shodan** [comment]
Official app 2.10.0

**Comment by ddvk** [comment]
> > what red dot stylus updates?
> 
> The pen position when hovering the screen with it.
I hadn't noticed that the feature in the official app now

**Comment by ddvk** [comment]
could anyone else confirm this, because I can't reproduce it

**Comment by Blerkselmans** [comment]
Just tested it and the Windows App upgraded on startup to 2.10.0 (172) (don't know what previous version was).
It works without an issue on my device

**Comment by i-am-shodan** [comment]
at least one other person is seeing it on Discord

**Comment by i-am-shodan** [comment]
Remarkable 2?

**Comment by Blerkselmans** [comment]
Yes, RM2

**Comment by ddvk** [comment]
are you using anything else, launcher etc

**Comment by Fabpir** [comment]
Yes. I do confirm this. Don’t touch the screen but just move the pen over it closer. 
Have a nice day all. 
Fabrizio

**Comment by i-am-shodan** [comment]
The red dot works fine, screen updates don't

**Comment by burgarth** [comment]
All working fine here, Lamy Stylus with button hack, rm-hack, Rm1, Mac client, seeing red dot

**Comment by i-am-shodan** [comment]
Yes remux - I've tested it without anything running.

Can reproduce running original xochitl (all screen updates appear) and the patched version straight from the console (no screen updates, only initial screen and red dot appear)

**Comment by ddvk** [comment]
> The red dot works fine, screen updates don't

just a patched xochitl, or you have other things installed, remux, rmkit,tolctec etc?

**Comment by i-am-shodan** [comment]
To be clear - this is nothing to do with the red dot. It's all about updates from styles on device.

**Comment by GuyNT** [comment]
Works perfectly on my with this patch and the offical app on windows 10

**Comment by i-am-shodan** [comment]
remux, r2fb and toltec are installed.

**Comment by ddvk** [comment]
can you remove r2fb? and test again, probably something with the hooks

**Comment by i-am-shodan** [comment]
If I run xochitl from the command line (without the LD_PRELOAD) is that the same?

**Comment by ddvk** [comment]
yes

**Comment by i-am-shodan** [comment]
well i've done that and it still don't work

**Comment by i-am-shodan** [comment]
I will test again now

systemctl stop remux
xochitl

**Comment by ddvk** [comment]
is the LD_PRELOAD set globally somewhre

**Comment by i-am-shodan** [comment]
echo $LD_PRELOAD is empty

**Comment by i-am-shodan** [comment]
hold on

Loading custom environment variables from /opt/etc/xochitl.env.d

let me nop that out

**Comment by i-am-shodan** [comment]
Disabling the LD_PRELOAD in /opt/etc/xochitl.env.d fixed the issue. Must be an issue in r2fb.

Do you want me to start an issue in your other repo?

**Comment by Etn40ff** [comment]
> could anyone else confirm this, because I can't reproduce it

I can reproduce

**Comment by ddvk** [comment]
> Disabling the LD_PRELOAD in /opt/etc/xochitl.env.d fixed the issue. Must be an issue in r2fb.
> 
> Do you want me to start an issue in your other repo?

yes, you should open the issue in the remarkable-framebuffer repo,
i just reproduced it after installing rm2fb

**Comment by ddvk** [comment]
the offical xochitl's screensharing also doesnt work with rm2fb
