### ISSUE TITLE
The "quick browse" scrollbar is shortened by the hacks (software 2.9)

### ISSUE THREAD

**Issue by mrwth** [ddvk/remarkable-hacks#345]
The quick browse scrollbar (swipe up from the bottom edge with one finger) is much shorter in the hacked version of the software.

**Comment by ddvk** [comment]
botched by mistake, fixed now

**Comment by Blerkselmans** [comment]
Wow, that is fast @ddvk ! I noticed the scrollbar issue as well today.
Only applying patch_24.2.03 should fix it?

Would like to add, although 2.9 is a major Rm release, life is so much easier using your hack. Such a relief after working hackless for some time.

**Comment by ddvk** [comment]
yes, 03 should fix it
