### ISSUE TITLE
Navigation arrows not working on 2.9

### ISSUE THREAD

**Issue by martin-braun** [ddvk/remarkable-hacks#347]
I remember that I could navigate back between pages (and even files?) with those directional arrows below the page info on the side bar. Those arrows are always greyed out, now.

I think they should provide proper navigation after swiping to previous or next page, switching the document, navigating using the new slider on on the bottom or using the traditional page navigator of the hack in the side bar (four little squares icon).

Other than that, great 2.9 hack. ❤️

**Comment by ddvk** [comment]
those work only for bookmarks, pdf links and directly dialing a page for now...
i can fix the slider, overview page and table of contents, but multi document hopping is a bit hard

**Comment by martin-braun** [comment]
@ddvk maybe my memory is false then, but yes, it would be nice to be able to navigate back between pages in the same document at least. It would be very useful, especially when using the bottom slider.

Thank you. 🙏🏻

**Comment by martin-braun** [comment]
@ddvk Seems like my memory is weak then, but I love the way you solved it, although not featuring everything, it's good to go. 

Thank you for the quick implementation. 🙏🏻
