### ISSUE TITLE
Request "Recent Notebooks" Gesture Available in My Files/Folder 

### ISSUE THREAD

**Issue by Bricewilliamsinc** [ddvk/remarkable-hacks#358]
Rm2 recent notebook is available regardless of the file structure.  Which is helpful while in a folder or "my files" to retrieve recent notebooks.  I prefer ddvk hack "recent notebook" list view; but many times i find my self opening a random notebook to gain access to recent list.  Is it possible to have your recent list available while in My Files or a Folder?  Thanks again for making my Rm2 a pleasure to use and less cumbersome using the manufacture's scheme (zen mode is fantastic!)

**Comment by martin-braun** [comment]
Just tap on "Menu" in the top left corner and you will see the recent file list from the hack in front of you.

**Comment by Bricewilliamsinc** [comment]
thank you for the reminder, I was looking to have the 2 finger gesture available to bring up recent list.  I guess I am getting spoiled with the speed in which ddvk has developed the hack with gestures.

**Comment by martin-braun** [comment]
You're welcome. Well, the 2 finger gesture from top is reserved to the official implementation. There are users who prefer to use the official recent list instead, so it's programmed to support both actions. If you want the ddvk's implementation, you should tap on "R" or "Menu", depending where you are, and you will be used to it pretty quick.

Btw, there are ongoing issues (#346, #310) to find a better solution to this redundant behavior when the hack is installed. I'd suggest to participate there and close this issue to keep things simple. :)
