### ISSUE TITLE
Feature request: remember last orientation in new notebook

### ISSUE THREAD

**Issue by joachimkock** [ddvk/remarkable-hacks#36]
It is wonderful that last used pen is remembered for new notebooks. Thanks so much for that. I hope I do not appear ungrateful by suggesting that also the orientation (portrait/landscape) could be remembered for new notebooks.

(I feel a bit ashamed by entering four tickets in a row like this, as if I were unsatisfied. On the contrary, I am absolutely marvelled by the fact that the rM is now moving forward, thanks to your work! (while the official rM development team seems to be stuck. I have turned off auto-update, because your patches are more important than official increments.)

**Comment by ddvk** [comment]
fixed
