### ISSUE TITLE
cowardly aborting... 

### ISSUE THREAD

**Issue by Ilyo** [ddvk/remarkable-hacks#361]
I've been running DDVK successfully across multiple previous versions of rM updates, but got myself into a bit of a pickle when I'd not realised auto-update had reset after the last patch, and DDVK wasn't yet available for my RM1..

Anyway, I'd attempted (unsuccessfully) to revert to a previous version, and in the process had messed around with scripts and files I should rightly have left alone..

Anyway, suffice to say in the end I ended up doing a factory reset, and as a vanilla rm1 it's running fine, but on attempting to re-apply the DDVK patch I'm getting the 'Cowardly Aborting' status as below:

`ｒｅＭａｒｋａｂｌｅ
╺━┓┏━╸┏━┓┏━┓   ┏━╸┏━┓┏━┓╻ ╻╻╺┳╸┏━┓┏━┓
┏━┛┣╸ ┣┳┛┃ ┃   ┃╺┓┣┳┛┣━┫┃┏┛┃ ┃ ┣━┫┗━┓
┗━╸┗━╸╹┗╸┗━┛   ┗━┛╹┗╸╹ ╹┗┛ ╹ ╹ ╹ ╹┗━┛
root@reMarkable:~# sh -c "$(wget https://raw.githubusercontent.com/ddvk/remarkable-hacks/master/patch.sh -O-)"
Connecting to raw.githubusercontent.com (185.199.109.133:443)
wget: note: TLS certificate validation not implemented
writing to stdout
-                    100% |***************************************************************************************************|  7032  0:00:00 ETA
written to stdout
Disk space seems to be enough.
rM1 Version 2.10.0.324 - patch_25.1.02
Connecting to github.com (140.82.121.3:443)
wget: note: TLS certificate validation not implemented
Connecting to raw.githubusercontent.com (185.199.109.133:443)
saving to '/home/rmhacks/patch_25.1.02'
patch_25.1.02        100% |***************************************************************************************************| 79913  0:00:00 ETA
'/home/rmhacks/patch_25.1.02' saved
The backup /home/rmhacks/xochitl.2100324_rm1 is not the original file (was it replaced/ deleted?), cowardly aborting...
root@reMarkable:~# 
`

So, the question is, is there anything I can do to manually clean up and get the current patch to apply, or am I stuck waiting until the next rM update?

**Comment by ddvk** [comment]
switch to the other partition (check the script in remarkable-update), reupdate, remove the rmhacks folder

**Comment by Ilyo** [comment]
I did that, but sadly got the same issue.

I had already tried to roll back using the switch script prior to having this issue in the first place.. :-(

**Comment by Ilyo** [comment]
@snooxx - thanks for the reply.

Alas, whilst I'm reasonable tech savvy, I'm really a total linux n00b but I'll dig in and see if I can unravel that.

Cover me, I'm going in...

**Comment by Ilyo** [comment]
@snooxx Happy to report that did the trick.

Forced the upgrade, re-applied the patch and everything's working as expected again.

Thanks again, I really appreciate the help!
