### ISSUE TITLE
Question: is it possible to distinguish different pens?

### ISSUE THREAD

**Issue by dstango** [ddvk/remarkable-hacks#37]
I've been wondering whether it's possible to distinguish different pens from the software side (do pens have a kind of uuid or pen-type-id they transmit?). 

Thus it would be awesome to e.g. automatically switch the pen type -- when grabbing a Staedler e.g. automagically using the pencil, for the Lamy a pen and the original RM pen a ballpoint. 

That would be totally awesome for paper people, I think ;-) ...

Once again: thanks for your awesome patches - it's like Christmas and Birthday at the same time :-) ...

**Comment by ddvk** [comment]
nope, this is wacom tech,  all have the same id, you can distinguish between some tools eg eraser and some others but that’s it

**Comment by dstango** [comment]
thanks :-(
