### ISSUE TITLE
Question: More Handwriting conversion language?

### ISSUE THREAD

**Issue by nzbcorz** [ddvk/remarkable-hacks#370]
Hi, dear dev.

It's obvious that official OCR language is limited.

However, my device could unlock more "hidden" language.

When I use my reMarkable 2 few months ago, Chinese (Simplified) is available in the "Handwriting Conversion Language" (and its working). I have no idea how to active this feature, but it seems that on other devices using the same rmfakecloud, their devices are lack of this option, like the official system do. So it seems only my device is available to use that language.

![image](https://user-images.githubusercontent.com/25114850/138203829-6b674baa-b9e0-4e59-802c-c7d3da1f1094.png)
* as shown in my previous screenshot, it's available.

I'm here to ask for help that is there any configuration or switch that I can do to configure that done, or it's a feature of `remarkable-hacks`?

Thanks. Best wishes.

**Comment by ddvk** [comment]
sorry, not possible, too many dependenies
