### ISSUE TITLE
OCR on PDFs (27.2.01)

### ISSUE THREAD

**Issue by regrubtaf** [ddvk/remarkable-hacks#373]
I hate to keep grumbling about minor things, but was the OCR function in PDFs removed in patch 27.2.01 (v.2.10.2.356)?  It doesn't seem to be an option.  I don't really use this function, but it's still listed among the features added through the patch.

**Comment by ddvk** [comment]
not on purpose, restored

**Comment by regrubtaf** [comment]
Excellent. Works great!
