### ISSUE TITLE
Writing in the upper left corner

### ISSUE THREAD

**Issue by mrwth** [ddvk/remarkable-hacks#377]
When the tool bar is closed, the 1x1 cm square in the lop left corner serves to toggle it back, and it is impossible to write there (at least in the zen mode on rm2). Would it be possible to decrease a bit the size of that square (or do some other tweak that would allow writing there)?

**Comment by mrwth** [comment]
thanks!

**Comment by PkW4v3** [comment]
@ddvk Could you fix it for RM2 too?
Thanks🙏
