### ISSUE TITLE
Turkish keyboard (quwerty) and Quick and dirty reMarkable2 KOReader toggler support for rM2 update 2.10.2.356

### ISSUE THREAD

**Issue by strasbourgeois** [ddvk/remarkable-hacks#379]
Hi,

I really appreciate your efforts.  

Could you please add Turkish keyboard (quwerty) and Quick and dirty reMarkable2 KOReader toggler support for rM2 update 2.10.2.356?

Best

**Comment by ddvk** [comment]
could add the extra letter as long press eg (G,S,U)

**Comment by strasbourgeois** [comment]
That would be great! Thank you very much :)

**Comment by ddvk** [comment]
can we close this?
