### ISSUE TITLE
Swiping down to scroll up not working in landscape mode Page Overview or Table of Contents

### ISSUE THREAD

**Issue by Jdogzz** [ddvk/remarkable-hacks#380]
I'm using rm2 xochitl 2.10.2.356 with freshly installed hacks. I just noticed if I have any document in landscape mode, when I open the Page Overview or Table of Contents I can swipe up to scroll down, but cannot swipe down to scroll up. This was occurring on the last version of xochitl with the hacks, and when I upgraded to the current version of xochitl with the hacks the problem is still present.

**Comment by ddvk** [comment]
it seems this is a bug in the original xochitl

**Comment by Jdogzz** [comment]
Got it, I've reported it to them. Closing this issue.

**Comment by ddvk** [comment]
but I think fixed it

**Comment by Jdogzz** [comment]
I can confirm the patch works for me, thank you very much! I emailed remarkable about the problem but they asked me to go through a series of troubleshooting steps. I'll let that wait until the next xochitl update.
