### ISSUE TITLE
selective features – hidden close button

### ISSUE THREAD

**Issue by ONYX4407** [ddvk/remarkable-hacks#385]
Hello ddvk,

It is nice to see your work and additional features for RM2. I would like to ask you to selective hack. I can see many features in the package, but I'm interested especially to disappeared close button - cause I'm lefty... Based on that, I want to control all additional features from your package. Maybe I want to discover other features (but from your notes I don't understand why on rm2 I should have rm1 buton features?) but I would like to start with just one change in the original remarkable OS .

Is there any way to disable features one by one after installation? – just sth liek "checklist" to enable/add feature.

May I do permament hide of close button without other fetures? – can you point me to the part of the code that changes this, so I can create a patch that only changes this?

Is there any way to setup only gestures?

The main reason of asking to selective hack i.e. hidding close button, is the battery life. I consider every additional feature as other task/process running on background, so I just don't want that if I dont want to use the feature.

Thank you  for you answers. I am pretty sure I'm not only one who appreciates your help.

Jan

**Comment by ddvk** [comment]
there is a menu that can toggle most of the things. those things have no effect on the battery life as they are just cosmetic UI changes.

**Comment by ONYX4407** [comment]
Man, I take back all my worries... It's completely awesome, safe and powerfull... 
Thank you :)
