### ISSUE TITLE
List View of PDF files : do not show "Author" property

### ISSUE THREAD

**Issue by rex-banner** [ddvk/remarkable-hacks#394]
Hello,
Since 2.9 or 2.10, List View in a folder containing PDF now shows the "Author" properties of the PDF, which I find useless, inducing lack of visibility
https://ibb.co/bJLt46y
Could you remove this ?

**Comment by ddvk** [comment]
yea, sure, i think i removed it but ill check again

**Comment by ddvk** [comment]
yea, sure, i think i removed it but ill check again

**Comment by rex-banner** [comment]
Indeed, PDF Author is masked. Greater visibility :)
