### ISSUE TITLE
stroke/color menu too long in landscape mode (2.11)

### ISSUE THREAD

**Issue by mrwth** [ddvk/remarkable-hacks#399]
In the landscape mode the stroke/color menu doesn't fit into the screen, so it's impossible to select "red".

**Comment by ddvk** [comment]
i'll fix it

**Comment by michaelmcdonald** [comment]
Adding my +1 to this issue. Came across it today when viewing some PDFs that were forcing the display into landscape and I couldn't adjust the color of the pen.

**Comment by StLa1** [comment]
@ddvk Alternatively you could make the swipe up gesture cycle between all colors and not just the grayscale ones

(Did the touch area for this gesture change ? I have a very hard time triggering it now)

**Comment by JustusDinera** [comment]
Doesn't work to swipe thorught all colors. It goes back to black after white. (RM1)
