### ISSUE TITLE
Question : Handwriting conversion and email

### ISSUE THREAD

**Issue by baptd** [ddvk/remarkable-hacks#405]
Hi,
I have just received my tablet and had the unpleasant surprise to see that certain functions were now chargeable.
Does installing this hack re-enable these functions? The conversion of manual writing and sending email in particular

thanks in advance

**Comment by ddvk** [comment]
nope, those  particular functions are host based and require a server. your best bet is rmfakecloud for now

**Comment by baptd** [comment]
OK thank you ! I will check that
