### ISSUE TITLE
removing for warranty claim

### ISSUE THREAD

**Issue by Friismestemacher** [ddvk/remarkable-hacks#406]
hey there, 
anybody knows if the described process of removing the software ( sh -c "$(wget https://raw.githubusercontent.com/ddvk/remarkable-hacks/master/patch.sh -O-)" _ purge ) is enough to make it uneasy for remarkable to find out that this software was installed? 
I have sent in my rm2, because the power button is broken and am afraid that they will take themselves out of responsibility by bringing up this software issue.

**Comment by Eeems** [comment]
Software changes do not void hardware warranty, unless they can magically prove that the software change broke the power button.

**Comment by ddvk** [comment]
purge should be enough
