### ISSUE TITLE
Feature Request: Add support for Samsung pen

### ISSUE THREAD

**Issue by KlimaRitter** [ddvk/remarkable-hacks#408]
You have already added support for the Lamy Pen, could you add the same functionality for the Samsung Pen (S Pen EJ-PP610 for Galaxy Tab S6 Lite)?

**Comment by ddvk** [comment]
if you mean the button on the pen, it looks like it is using BLE (bluetooth low energy) which can't work with the rm, the pen has a battery as well. the lamy's button is part of the wacom's emr stuff.

**Comment by KlimaRitter** [comment]
I installed the remarkable-stylus hack (which I didn't install previously as I assumed to be part of this hack).
And with that one, the button on the pen works flawlessly. It has been an absolute game changer since for me.
Massive respect, love your work and will donate for sure!
