### ISSUE TITLE
Bookmarks stay disabled in Zen mode even if activated manually

### ISSUE THREAD

**Issue by StLa1** [ddvk/remarkable-hacks#41]
Zen mode deactivates Bookmarks creation, but the toggle is (fortunately) still visible in the Share menu. 
However it's not working. I used bookmarks a lot and always have Zen mode enabled, so it would be really cool to keep the toggle functional even in Zen

**Comment by ddvk** [comment]
this was done for #26, apparently not everyone s happy

**Comment by StLa1** [comment]
> this was done for #26, apparently not everyone s happy

I understand that it's disabled by default in Zen, but toggling it back on manually should work. Right now we simply can't have bookmarks in Zen

**Comment by StLa1** [comment]
Btw maybe you should close issues that you solved, since it starts to get a bit messy in the Issues tab

**Comment by ddvk** [comment]
i should probably revert it

**Comment by ddvk** [comment]
reverted
