### ISSUE TITLE
Bug in 2.12.1.527-patch_30.2.01

### ISSUE THREAD

**Issue by pstemper** [ddvk/remarkable-hacks#415]
I believe I found a small bug in the latest patch.  I installed the latest OS update (2.12.1.527) on my RM2, and then installed the hack as usual.  Everything appeared to work, so I made it "permanent" as I always do.

Later on, I went into a PDF that I had on the device.  First PDF I went into since 2.12.1.527.  It popped up a "window" explaining how I could now add a page to the PDF by clicking on the menu item.  At that point XOCHITL was "locked up" and the ONLY thing I could do is power off the rm.  It is JUST a guess, but I am guessing it is because it was jumping to an area in XOCHITL that was now patched for the hack.  I know the tutorial is removed when the hack is installed due to needed in the space.  Maybe that dialog is jumping into the middle of the tutorial or something.  I powered down the RM, removed the patch, then went into the PDF and got the dialog.  Then I could dismiss the dialog.  I then re-applied the patch, and now everything works (since it no longer needs to display that dialog.)

Just thought I would bring this up in case anyone else encounters it.

Thanks for all the hard work DDVK!  I have always loved the hacks you made for the rm, and I have been a contributor for a while now.  Thanks for all the hard work you put forward on this hack!!

**Comment by jmlgo** [comment]
Appending `PdfOrEbook_Introduction=true` to the `[Onboarding]` section of `/etc/remarkable.conf` works as well.

**Comment by ONYX4407** [comment]
Hi I found other bug on new update with zen mode icon.

When I am in Zen mode, I set tool "selector", then I hide panel, in the corner is showed wrong tool icon (bulletpoint).
Please check icons showed in Zen mode. 

Thank you.

**Comment by ddvk** [comment]
the bug with tip was that the click area was slightly offset, one had to click in the upper right corner above the X.

**Comment by ONYX4407** [comment]
> the bug with tip was that the click area was slightly offset, one had to click in the upper right corner above the X.

Thank you very much. Looks fine now.. I was slightly surprised at the meeting now when I shared the screen :)
Have a nice day.

**Comment by Finardi-FS** [comment]
I noticed that when i hold down the left button (RM1) to undo, it doesn't work.

Anyway thanks a lot for the patch ❤️

**Comment by martin-braun** [comment]
@Finardi-FS You might want to create an issue so it will be picked up, or did the latest version fix this bug as well?

**Comment by Finardi-FS** [comment]
@martin-braun, [patch_30.1.04](https://github.com/ddvk/remarkable-hacks/blob/master/patches/2121527_rm1/patch_30.1.04) fixed this bug. thanks for your interest!

P.s. thanks again @ddvk!!!
