### ISSUE TITLE
Folder under MY FILES disapeer

### ISSUE THREAD

**Issue by ikerside** [ddvk/remarkable-hacks#418]
after update to ddvk hacks v12 rm1: 2.12.1.527 , it is not showing all my folders under Myfiles, i see my files with shortcut but i am not able to navigate in my folders .

**Comment by ddvk** [comment]
what patch are you on, 30.1.07? does switching to grid view fixes it?

**Comment by ikerside** [comment]
i used automatic magic, ... yesturday i try 2 time with same issue. i just retry and now no issue ! perfect !

**Comment by Nuvzz** [comment]
I have the exact same issue for me.
I have been using all previous patches before and installed using automagic.

**Comment by martin-braun** [comment]
This is basically the follow up of #416. Always install the latest patch right before you report an issue. :)

**Comment by regrubtaf** [comment]
Question: when moving from one remarkable-hacks patch to a more recent one, for the same rM OS version, do you have to uninstall the old patch before installing the new patch?  For example, if you wanted to go from patch_30.2.03 to patch_30.2.07, can you just run the automagic script for the latest version, or do you have to get rid of 30.2.03 first?

**Comment by pstemper** [comment]
You can just run the automagic script again..
