### ISSUE TITLE
Add comma to first page of keyboard

### ISSUE THREAD

**Issue by dstango** [ddvk/remarkable-hacks#42]
Having just sent a document as email I realized that I missed the comma "," on the first page of the keyboard (in my case: German) and had to switch to page 2 several times to insert it.
As I noticed that the various keyboard layouts consist of varying numbers of "keys" I wonder if you could sneak in a comma button onto the first page.

**Comment by dstango** [comment]
I saw you seem to have added it -- thanks! But it doesn't show in any of the three keyboard layouts on my rm...

**Comment by ddvk** [comment]
i may have added in only when it’s in email mode

**Comment by dstango** [comment]
I actually tried it in the email body ....

**Comment by ddvk** [comment]
what does you version show? should be patch051-22-g1fe1df4 (this is 2.1.1.3), if not execute the automagic again

**Comment by dstango** [comment]
Version 2.2.0.48 patch05_1-26-ga190428

**Comment by ddvk** [comment]
that explains it, pushed a new 22048 with the changes

**Comment by dstango** [comment]
Now it's working!!! :-) thanks!
