### ISSUE TITLE
2.12.2.573 for RM2 out

### ISSUE THREAD

**Issue by alan412** [ddvk/remarkable-hacks#429]
I accidentally had on auto-update and it pulled it.   Not sure what is new in it.

**Comment by regrubtaf** [comment]
@alan412 2.12.2 is just cosmetic changes and bug fixes. Though they didn't fix the one bug I was hoping they would.  This is the beta release note.  Sounds like its out of beta now.  https://support.remarkable.com/hc/en-us/articles/360021049478-Overview-of-beta-software-releases

**Comment by NilsIrl** [comment]
sorry this is a bit off-topic but it's the reason I had auto-update on in the first place. Is there a way to update without auto-updates on? In order for the button "check updates" to appear I need to enable auto updates on my device

**Comment by Eeems** [comment]
> sorry this is a bit off-topic but it's the reason I had auto-update on in the first place. Is there a way to update without auto-updates on? In order for the button "check updates" to appear I need to enable auto updates on my device

Correct, in order to update, you have to turn on auto updates. You can then turn it off again after updating.

**Comment by CrazyEasy** [comment]
@ddvk 😉

**Comment by Eeems** [comment]
@ddvk it's also out for the rM1

**Comment by 3eefc4ke** [comment]
1.5 pen thickness - Woo Hoo! Thank you @ddvk 🥇

**Comment by alan412** [comment]
Thank you @ddvk
