### ISSUE TITLE
Expand email body size (or show characters remaining)

### ISSUE THREAD

**Issue by dstango** [ddvk/remarkable-hacks#43]
The email body length seems to be limited to 255 characters. I don't have hopes that can easily be expanded, but if it's possible that would be great.

Alternatively it would be helpful to display the number of remaining characters while typing the email body.

**Comment by ddvk** [comment]
you sure about that, there should be no limit. The scrolling is a bit broken at the moment

**Comment by dstango** [comment]
Strange ... I remember I couldn't continue typing recently, but now it's working. 
did it maybe get fixed in the current update. 

Sorry for bothering you!

**Comment by ddvk** [comment]
it is somewhat broken, may have lost focus
