### ISSUE TITLE
Corruption of notebooks (blank pages) - hack-related or no?

### ISSUE THREAD

**Issue by Tridens92** [ddvk/remarkable-hacks#432]
Hey, all.

I'm having a very troubling issue over the past several months (I'm NOT saying this is ddvk-hack-related, but I'm seeking to rule it out).  

I'm finding that numerous notebooks are being corrupted.  Basically I'll go into a notebook, and the written contents will appear for less than 1 second and then disappear, leaving only the template.  If I go into Thumbnail view of the notebook, I can see the text of the pages.  But when I then choose to view the page again (or often any other page), the text again appears briefly, then disappears.  Eventually it seems like the pages start to go blank in the thumbnail view too.

Unfortunately, this is *silent* data loss, because it's not discovered until I open the notebook again.  At that point, the change/corruption is already synced to the cloud and the data is gone.  That then requires working with reMarkable support to restore a backup (the last time I needed to do this it took a whole month to get a notebook restored!!!).

Anyone else experiencing something similar?  @ddvk , is there any possibility at all that this is hack-related?

I simply can't trust my reMarkable anymore, which is a shame.  Every time I open a notebook I'm biting my nails, wondering if my page is going to disappear before my eyes.

Thanks for any feedback from @ddvk and this great community!

**Comment by dstango** [comment]
I haven't noticed anything of the likes, but had strange sync behaviour in recent weeks: it was like my whole remarkable wanted to sync everything over and over again ... maybe that's related to the cloud sync migration @pstemper mentioned.
And we had two minor updates recently - related?!?
Do you happen to have wifi turned on usually?
If you're on windows the rm desktop software has files stored in %userprofile%\AppData\Roaming\remarkable\desktop -- maybe make a backup or preserve an old one -- just in case. I guess with other OS there should be a file cache in some similar place.

**Comment by ddvk** [comment]
it is very unlikely, nothing to do with rendering has been touched. 
They do seem to change the format of the notes from time to time and the conversion could be failing for some reason.
I would suggest checking the log.txt file for any warnings (after the content of a file that you load disappears)

**Comment by Tridens92** [comment]
Thanks, @pstemper for the info.  Yes, I've seen data loss reported on the fb group, but it seems like it was more related to entire notebooks disappearing, rather than corruption of individual notebooks in the way I'm describing.  Again, rM support seems to confirm this is an "occasional issue", but it's been "occasional" three times for me recently. And those are only the ones I've discovered (you don't know until you open a notebook and your page briefly appears and then goes blank!).

@dstango I've noticed that recent behavior too.  I asked on fb and some suggested it might be because rM is syncing "last page viewed" now.  So even if you haven't modified the file, or merely opened it for viewing on the desktop or mobile app, it's going to force a sync.  I wish they'd turn this feature off or make it optional. At this point, I have little confidence in rM's syncing, so all these syncs just feel risky to me for not much benefit.

@ddvk , thanks for confirming from your side that it's not hack-related.  I assumed so, but wanted to rule it out.

Have a great week, everyone!

**Comment by ddvk** [comment]
@Tridens92 when it briefly appears is it a bit pixelated? because usually first the cached thumbnail image is displayed and then the page is rendered

**Comment by Tridens92** [comment]
HI, @ddvk .  Yes, that's the behavior sometimes.  Other times I'll click the thumbnail page and nothing at all is displayed.  Thanks for the confirmation that this is probably just thumbnail data that I'm seeing, unfortunately.

**Comment by Tridens92** [comment]
Can someone tell me where the reMarkable log.txt file is located that @ddvk mentions I could check to look for warnings?  I'm still having this corruption issue.  Thanks!

**Comment by Tridens92** [comment]
@Eeems , thanks so much!  I was looking on my PC, assuming it was kept with the companion app installation.  That would explain why I couldn't find it.  :)
