### ISSUE TITLE
rm1: menus slower to open than stock firmware

### ISSUE THREAD

**Issue by sersorrel** [ddvk/remarkable-hacks#438]
I recently noticed my rm1 seems slower (specifically, opening/closing the sidebar menus (eraser, pen thickness, templates, ...) is slower) with the hacks installed – originally I noticed this on 2.12.2.573, but I just updated to 2.12.3.606 and the slowness is present there too.

On stock firmware, when there's nothing behind the menus, they open and close near-instantly. When there's something behind a menu (e.g. the page has a non-blank template), it still feels fast to open, because the black menu outline and text appear instantly, even though the template still shows through in the areas that should be white – they're cleared properly a little later. It takes a little longer for the menu to close when there's something behind it, though.

With the hacks installed, opening/closing menus is never fast, even when there's nothing behind them. It feels like it's doing the same kind of redraw as it would when there's text or a template behind them, even when the background is actually blank. It also doesn't draw in the black parts of the menus early when opening them (instead the whole menu shows up at once), which makes the device feel _much_ slower.

Is this just an unavoidable consequence of the hack adding more stuff to the menus?

**Comment by ddvk** [comment]
I saw what you mean, I should be able to fix it

**Comment by Tridens92** [comment]
So glad to hear this!  I thought perhaps it was slowdown from the rm OS bloating and slowing on the rM1 vs. rM2.

**Comment by ddvk** [comment]
is it better?

**Comment by sersorrel** [comment]
yes, that feels much faster! thank you so much ^.^

**Comment by Tridens92** [comment]
Thanks again for all of your work, @ddvk !

**Comment by Reddevil57** [comment]
Hi,
Is there an explanation somewhere to how we can instal this patch ?

**Comment by Reddevil57** [comment]
ok, I understand, thanks, :) but my question was for installing the small patch which adresses the slow menus. I am already in 2.12.3.60

**Comment by Reddevil57** [comment]
understood ! :)
Thanks very much
