### ISSUE TITLE
Patch for version 2.13.0.758

### ISSUE THREAD

**Issue by nitish-agg** [ddvk/remarkable-hacks#442]
Dear sir, first of all, many many many thanks for all this. I almost feel bad for asking for a new patch as I forgot to disable the automatic updates. Would it be possible for you to provide us with the patch for version 2.13.0.758?

Thanks

**Comment by martin-braun** [comment]
Duplicate #440

**Comment by ddvk** [comment]
yeah, it's coming

**Comment by ddvk** [comment]
Duplicate https://github.com/ddvk/remarkable-hacks/issues/440
