### ISSUE TITLE
v. 2.14. 

### ISSUE THREAD

**Issue by regrubtaf** [ddvk/remarkable-hacks#446]
It looks like there's another official update rolling out already. Among other fixes, it will add a tags feature for inter- and intra-document labels. This feature will also add a new icon to the menu bar within a file.

https://support.remarkable.com/hc/en-us/articles/5541796483741

**Comment by martin-braun** [comment]
I wonder why 2.14 is not rolled out for me, not even when I enroll the beta program.

**Comment by regrubtaf** [comment]
@ddvk Thank you very much!

**Comment by ai212983** [comment]
Why this ticket was closed? I thought 2.14.0.861 is in alpha yet. README specifies it as wip - work in progress.

**Comment by Eeems** [comment]
> Why this ticket was closed? I thought 2.14.0.861 is in alpha yet. README specifies it as wip - work in progress.

Because the author of the ticket closed it.
