### ISSUE TITLE
Is your patch similar with 22048 version and 2.1.1.3 version ?

### ISSUE THREAD

**Issue by zelomel** [ddvk/remarkable-hacks#45]
Did you implement same patches with 22048 and 2113 version ?

**Comment by dstango** [comment]
viewing the patches-directory it looks to me like 2.2.0.48 and 2.1.1.3 are both currently updated with new patches.

**Comment by ddvk** [comment]
they should be mostly the same

**Comment by ddvk** [comment]
updated readme
