### ISSUE TITLE
VERSION 2.13.0.758-PATCH_25.2.01-G-G6BE1F40

### ISSUE THREAD

**Issue by jayrich5807** [ddvk/remarkable-hacks#462]
VERSION 2.13.0.758-PATCH_25.2.01-G-G6BE1F40
I am using

  I can't put in a new PDF file because I can't roll back and it doesn't sync.

No rollback, no version upgrade

Is there any way?

/home/rmhacks/patch.sh 

Even if I delete the folder, the update does not work;

![image](https://user-images.githubusercontent.com/65334090/184125231-a5980397-e09c-45e4-a833-8cd064e92c5f.png)

**Comment by Eeems** [comment]
It looks like you aren't connected to the internet, which would be why none of that works.

**Comment by jayrich5807** [comment]
> It looks like you aren't connected to the internet, which would be why none of that works.

It doesn't seem to be an internet problem.  The remarkable thing is that it is well connected to the Internet, and the computer is also the same. In this case, I uninstalled the hack and proceeded with the update, and then installed hack again, but now the hack is not deleted.

**Comment by Eeems** [comment]
> > It looks like you aren't connected to the internet, which would be why none of that works.
> 
> It doesn't seem to be an internet problem. The remarkable thing is that it is well connected to the Internet, and the computer is also the same. In this case, I uninstalled the hack and proceeded with the update, and then installed hack again, but now the hack is not deleted.

Alright, well the current error you are encountering when trying to remove the hacks is due to network connectivity.

**Comment by jayrich5807** [comment]
![image](https://user-images.githubusercontent.com/65334090/184262964-221807c3-acff-4c55-93e9-3709e8e7cc6a.png)

![image](https://user-images.githubusercontent.com/65334090/184263029-1977d3e8-a38f-45d9-8cc3-b1909e47e63b.png)
![image](https://user-images.githubusercontent.com/65334090/184263047-44c10b06-2122-4e5a-b666-3eddb0c7099f.png)

**Comment by Eeems** [comment]
So you are connected to wifi, but unable to connect to the wider internet, You have a couple options:

- Try to resolve your network connectivity issue
- Copy the patch.sh script to your device manually and run it

**Comment by jayrich5807** [comment]
As you said, it is possible that the internet is the problem.

The Wi-Fi appears to be connected, but I think that it may not actually be connected.

How do I manually apply a new patch?

**Comment by Eeems** [comment]
To uninstall, copy the patch.sh script to your device and run it as per the instructions in the readme. There may already be a copy on the device based on the path mentioned in the readme for the offline step.

**Comment by dstango** [comment]
How about connecting to another wifi like a hotspot from a mobile phone to check if that helps with the network issue?
Or rebooting the router - I recently had the stranges issues with  network printer, and turned out the router had a hick up of some sort, and a restart resolved the issues.

**Comment by jayrich5807** [comment]
> How about connecting to another wifi like a hotspot from a mobile phone to check if that helps with the network issue?
> Or rebooting the router - I recently had the stranges issues with network printer, and turned out the router had a hick up of some sort, and a restart resolved the issues.

I've tried tethering, but it's still the same

**Comment by Eeems** [comment]
> > How about connecting to another wifi like a hotspot from a mobile phone to check if that helps with the network issue?
> > Or rebooting the router - I recently had the stranges issues with network printer, and turned out the router had a hick up of some sort, and a restart resolved the issues.
> 
> I've tried tethering, but it's still the same

Tethering your tablet? It doesn't support tethering. Unless you mean using your phone as a hotspot?

**Comment by jayrich5807** [comment]
> > > How about connecting to another wifi like a hotspot from a mobile phone to check if that helps with the network issue?
> > > Or rebooting the router - I recently had the stranges issues with network printer, and turned out the router had a hick up of some sort, and a restart resolved the issues.
> > 
> > 
> > I've tried tethering, but it's still the same
> 
> Tethering your tablet? It doesn't support tethering. Unless you mean using your phone as a hotspot?

I tried connecting to the hotspot of my phone, but it didn't work.
Try connecting to your company's Wi-Fi
I've tried connecting from home, but it still doesn't seem to work.

**Comment by Eeems** [comment]
Very odd. Have you tried running the uninstall offline yet? If you have and you still don't have network access, I'd recommend jumping on the community discord and asking for help fixing the network connection issue.

**Comment by jayrich5807** [comment]
> Very odd. Have you tried running the uninstall offline yet? If you have and you still don't have network access, I'd recommend jumping on the community discord and asking for help fixing the network connection issue.

I know how to use only automagic codes

I don't know which one to delete offline.

I uninstalled /home/rmhacks/patch.sh using Filezilla and restarted it, but still no upgrade.

**Comment by Eeems** [comment]
So you've removed the hacks and it's still not connecting to the internet?

**Comment by jayrich5807** [comment]
> So you've removed the hacks and it's still not connecting to the internet?
Ames Thank you for your many replies.

I don't know much about this, so I don't seem to be able to execute it properly as you said.
1. I don't know how to remove hack offline.
  I tried forcibly removing the /home/rmhacks/patch.sh folder. I wonder if this method is a way to remove nuclei.
2. The current situation is as follows.
I'm connected to wifi, but it doesn't seem to connect as you said.
Can't connect to email or cloud and can't sync.
I logged out of my account and tried to connect again, but that doesn't work anymore.

![ScreenShot_20220815141646](https://user-images.githubusercontent.com/65334090/184580562-b14b8186-3020-47ea-8a86-10497c4d364e.png)

![ScreenShot_20220815142046](https://user-images.githubusercontent.com/65334090/184580725-ee66518a-a407-4448-9224-38fdf12d3f88.png)

**Comment by martin-braun** [comment]
I would rather start off by fixing the internet problem on your remarkable. Do it at home where no Firewall could hinder you. Try to ping your router IP, 1.1.1.1 and google.com from the device in your SSH session. I got the feeling you have DNS problems on the device. Are you sure you did not tamper with any configurations on the device?

To solve the permission problem, you should add execute permissions to the patch.sh: 

```sh
sudo chmod +x /home/rmhacks/patch.sh
```

Then you can run it.

**Comment by Eeems** [comment]
/home/rmhacks contains the backup of the unlatched version of xochitl. **Do not delete it**. As @martin-braun said, you need to make it executable in order to run it, which is something missing from the readme.

**Comment by jayrich5807** [comment]
> 나는 오히려 당신의 놀라운 인터넷 문제를 해결하여 시작하고 싶습니다. 방화벽이 당신을 방해할 수 없는 집에서 하십시오. SSH 세션의 기기에서 라우터 IP, 1.1.1.1 및 google.com을 ping해 봅니다. 장치에 DNS 문제가 있다는 느낌이 들었습니다. 장치의 구성을 변경하지 않았습니까?
> 
> 권한 문제를 해결하려면 patch.sh를 실행하기 전에 자신에게 실행 권한을 부여해야 합니다.
> 
> ```shell
> chmod +x /home/rmhacks/patch.sh
> ```

![image](https://user-images.githubusercontent.com/65334090/184922961-269869c9-fb5e-4a38-9d47-dc9c4dc78240.png)
right?

**Comment by Eeems** [comment]
Yes, now you can run it: `/home/rmhacks/patch.sh purge`

**Comment by jayrich5807** [comment]
> Yes, now you can run it: `/home/rmhacks/patch.sh purge`

Since the laptop and the Remarkable are in the same Wi-Fi environment, it does not mean that the Internet is not available.

**Comment by Eeems** [comment]
> > Yes, now you can run it: `/home/rmhacks/patch.sh purge`
> 
> There is still something wrong.

Could you clarify?

**Comment by jayrich5807** [comment]
![image](https://user-images.githubusercontent.com/65334090/184924510-15814b94-93a4-443e-ba7f-3ec76819d8f6.png)

seems to have been resolved

I don't know how it was solved.

**Comment by jayrich5807** [comment]
> You have no free space on your root partition, this explains why the device can't connect to the network. See if the following helps: `journalctl --vacuum-size 1`
> 
> If not, we'll need to sort out how to free up a little more space.
> 
> See #420 for some more information.

1. chmod +x /home/rmhacks/patch.sh
this helped

2.patch.sh seems to have a problem.

It seems to have happened because I did a purge using the previous patch.sh.


The current situation is this:
![image](https://user-images.githubusercontent.com/65334090/184926578-bd0ab2da-04b9-455a-902a-66a57db6b7df.png)

**Comment by Eeems** [comment]
patch.sh didn't have a problem, it saw that there still wasn't enough space and stopped. you need at least 3MB of free space for it to run. You can check how much space is free by running `df -h /`. It looks like there wasn't any extra space cleared. You might want to reboot to make sure that the filesystem synced properly. If `df -h /` says that there is at least 3MB of space, you can run patch.sh purge again.

**Comment by jayrich5807** [comment]
> patch.sh didn't have a problem, it saw that there still wasn't enough space and stopped. you need at least 3MB of free space for it to run. You can check how much space is free by running `df -h /`. It looks like there wasn't any extra space cleared. You might want to reboot to make sure that the filesystem synced properly. If `df -h /` says that there is at least 3MB of space, you can run patch.sh purge again.

![image](https://user-images.githubusercontent.com/65334090/184927570-825701fa-f380-4538-aaff-f72b4bc9640f.png)
Thank you so much for your help.

People who have the same problem as me, please refer to it and solve it.

Thank you so much for your interest and finding a solution.

**Comment by jayrich5807** [comment]
> patch.sh didn't have a problem, it saw that there still wasn't enough space and stopped. you need at least 3MB of free space for it to run. You can check how much space is free by running `df -h /`. It looks like there wasn't any extra space cleared. You might want to reboot to make sure that the filesystem synced properly. If `df -h /` says that there is at least 3MB of space, you can run patch.sh purge again.

고마워요 친구~
thank you friend
