### ISSUE TITLE
2.14.3.958 update (RM2)

### ISSUE THREAD

**Issue by Blerkselmans** [ddvk/remarkable-hacks#466]
The good thing about forgetting to disable auto updates is that you get the chance to wonder how people can do without ddvk. Although nice, it shouldn't take too long ;-)
Kind request to update the ddvk hack for 2.14.3.958 and fully appreciating the work/efforts you put into this project.

**Comment by 64MPH** [comment]
One of my kids switched on auto-update and I'm in the same boat as Blerkselmans.  Similarly kind request to update the hack for 2.14.3.958 please.  Seriously, I am already so frustrated with operating using the native menu.  I also appreciate the work that has to go in, but it is a phenomenal hack and so useful.

**Comment by p-phillips** [comment]
And me.  I have now switched auto updates off so this doesn't happen again.  ddvk makes such a difference. pretty please can we have it for the latest version?

**Comment by Mavyre** [comment]
2.14.3.977 has just been released

**Comment by fuerst** [comment]
And me (new to the Remarkable world) got it installed before I even knew this hacks are the more important features :-)

**Comment by Mavyre** [comment]
@fuerst Don't worry, the tablet forces you to have the latest updates on first boot...

**Comment by samjliu** [comment]
> And me (new to the Remarkable world) got it installed before I even knew this hacks are the more important features :-)

Same here :(

**Comment by fuerst** [comment]
> @fuerst Don't worry, the tablet forces you to have the latest updates on first boot...

Yeah - so I got time to learn the basics first...

**Comment by NancyJin** [comment]
I accidentally auto-upgrade to 2.14.3.977 , and can no longer re-apply the hacks... any suggestions would be of great help!!!!

**Comment by Blerkselmans** [comment]
> I accidentally auto-upgrade to 2.14.3.977 , and can no longer re-apply the hacks... any suggestions would be of great help!!!!

Revert back to previous version (Google: Remarkable downgrade), although this didn't work for me or wait for the new patch to arrve (has been so far the longest week of my life ;-) )

**Comment by NancyJin** [comment]
> > I accidentally auto-upgrade to 2.14.3.977 , and can no longer re-apply the hacks... any suggestions would be of great help!!!!
> 
> Revert back to previous version (Google: Remarkable downgrade), although this didn't work for me, or wait for the new patch to arrive (has been so far the longest week of my life 😉 )

I do find the guide, but cannot find the official upgrade jar... i browsed their official git repo...  so now I get stuck at the first step, not even start play around it yet...

**Comment by Admonstrator** [comment]
You could try to downgrade by switching the partition.

Create a shell file with the following content:
```
#!/bin/bash
# switches the active root partition

fw_setenv "upgrade_available" "1"
fw_setenv "bootcount" "0"

OLDPART=$(fw_printenv -n active_partition)
if [ $OLDPART  ==  "2" ]; then
    NEWPART="3"
else
    NEWPART="2"
fi
echo "new: ${NEWPART}"
echo "fallback: ${OLDPART}"

fw_setenv "fallback_partition" "${OLDPART}"
fw_setenv "active_partition" "${NEWPART}"
```

Execute it and reboot the device.

**Comment by NancyJin** [comment]
> 

Thank you !!!! It worked as MAGIC!!! @Blerkselmans  try it, then you can re-apply the hacks, no need to wait! : )

**Comment by Blerkselmans** [comment]
Thank you, I know the script and I have applied it. Partition 2 and 3 contain both a version higher than 2.14.1.866. Booting from either of them leads to a non-hacked version.

**Comment by cyCharlie** [comment]
Also on 2.14.3.977 - patiently waiting...

**Comment by cyCharlie** [comment]
Is there any way we can compile from source code?

**Comment by palfrey** [comment]
> Is there any way we can compile from source code?

No, see https://github.com/ddvk/remarkable-hacks#faq

**Comment by cyCharlie** [comment]
sigh...

**Comment by Wortlaut** [comment]
> You could try to downgrade by switching the partition.
> 
> Create a shell file with the following content:
> 
> ```
> #!/bin/bash
> # switches the active root partition
> 
> fw_setenv "upgrade_available" "1"
> fw_setenv "bootcount" "0"
> 
> OLDPART=$(fw_printenv -n active_partition)
> if [ $OLDPART  ==  "2" ]; then
>     NEWPART="3"
> else
>     NEWPART="2"
> fi
> echo "new: ${NEWPART}"
> echo "fallback: ${OLDPART}"
> 
> fw_setenv "fallback_partition" "${OLDPART}"
> fw_setenv "active_partition" "${NEWPART}"
> ```
> 
> Execute it and reboot the device.

hi for an windows user, please so kind: what have i to do for reating an run such a file on my rM2. The access to the root of rM2 is no problem ( i use putty on windows) but i need the next steps . Thanks a lot to all

**Comment by Admonstrator** [comment]
> > You could try to downgrade by switching the partition.
> > Create a shell file with the following content:
> > ```
> > #!/bin/bash
> > # switches the active root partition
> > 
> > fw_setenv "upgrade_available" "1"
> > fw_setenv "bootcount" "0"
> > 
> > OLDPART=$(fw_printenv -n active_partition)
> > if [ $OLDPART  ==  "2" ]; then
> >     NEWPART="3"
> > else
> >     NEWPART="2"
> > fi
> > echo "new: ${NEWPART}"
> > echo "fallback: ${OLDPART}"
> > 
> > fw_setenv "fallback_partition" "${OLDPART}"
> > fw_setenv "active_partition" "${NEWPART}"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Execute it and reboot the device.
> 
> hi for an windows user, please be so kind: what have I to do for creating and run / execute such a file on my rM2. The access to the root of rM2 is no problem ( I use puTTy on windows) but i need the next steps . Thanks a lot to all

To be honest: If you don't know what you are doing - don't do it. In the worst case, it could convert your device into a big brick.
If you still want to proceed:

1. Connect to your device by using Putty
2. Enter: `vi switch-partition.sh`
3. Press: `i`
4. Copy the whole script and paste it by clicking with the right mouse button.
5. Press: ESC
6. Enter: `:wq`
7. vi will close now, and you will be back in the shell
8. Enter: `bash switch-partition.sh`

Trying to list up these steps by my mind - so no warranty for anything.

**Comment by Wortlaut** [comment]
thanks a lot  but  it didn't work. on the other side, DDVK wrote on hour age, that he will upload the hack in a few time. So I have to wait. But you have my thanks

**Comment by palfrey** [comment]
See https://github.com/ddvk/remarkable-hacks/issues/469

**Comment by Blerkselmans** [comment]
Upgraded to 977 and applied the hack. Feels great to be whole again. It's been a tough two weeks.
Thanks so much @ddvk for the time and efforts every time again!

**Comment by 64MPH** [comment]
What Blerkselmans said.  Thanks so much for the hack.  I won't waste loads of time trying to use all the gestures that I lost now.  Also, bookmarks AND tags - gamechanger.  Thanks so much again @ddvk.
