### ISSUE TITLE
The backup /home/rmhacks/xochitl.2020 is not the original file (was it replaced/ deleted?), cowardly aborting...

### ISSUE THREAD

**Issue by Rage997** [ddvk/remarkable-hacks#47]
By following the instructions on the readme, I ran the following line on the RM

`sh -c "$(wget https://raw.githubusercontent.com/ddvk/remarkable-hacks/master/patch.sh -O-)" `

Here's my ouput

```
remarkable: ~/ sh -c "$(wget https://raw.githubusercontent.com/ddvk/remarkable-hacks/master/patch.sh -O-)" 
Connecting to raw.githubusercontent.com (151.101.112.133:443)
wget: note: TLS certificate validation not implemented
-                    100% |*******************************************************************************************|  3508  0:00:00 ETA
Disk space seems to be enough.
Version 2.0.2.0
Connecting to github.com (140.82.118.3:443)
wget: note: TLS certificate validation not implemented
Connecting to raw.githubusercontent.com (151.101.112.133:443)
patch_224            100% |*******************************************************************************************| 39533  0:00:00 ETA
The backup /home/rmhacks/xochitl.2020 is not the original file (was it replaced/ deleted?), cowardly aborting...
```

Can't figure out what it is and how to fix it

**Comment by ZacharieALES** [comment]
I had the same problem and fixed it like that (be aware that it removes some safety checks provided by the standard script): 

1 - Connect to the rM through ssh
ssh root@10.11.99.1

2 - Make a backup of the current xochitl file (in case something goes wrong)
cp /usr/bin/xochitl /usr/bin/xochitl_official_backup
cp /home/root/xochitl.2113 /home/root/xochitl.2113

3 - Download the latest patch
wget https://github.com/ddvk/remarkable-hacks/raw/master/patches/22048/patch_03

4 - Apply the patch
bspatch /usr/bin/xochitl xochitl.patched /home/root/patch_03

5 - Stop some services and cleanup before starting the patched version:
root@reMarkable:~# systemctl stop xochitl
root@reMarkable:~# systemctl stop remarkable-fail
root@reMarkable:~# rm /tmp/*crash*
root@reMarkable:~# rm -fr .cache/remarkable/xochitl/qmlcache/
root@reMarkable:~# QT_LOGGING_RULES=*=false  ./xochitl.patched || echo "It crashed?"

6  -  To make it permanent, replace /usr/bin/xochitl by xochitl.patched
Ctrl + z
bg
cp /home/root/xochitl.patched /usr/bin/xochitl

**Comment by Rage997** [comment]
Thanks for the reply

After the last line in step 5, I get:
`root@remarkable:~# QT_LOGGING_RULES=*=false ./xochitl.patched || echo "It crashed?"
Segmentation fault
It crashed?
`

**Comment by ZacharieALES** [comment]
Is your current rM version 2.2.048?

**Comment by Rage997** [comment]
My remarkable version: 2.0.2.0. I guess I should update it?

**Comment by Rage997** [comment]
I confirm: after updating to version 2.2.048 everything works like charm
