### ISSUE TITLE
2.14.3.977 now displays "recent notebook list" perpendicular/sideways when in landscape mode. Anyone else seeing the same thing? 

### ISSUE THREAD

**Issue by rclang** [ddvk/remarkable-hacks#470]
Viewing a landscape notebook, 2-finger swipe up, recent notebooks come up but are displayed perpendicular, as if in portrait view upside down. Anyone else experiencing? Came right after this patch. Not sure if it's something I did.

**Comment by ddvk** [comment]
yeah, a bug, didn't test everything...

**Comment by rclang** [comment]
Would be impossible to test everything, methinks. That's what community is for :) 
Thanks for all that you do! This is a minor one, was mostly curious if it was something I was doing LOL

**Comment by ddvk** [comment]
fixed in 1005
