### ISSUE TITLE
Running Time Zone Command

### ISSUE THREAD

**Issue by nhadfield** [ddvk/remarkable-hacks#471]
Forgive my ignorance, but I can't seem to run the time zone command.  What is the full string of text/code I need to enter?

Thanks

**Comment by Eeems** [comment]
The full text of the code can be found at https://github.com/ddvk/remarkable-hacks#timezones
If that isn't enough information, what is the error, and what extra information do you need?

**Comment by nhadfield** [comment]
-sh: timedatect1: command not found

**Comment by Eeems** [comment]
Ah, that would be because it's `timedatectl` not `timedatect1`

**Comment by nhadfield** [comment]
ahhh I see.  Thanks!

**Comment by Eeems** [comment]
@nhadfield does it work now?

**Comment by nhadfield** [comment]
yeah that worked.  Thanks again

**Comment by Eeems** [comment]
@nhadfield awesome, could you close this issue :)
