### ISSUE TITLE
v2.15 compatibility

### ISSUE THREAD

**Issue by bgajdero** [ddvk/remarkable-hacks#472]

**Comment by DecisionDigital** [comment]
Hi team. Do you have an ETA on a new build to fix compatibility with 2.15? Really appreciate the great product you have created. Cheers

**Comment by dstango** [comment]
Is it already out? I can't see any release notes for 2.15. Or are you on the beta channel? @ddvk only adapts the rm hacks after a new production release is out.

**Comment by pstemper** [comment]
No, 2.15 is still Beta.

**Comment by noizo** [comment]
2.15.0.1067 is out

**Comment by alaunay** [comment]
That's interesting: ssh in ipv4 doesn't work with 2.15.0.1067, but it works in ipv6...

**Comment by alaunay** [comment]
Patch 2.15 is out and works well. I believe this can be closed.

**Comment by DecisionDigital** [comment]
You guys are the best. New version went right in. This is me ringing the virtual bell for awesome assistance.

**Comment by Osndok** [comment]
> In the logs: `` Oct 07 17:26:12 reMarkable dropbear[361]: Exit before auth from <::ffff:A.B.C.D:37120>: Failed assertion (../dropbear-2020.81/rsa.c:164): `key != NULL' ``

That seams to be something to do with the key algo types being offered. I found this: https://github.com/mkj/dropbear/issues/219

**Comment by habnabit** [comment]
> That seems to be something to do with the keypair types, and the host (tablet in this case) not having an RSA key to offer. I found this: [mkj/dropbear#219](https://github.com/mkj/dropbear/issues/219)

most specifically, it's the client saying "send me an RSA host key" and dropbear crashing instead of saying "i don't have one". how you tell the client "only accept ed25519 host keys" depends on the client.
with openssh, you can also do this by setting `-o HostKeyAlgorithms=ssh-ed25519` on the command line, or in the `~/.ssh/config` file per-host.
