### ISSUE TITLE
2.15.0.1067 I did something to make sidebar clock disappear, is there a toggle somewhere?

### ISSUE THREAD

**Issue by rclang** [ddvk/remarkable-hacks#479]
Unsure how but did the patch to latest and lost the clock, ... perhaps I hit a toggle inadvertently. Tried resetting the time zone without error but how can you get clock to display back?

**Comment by regrubtaf** [comment]
@rclang Same thing happened to me (rM2, 2.15.0.1067), but for some reason, when I activated the handwriting conversion menu (the big "L" in the bottom right corner menu), after I closed the menu, the clock/date came back.

**Comment by ddvk** [comment]
long press on on the clock

**Comment by rclang** [comment]
Long press is it! Sorry if this was documented and I missed it searching. It works, thank you tons!
