### ISSUE TITLE
2.15.0.1067 - transparency not supported in sleepscreen

### ISSUE THREAD

**Issue by andreapanontin** [ddvk/remarkable-hacks#482]
I updated to 2.15.0.1067 and if I replace the suspended.png file with a custom one with transparency, the transparent parts of the file get rendered white, masking the content beneath. (Of course I applied your patches before doing this.)

**Comment by adrhill** [comment]
I have the same issue on `2.15.0.1067-patch_38.2.01-0-gdbdbd93`.
