### ISSUE TITLE
Bookmarks break when inserting/deleting pages

### ISSUE THREAD

**Issue by iHnR** [ddvk/remarkable-hacks#484]
I noticed that my bookmarks get shifted when I insert or delete pages before them (both in notebooks and pdf's). 

I imagine it's a difficult problem to solve as the bookmarks are probably just stored by page number? Maybe it's possible to catch a page insert/delete and edit bookmark page numbers accordingly?

**Comment by Kenivia** [comment]
Seems like a duplicate of https://github.com/ddvk/remarkable-hacks/issues/179

**Comment by iHnR** [comment]
@Kenivia Yep, I didn't see catch that somehow. The situation changed a bit though since the inclusion of note pages in pdfs, which was one of the biggest missing features for me as I like to take notes while reading textbooks. Now that this is included, the bookmarks (which I previously used a lot) have unfortunately become basically useless for me.
