### ISSUE TITLE
3.0 Beta

### ISSUE THREAD

**Issue by regrubtaf** [ddvk/remarkable-hacks#485]
I know there are no patches for beta software but I wanted @ddvk and any other Devs to know that there seems to be big changes on the horizon that, at the very least will change the default swipe and gesture functions while a file is open.  This is a link to some of the new navigation functions. I can see that both one and two-finger up and down swipes have been repurposed for new native functions.  There is also a new native gesture for undo and redo. Hopefully, these changes don't disable or complicate the great functions in the patch/hacks.

https://support.remarkable.com/s/article/Navigating-our-new-pages-beta-3-0

**Comment by ddvk** [comment]
thanks
