### ISSUE TITLE
2.15.1.1189 Released

### ISSUE THREAD

**Issue by Tridens92** [ddvk/remarkable-hacks#490]
Version 2.15.1.1189 has been released (at least for rM1).  Giving all al "head's up" before you update and lose your hacks until @ddvk releases compatible version.  Just a reminder that you can avoid installing an unsupported update by briefly enabling automatic updates, letting the download start to see which version is offered, and disable automatic updates again before it installs.

**Comment by TobiasHeinicke** [comment]
Given the fact that this seems to be the last release before 3.0, I personally would love to see a new release of the hacks. Also (given that this is my first post) thanks for the hacks @ddvk - they really are a game changer!

**Comment by avillavecesn** [comment]
I second TobiasHeinicke here. I only got my rM2 two weeks ago, and it updated to 2.15.1.1189 before I even had heard of @ddvk hacks! I truly would like to try them! (Thanks)

**Comment by ddvk** [comment]
was busy trying to figure out the new notes format, will do it in the next days

**Comment by regrubtaf** [comment]
@HawthornThistleberry They weren't that specific, but I think the cloud access issue is only a problem if you have OS 2.12 or lower. See this page for more info. 

https://support.remarkable.com/s/article/Improved-sync?utm_source=sfmc&utm_medium=email&utm_campaign=2022_10_14_SYNC_1.0_V1&utm_term=https%3A%2F%2Fsupport.remarkable.com%2Fs%2Farticle%2FImproved-sync&utm_id=39359

**Comment by hektor-jr** [comment]
Morning!
I mistakenly thought there was a hack out for the new RM version and upgraded.... sigh....    @ddvk  Any guesses as to when the hacks will be ready for 2.15?

**Comment by hektor-jr** [comment]
Thanks!

**Comment by HawthornThistleberry** [comment]
Hopefully this was an easy-to-fix stupid mistake on my part...

- Looks like I hadn't updated since 2.11 so I figured I'd better update.
- Tried to follow the instructions to install the latest patch but after doing it, the version info was not changing.
- Tried specifying the patch number in the magic line but it didn't take.
- So I thought maybe I needed to update the rm way first and patch over that, so I tried that.
- However now that I'm running the latest rm 2.15.1.1189 the SSH command won't connect doing the exact same things that worked fifteen minutes ago. Connection immediately closes. Verbose mode shows debug1: expecting SSH2_MSG_KEX_ECDH_REPLY.
- Tried with web interface on and off. When on, web interface works.

What am I missing? Or has reMarkable, despite the GPL terms, blocked SSH into it?

**Comment by ddvk** [comment]
> Hopefully this was an easy-to-fix stupid mistake on my part...
> 
> * Looks like I hadn't updated since 2.11 so I figured I'd better update.
> * Tried to follow the instructions to install the latest patch but after doing it, the version info was not changing.
> * Tried specifying the patch number in the magic line but it didn't take.
> * So I thought maybe I needed to update the rm way first and patch over that, so I tried that.
> * However now that I'm running the latest rm 2.15.1.1189 the SSH command won't connect doing the exact same things that worked fifteen minutes ago. Connection immediately closes. Verbose mode shows debug1: expecting SSH2_MSG_KEX_ECDH_REPLY.
> * Tried with web interface on and off. When on, web interface works.
> 
> What am I missing? Or has reMarkable, despite the GPL terms, blocked SSH into it?

remove the ~/.ssh/known_hosts file

**Comment by HawthornThistleberry** [comment]
Ah thanks, that did it! Will remember next time.

**Comment by Tridens92** [comment]
Thanks for updating the hack, @ddvk !

**Comment by NilsIrl** [comment]
Thank you so much @ddvk ❤️

**Comment by avillavecesn** [comment]
Thanks!!! For this amazing hack! I could finally try it! :)

**Comment by avillavecesn** [comment]
Hi @ddvk - the hack is great. The only part that seems strange to me is the pen-switching gesture. For some reason, it only works sometimes. I reinstalled the hack but for some reason the pen-switching gesture only seems to work sometimes, and often has to be repeated. Am I doing something wrong? Thanks!

**Comment by Eeems** [comment]
@ddvk this can probably be closed
