### ISSUE TITLE
Allows use of "Undo" button in Zen mode

### ISSUE THREAD

**Issue by AdamSLevy** [ddvk/remarkable-hacks#5]
Zen mode is a fantastic improvement and what the RM has been missing for a long time. Thank you for that and all your amazing patches!

I was wondering if it might be possible to add a feature to zen mode to allow a quick undo, or several quick undos. Perhaps a double press of the left button could cause an undo and a single slightly longer press toggle the writing implement.

What do you think?

**Comment by ddvk** [comment]
how about long press, 3 undos, it's 600ms

**Comment by AdamSLevy** [comment]
You mean that a long press would cause 3 undo actions? Not just one?

Personally this wouldn't be ideal for me because I typically only need to undo once to erase my last entire word since I write in cursive.
I would personally rather have the long press switch my writing tool and the quick press perform an undo.
Thinking about it more, perhaps a quick double click of the button for an undo would be easier to work with.

Just throwing out ideas. Any of these would be useful to me. 3 undo steps is a bit much for cursive writing though.

**Comment by ddvk** [comment]
will see if double click is doable

**Comment by ddvk** [comment]
currently a long press does undo, double clicks are off the table for now
