### ISSUE TITLE
Menu icons overlay

### ISSUE THREAD

**Issue by thawker94** [ddvk/remarkable-hacks#50]
Hello,
not sure if I am trialling it wrong but have tried different patches. When I test it out, the menu loads as normal, with then the remarkable-hacks menu over the top of it, making there be effectively two menus that interfere with one another. All the features seem to work fine, but because two menus appear to load, it often ends up reverting to the remarkable menu option.

If this doesn't make sense, I can upload photos to display what I mean.

Many thanks

**Comment by dstango** [comment]
Are you in portrait or landscape mode?
Right hand or left hand mode?

**Comment by thawker94** [comment]
> Are you in portrait or landscape mode?
> Right hand or left hand mode?

hello, thanks for responding. I am in portrait mode, right hand mode. It also does the same in landscape

**Comment by dstango** [comment]
works for me -- maybe share some pictures ...

**Comment by dstango** [comment]
Might it be there's a difference between pdf files and regular notebooks? I noticed for pdf files the additional rm hacks menu missing in the most recent version.

**Comment by thawker94** [comment]
Hello,
Apologies for the delayed response. Thank you for getting back to me. Please find attached some photos of the overlay I'm describing. If you need more, feel free to ask.

Kind regards

![IMG_20200708_203551](https://user-images.githubusercontent.com/64670770/86962776-588c5d00-c15b-11ea-9acb-4def53753e64.jpg)
![IMG_20200708_203603](https://user-images.githubusercontent.com/64670770/86962785-5a562080-c15b-11ea-83ea-a7572051b93c.jpg)
![IMG_20200708_203728](https://user-images.githubusercontent.com/64670770/86962788-5c1fe400-c15b-11ea-9a21-997a960f3472.jpg)


to ask.
Kind regards
![IMG_20200708_203748](https://user-images.githubusercontent.com/64670770/86962764-53c7a900-c15b-11ea-89ca-f568bdfd2fb9.jpg)
![IMG_20200708_203537](https://user-images.githubusercontent.com/64670770/86962772-562a0300-c15b-11ea-8183-b187df1d0bbc.jpg)

**Comment by dstango** [comment]
I can't reproduce it on my device.
Did you try uninstalling and reinstalling the hacks?
Which release are you on? I'm on 2.2.0.48.
Do you have installed any other hacks on your rm that might interfere?

**Comment by thawker94** [comment]
I'm also running on 2.2.0.48. The only other hack I have installed is draft launcher, is this one known to interfere? I can try resetting the remarkable entirely and starting from scratch with it and then working to figure out what is causing the issue. Thanks for your help thus far

**Comment by thawker94** [comment]
Hello, I reverted my remarkable to factory default, and it is the draft launcher that is interfering with your hack. This is unfortunate as I quite like the draft launcher but prefer the features you have added with this hack. I might try looking into what is causing the conflict/interference. Let me know if you have any advice/understanding as to what the cause may be. Otherwise, thank you for your help.

**Comment by dstango** [comment]
Hi,
great you figured it out!
I think we'll have to wait for @ddvk to see what can be done. I'm just an enthusiastic user like you and have no access to the code base.
Maybe the author of draft launcher has an idea?

**Comment by ddvk** [comment]
you have 2 instances if xochitl running.

install the hack first, then follow draft instructions

**Comment by thawker94** [comment]
Ah that makes a lot of sense. Thank you for your help.
