### ISSUE TITLE
new

### ISSUE THREAD

**Issue by jayrich5807** [ddvk/remarkable-hacks#503]
I think that would be an unreasonable request.  I just want to ask if there is a possibility.  Is there a way to connect to nas with webdav in ReMarkable?

**Comment by ddvk** [comment]
you have to use your own cloud e.g rmfakecloud, as everything goes through the cloud

**Comment by jayrich5807** [comment]
Does rmfakecloud support automagic ?

**Comment by Eeems** [comment]
> Does rmfakecloud support automagic ?

I would recommend going to that repository and reading it's documentation instead of asking the question here.
