### ISSUE TITLE
rM2: Version 20221208102714 not supported yet

### ISSUE THREAD

**Issue by r41d** [ddvk/remarkable-hacks#508]
I recently got a used reMarkable 2 and got me a LAMY Stylus.
Unfortunately when trying to run the patch script it tells me that
```
The version the device is running is not supported, yet. 20221208102714
```
The software version that is reported in the UI on the rM2 is `Version 3.0.4.1305`.
How can I assist in helping with an update?

**Comment by Eeems** [comment]
Duplicates #496 (and #507 #505 #501 #499)

**Comment by OrbXXX** [comment]
Hello, I have the exact sale problem as above, yet I dont understand the "answer" at all. Could anyone help please??

**Comment by Eeems** [comment]
> Hello, I have the exact same problem as above, yet I dont understand the "answer" at all. Could anyone help please??
> 
> -After a bit of time, I may have found something wroten by Mr Eeem, it seeems. Looking forward to it. And yet.. nothing.. Is it at least possible on this version ? (3.0.1.1305) ..
> 
> Would it in any way be related to this 20221208102714 not being supported . Actually it seems so. Sorry for disturbance

This is a duplicate issue. Please see #496 for the current status of this. You are correct that this is not a supported version yet.
