### ISSUE TITLE
Bookmark bug

### ISSUE THREAD

**Issue by manuelinux67** [ddvk/remarkable-hacks#51]
Hi. Can U please fix this? If I bookmark a page like the third one with a “C”, and then insert another page in front of it, my bookmark “C” will stay on the third page, which is now “E”. And so I loose my bookmark for  the page “C”

![image](https://user-images.githubusercontent.com/67714586/86295777-a521e680-bbf7-11ea-9542-905c93ca48e0.jpeg)

![image](https://user-images.githubusercontent.com/67714586/86295797-b10da880-bbf7-11ea-96e6-2bd8df95c407.jpeg)

![image](https://user-images.githubusercontent.com/67714586/86295823-bd920100-bbf7-11ea-80a8-c5f9f3f8c8c6.jpeg)

![image](https://user-images.githubusercontent.com/67714586/86295857-cda9e080-bbf7-11ea-93ea-cce10683d514.jpeg)

**Comment by manuelinux67** [comment]
From FB discussion: I can bookmark pages and give every bookmark a name. But the bookmark doesn’t stuck to that specific page. Therefore the bookmark remains at the specific page number (in this case the third page). If I move the fifth page (with an E written on it) in front of the one where I wrote a C, the third page results to be the one with the E written on it. My page with the C loses its bookmark and the letter E becomes a bookmark. I don’t won’t it like that. I need the bookmark “C” to remain on the page with the letter C even if other pages get inserted before that one.

**Comment by ddvk** [comment]
atm bookmarks are not connected with the page, just with a page number

**Comment by ddvk** [comment]
sorry, atm no idea how to fix it
