### ISSUE TITLE
Firmware 2.15.1.1189 for Remarkable 1

### ISSUE THREAD

**Issue by haydensp** [ddvk/remarkable-hacks#510]
Hey team,

I honestly hate the new update 3.*** that rolled out a little while ago. 

I want to downgrade to the firmware 2.15.1.1189 so I can get @ddvk's hacks back since they're so great, but I can't find the file anywhere!

Does anyone have a version of the firmware that they could send me? or know somewhere I can download it from?

Cheers!

**Comment by Eeems** [comment]
Sharing the firmware would be breaking the ToS.

**Comment by Eeems** [comment]
I would recommend looking into using this though: https://github.com/Jayy001/rm-update-helper

**Comment by martin-braun** [comment]
@Eeems Thanks for sharing that, I probably update to 2.15.1.1189 on my rm2, because version 3 will probably take a lot of time to get the hacks anyways.

Although, the rm-update-helper is only for rm2, not rm1.

**Comment by haydensp** [comment]
Yea, I appreciate that! Unfortunately the creator of RM Update Helper has yet to release a version that works with the RM1, so here I am. I'm aware that sharing the firmware breaks the terms of service, I guess I was just hoping someone would be willing to help me out 🤙 I'll keep hoping!

**Comment by Eeems** [comment]
@ddvk can you close this since it's not actually an issue with this repository, and is asking for something that breaks ToS?

@haydensp I'd recommend opening an issue on the rm-update-helper repo asking for help on how to get it to pull rM1 updates instead.
