### ISSUE TITLE
Help! I used the switch.sh to swap for my previous version and now it's stuck on boot.

### ISSUE THREAD

**Issue by hgk8769789** [ddvk/remarkable-hacks#514]
I used the switch.sh on my remarkable 2, and now it's stuck on "is starting" after a few seconds it refrashes the screen and tries again. I can't ssh into it too. please help

**Comment by ddvk** [comment]
did you update it once, what was the previous version?

**Comment by hgk8769789** [comment]
> did you update it once, what was the previous version?

Yes I updated it to 2.5.0.27. I am not sure what was the previous version, I just bought the remarkable, in the setup I choose not to update to 3.0 version. if that helps.

**Comment by Eeems** [comment]
To clarify, you did run through an update process, or you did not update? The switch script script from the [remarkable-update repo](https://github.com/ddvk/remarkable-update) only switches to the other root partition, but doesn't check that it actually has anything installed. If you didn't run through an update, there is a chance that the partition is empty, and you'll be stuck in a reboot loop as there isn't anything there to install.

If that's the case, you'll need to go through the [remarkable2-recovery](https://github.com/ddvk/remarkable2-recovery) process.

**Comment by hgk8769789** [comment]
> did run through an update process

Yes I updated.

**Comment by hgk8769789** [comment]
> To clarify, you did run through an update process, or you did not update? The switch script script from the [remarkable-update repo](https://github.com/ddvk/remarkable-update) only switches to the other root partition, but doesn't check that it actually has anything installed. If you didn't run through an update, there is a chance that the partition is empty, and you'll be stuck in a reboot loop as there isn't anything there to install.
> 
> If that's the case, you'll need to go through the [remarkable2-recovery](https://github.com/ddvk/remarkable2-recovery) process.

I have a question. how would I do the recovery progress if I can't turn off my remarkable? should I pull the battry out or something

**Comment by Eeems** [comment]
https://remarkablewiki.com/faq/hard_reset
Hold the power button for 10 seconds. The screen will **_not_** update.

**Comment by hgk8769789** [comment]
> https://remarkablewiki.com/faq/hard_reset Hold the power button for 10 seconds. The screen will **_not_** update.

right, if I hold the button it stays on the "is starting" if I hold it will I be able to do recovery?

**Comment by Eeems** [comment]
It'll power off the device if it's on, and the screen will stay in whatever state it was in. So yes you would be able to go through the rest of the recovery process.

**Comment by hgk8769789** [comment]
> ight, if I hold the button it stays on the "is startin

It doesn't power it off

**Comment by Eeems** [comment]
Again, the screen will _**not**_ update, so you will have no way of knowing that it powered off.

**Comment by hgk8769789** [comment]
oh right ok.

**Comment by hgk8769789** [comment]
I have to do it by recovery right? can I use an altarnitve method?
