### ISSUE TITLE
Zoom not working anymore

### ISSUE THREAD

**Issue by ainou** [ddvk/remarkable-hacks#52]
After applying the patch on the latest firmware you're unable to use the small window on the right to choose the area to zoom and neither change the zoom percentage.

**Comment by torwag** [comment]
It is working for me. Can you elaborate on your test setting? Did you use a PDF or a Notebook, which software version did you test?

**Comment by torwag** [comment]
I can't reproduce this being on 2.2.0.48 using patch 05_1-30-ga4e2c2d.
It works with the pen not with the touch. Maybe that is the standard feature, I am not sure about it.

**Comment by ainou** [comment]
You're right, using the pen it works indeed. Sorry for misleading you but I never used the pen before for that.

**Comment by darthoctopus** [comment]
I can confirm that it works with touch without the patch applied. Is there a way to re-enable this functionality?
