### ISSUE TITLE
Corner Bookmark disable

### ISSUE THREAD

**Issue by sukulent** [ddvk/remarkable-hacks#524]
Hey, I have just a little feature request for a toggle for the bookmarks corner. I find myself often laying my hand over the corner and triggering it (or the rename menu) when I don't want to. Just the activation, the visual indicator is pretty :D
Than it would be logical to put another activation button into the bookmarks menu so when the corner activation is turned off, one can still bookmark pages.

Installing your hacks was the first thing I did after I got my remarkable and I can't image living without them, thank you very much!

**Comment by ddvk** [comment]
there is an option to disable them, but it hides the indicator iirc
