### ISSUE TITLE
Time / clock

### ISSUE THREAD

**Issue by shreevatsa** [ddvk/remarkable-hacks#53]
It would be nice to have a clock (a display of the current time) available somehow. For me, needing to know the time (when to return from a walk for example) is the main thing that requires me to take my phone with me in addition to the Remarkable. 

I see that such a feature is already available with your https://github.com/ddvk/remarkable-touchgestures but the two seem to interact together in unpredictable ways (sometimes both events fire, i.e. swiping down will both show the clock and hide/unhide the menu, or swiping left/right turns *two* pages instead of one).

**Comment by spinningrust** [comment]
Showing the current time on the sidebar would be very nice indeed.

**Comment by Tridens92** [comment]
Any chance we could get a toggle to turn off the clock? I personally don't like the tyranny of the clock when I'm doing deep mind work.  Thanks for considering this and for your great hack.

**Comment by dstango** [comment]
We need some documentation how to change the time zone for linux-tourists like me ;-):
* look up available time zones:
  ls /usr/share/zoneinfo/

* change time zone, e.g. for my time zone (Germany), as Europe/Berlin is not available:
    timedatectl set-timezone Europe/Paris

**Comment by ddvk** [comment]
you can copy the zone file from any linux distro... could be scripted

**Comment by ddvk** [comment]
> Any chance we could get a toggle to turn off the clock? I personally don't like the tyranny of the clock when I'm doing deep mind work. Thanks for considering this and for your great hack.

long press on clock

**Comment by Tridens92** [comment]
Hi, ddvk.  Thanks for the answer re: long press of the clock to turn it off.  However, I don't seem to be able to get this to work. No matter how carefully/accurately I press on the clock with the marker, it always activates the notebook button above the clock.  Can you advise?  Running 2.2.0.48, Patch 10.06 .

Thanks!

**Comment by ddvk** [comment]
probably in a later patch

**Comment by Tridens92** [comment]
The only newer one I'm aware of is the patch for the rm2, and I have an rm1.  I'm assuming I can't use the rm2 patch?

**Comment by Tridens92** [comment]
As of this morning, I was running the latest patch for rm1, but I see a new version has been posted for rm1 since.  I'll try that.

I'm assuming we can't/shouldn't run the rm2 patches on the rm1?

**Comment by ddvk** [comment]
yes, rm1 and rm2 sw is not the same

**Comment by Tridens92** [comment]
Solved with version 10.07.  Thanks so much!

**Comment by jackgca** [comment]
Is there any way to change the clock to use 12 hour time?

**Comment by Tridens92** [comment]
Subtract 12.  :)  Just kidding.  That's a good question/request.
