### ISSUE TITLE
Archive this repository

### ISSUE THREAD

**Issue by martin-braun** [ddvk/remarkable-hacks#532]
I think it is clear that this project has come to an end. It's fine, I won't complain, we had good times with it and it's time to move on. Please mark this repository read-only / archived, so it's clear this is not being worked on anymore.

Farewell, thanks for your service @ddvk

**Comment by dreadful-brain** [comment]
Thanks @ddvk, you showed us what is possible with reMarkable and I loved your hacks!

**Comment by ddvk** [comment]
I haven't given up yet

**Comment by katiebobus** [comment]
You're the GOAT!

**Comment by jacob414** [comment]
Never give up. It ain't over till it's over and all that. @ddvk  you're a hero.

**Comment by AlloryDante** [comment]
@ddvk You're the best. Today was the last day I've used your mods. Its time to upgrade to v3. I've been using your mods since I got the tablet AKA since the release of it. You really did make an inpact.

**Comment by StarNumber12046** [comment]
> @ddvk You're the best. Today was the last day I've used your mods. Its time to upgrade to v3. I've been using your mods since I got the tablet AKA since the release of it. You really did make an inpact.

If you want to keep something like it, use remarkable hacks, they offer the same - if not more - functionality
