### ISSUE TITLE
Stuck at "reMarkable is starting" screen after removal

### ISSUE THREAD

**Issue by lemonlemming** [ddvk/remarkable-hacks#535]
Was having issues syncing (kept getting error 400 bad request) so I tried to remove remarkable hacks using the listed instructions under factory reset (stopped xochitl, copied correct version back over, restarted xochitl)

```
reMarkable: ~/ systemctl stop xochitl
reMarkable: ~/ rm -fr .cache/remarkable/xochitl/qmlcache/*
reMarkable: ~/ ls
bootstrap                           koreader-remarkable-v2020.05.zip
entware_install.sh                  log.sdr
koreader                            log.txt
koreader-remarkable-v2020.03.2.zip  log.txt.old
koreader-remarkable-v2020.05.sdr    plato-media
reMarkable: ~/ cd ..
reMarkable: /home/ ls
lost+found  rmhacks     root
reMarkable: /home/ cd rmhacks
reMarkable: /home/rmhacks/ ls
patch.sh              patch_17.1.10         xochitl.22048
patch_03              patch_39.1.01         xochitl.25027_rm1
patch_08              xochitl.2113          xochitl.patched
patch_10.09           xochitl.21511189_rm1
reMarkable: /home/rmhacks/ cp /home/rmhacks/xochitl.21511189_rm1 /usr/bin/xochitl
reMarkable: /home/rmhacks/ systemctl start xochitl
```

Device was functioning normally on stock xochitl but was still getting sync error so proceeded with factory reset

Now device is stuck on displaying "is starting" page. 
I can restart the device by holding the power button 10s then pressing for 2s, screen will flash black then goes back to the 'is starting' screen but stays stuck there.

I did also have koreader installed at one point
I'm unable to ssh into device via usb address or most recent network addresss
Battery is charged

Any advice?

**Comment by Eeems** [comment]
https://remarkable.guide/faqs.html#is-it-safe-to-factory-reset-my-device

Since you had koreader (and rm2fb by extension if you are on a rM1) installed, you put your device into a broken state by factory resetting the device. This would not be an issue related to this repository.

Since you are unable to ssh in, you will need to perform emergency recovery: https://remarkable.guide/tech/recovery.html

**Comment by lemonlemming** [comment]
Ok makes sense, will read up on it. thank you
