### ISSUE TITLE
Feature Request: More GotoPage Features

### ISSUE THREAD

**Issue by torwag** [ddvk/remarkable-hacks#55]
Relative Goto pages:
Using a minus (it is their but I do not see the use for it) or a plus sign in front of a number moves X pages back- rep. forward.
Goto previous page:
Sometimes you look something up and want to go back to the previous page after that.
Like dial in page 10... read about something and with a gesture or single keypress, go back to the inital page.
Preview Goto page. If a number was dialed it would be nice to have a "preview button" to look if the page was right without triggering e.g. page switch, page numbers, previous pages variables, etc. if it is right a final "GO" would do the normal job. That would allow people to jump to the page which might be close to what they are looking for and adjust it from there.
Alternatively, a "Go to page overview" which centers around the dialed in number might be a nice alternative.

**Comment by Tridens92** [comment]
I would love to have a "Go to Last Page" button (as in the last page in the notebook, not the last page visited/history).  That is something I do frequently, and is a feature of readers like Kindle.  A "Go to First Page" would be nice to, but seems less important.

If space is at a premium, I'm not sure I understand the value of the "Set" button.  Given one can use the backspace/delete button it seems redundant.  Maybe that button could get replaced with "Go to First Page" (or "Go to..." submenu, with "First, Last, etc.)?

I'm also not sure I understand what the "minus" key is for.  Can someone clarify?

Love this hack...thanks again!

**Comment by dstango** [comment]
Goto first/last page of document is a accomplished by a long press on the left/right button respecitvely.

**Comment by Tridens92** [comment]
dstango, 

Thanks, I'd forgotten that feature!  Of course, when people receive the RM2 (won't be me, as I'm left-handed), those buttons are going away, so a software go to first/last will still be helpful.

**Comment by torwag** [comment]
The readme needs some updates on this.
If you have a PDF which starts with some preamble, some table of content list, list of figures, remarks of the author, credits, copright-remarks and some other pages, it is likely that is starts to count the acutal page of the content at some later point. E.g. the bookpage 30 is labeled as page 1. 
If you read now the table of content or within the text a page number is referred and you want to go to that page, lets say 135 you would need to count that the page with the label 135 is actual the bookpage 135+30=165. This is heavily confusing and cumbersome.
The set button sets the dialed in number as first page. In the example you would enter 31 and press set. From there on, dial in go-page number 2 is the actual page labeled as number 2 and so on. It is in sync now. page number 0 would then be the last page of the preamble, page number -1 would be the next to last page of the preamble and so on.
That is the reason we have a minus there, and we have Set and Rst (Reset).

**Comment by StLa1** [comment]
> Sometimes you look something up and want to go back to the previous page after that.
> Like dial in page 10... read about something and with a gesture or single keypress, go back to the inital page.

You can achieve this by pressing the <- icon once you're in page 10

**Comment by fmagin** [comment]
I would actually add the feature request that the "set" button allows setting the _current_ page instead of the first. This value doesn't seem to be saved if the document is changed/closed (which is another issue if switching between docs with the two finger swipe gesture), and I quite like it and use it often. E.g.  something referencing the pages "42-45" in some book or document, while referring to the true page number  (i.e. printed on that page) instead of the page number of the PDF. 

So if your document has a 10 page preamble and the true "Page 1" is at PDF page 11, you currently have to type 11 and then hit `set`. Which is fine if you already know that the true Page 1 is at PDF page 11. But if you are in some document, possibly only even excerpt of a journal where the PDF page 17, has the true page number 273, the calculations to set the page indexing correctly are cumbersome. Instead just typing "273" and hitting `Set` should be enough to store the information that the current PDF page is the true page 273 and the rest gets calculated automatically. I am not sure if this is harder than it sounds because getting the current page number isn't trivial, but this is the only problem I can imagine. The rest is just `first_page = 1 + current_pdf_page - input` and using this with the existing logic instead of the user input.

**Comment by ddvk** [comment]
> I would actually add the feature request that the "set" button allows setting the _current_ page instead of the first. This value doesn't seem to be saved if the document is changed/closed (which is another issue if switching between docs with the two finger swipe gesture), and I quite like it and use it often. E.g. something referencing the pages "42-45" in some book or document, while referring to the true page number (i.e. printed on that page) instead of the page number of the PDF.
> 
> So if your document has a 10 page preamble and the true "Page 1" is at PDF page 11, you currently have to type 11 and then hit `set`. Which is fine if you already know that the true Page 1 is at PDF page 11. But if you are in some document, possibly only even excerpt of a journal where the PDF page 17, has the true page number 273, the calculations to set the page indexing correctly are cumbersome. Instead just typing "273" and hitting `Set` should be enough to store the information that the current PDF page is the true page 273 and the rest gets calculated automatically. I am not sure if this is harder than it sounds because getting the current page number isn't trivial, but this is the only problem I can imagine. The rest is just `first_page = 1 + current_pdf_page - input` and using this with the existing logic instead of the user input.

this is actully a nice idea (and belongs to the #38) , don't know if it will be intuitive enough

**Comment by ddvk** [comment]
> I would actually add the feature request that the "set" button allows setting the _current_ page instead of the first. This value doesn't seem to be saved if the document is changed/closed (which is another issue if switching between docs with the two finger swipe gesture), and I quite like it and use it often. E.g. something referencing the pages "42-45" in some book or document, while referring to the true page number (i.e. printed on that page) instead of the page number of the PDF.
> 
> So if your document has a 10 page preamble and the true "Page 1" is at PDF page 11, you currently have to type 11 and then hit `set`. Which is fine if you already know that the true Page 1 is at PDF page 11. But if you are in some document, possibly only even excerpt of a journal where the PDF page 17, has the true page number 273, the calculations to set the page indexing correctly are cumbersome. Instead just typing "273" and hitting `Set` should be enough to store the information that the current PDF page is the true page 273 and the rest gets calculated automatically. I am not sure if this is harder than it sounds because getting the current page number isn't trivial, but this is the only problem I can imagine. The rest is just `first_page = 1 + current_pdf_page - input` and using this with the existing logic instead of the user input.



> I would love to have a "Go to Last Page" button (as in the last page in the notebook, not the last page visited/history). That is something I do frequently, and is a feature of readers like Kindle. A "Go to First Page" would be nice to, but seems less important.
> 
> If space is at a premium, I'm not sure I understand the value of the "Set" button. Given one can use the backspace/delete button it seems redundant. Maybe that button could get replaced with "Go to First Page" (or "Go to..." submenu, with "First, Last, etc.)?
> 
> I'm also not sure I understand what the "minus" key is for. Can someone clarify?
> 
> Love this hack...thanks again!

that's what the L bookmark is for :>

**Comment by ddvk** [comment]
I think all the use cases have been covered (jumb forth, back) + relative page numbers
