### ISSUE TITLE
Patch release naming

### ISSUE THREAD

**Issue by torwag** [ddvk/remarkable-hacks#56]
Hi,
first thanks for all the work.
I found that more and more discussions about those patches appear and that is generally a good thing. However, most of the time people refer to the patch number of the (then) current firmware version. This does not help if you start to read about it a few month later, as the firmware version might have changed in between. Thus patch 6 mentioned in the thread might be far older now compared to patch 1 of the new firmware.
It might be a good idea to come up with a versioning scheme to refer to patches independent of the firmware number. e.g. Major increments whenever the firmware changes, minor increments whenever the patch evolves.  This gives us.
3.1, 3.2, 3.3, 4.0, 4.1, 4.2, 5.0 Whereas the *.0 numbers are always just the last patch ported to the new firmware.
Just my two cents ;)

**Comment by ddvk** [comment]
i'll try to stick to a scheme.
