### ISSUE TITLE
Feature request: toggle last two used pens (alternatively, shortcut for highlighter)

### ISSUE THREAD

**Issue by BernhardWenzel** [ddvk/remarkable-hacks#59]
I usually use three tools when reading: a pen, a highlighter and an eraser. The Zen mode is awesome for switching between pen and eraser, would it be possible to add another shortcut that allows me to switch between pen and highlighter? Ideally, that shortcut would remember the last two used pens. If that is not possible, a direct shortcut for highlighter would do the trick as well.

Thanks for your work, the hacks are the main reason I bought the remarkable (if someone from the company reading this, please hire this person!)

**Comment by spinningrust** [comment]
That would be awesome!

**Comment by kesslerr** [comment]
Thumbs up, they should hire you immediately ! ;)

And thumbs up for this feature, that would be just great to switch between marker, pen, and eraser.

**Comment by chimpdude** [comment]
Oh my goodness, +1000 for this.  I also would love this feature, as I often use my RM1 to read technical papers and go between a pen to circle things and a highlighter to highlight important text. Opening the menu and switching, then closing the menu, then opening again to switch back, then closing...it's a rather cumbersome process.

In Zen mode, I believe the right button currently does nothing, correct? @ddvk could the right button in Zen mode become a toggle for the two most recently used pens?

**Comment by ddvk** [comment]
you would probably press it by mistake

but i will add it and see how it goes

**Comment by ddvk** [comment]
ok done

**Comment by BernhardWenzel** [comment]
works like a charm, this is great, thank you so much!

**Comment by kesslerr** [comment]
This is the best feature! Thanks so much!

**Comment by spinningrust** [comment]
Wow, this is fantastic! Thanks a lot: the RM1 starts to be a really awesome device to read and annotate PDFs! :+1:

**Comment by Tridens92** [comment]
Agreed.  This works swimmingly.  All of this button functionality makes me all the more convinced to stick with my rM1 and pass up the rM2!

**Comment by chimpdude** [comment]
What the others said! Wow, what a simple, yet extremely useful feature. Thanks times a million.

@BernhardWenzel @ddvk I'd say this issue could be closed now, seems pretty much resolved to me.
