### ISSUE TITLE
Quick switch to most recent document using quick double click on home button

### ISSUE THREAD

**Issue by AdamSLevy** [ddvk/remarkable-hacks#6]
The Recent Files menu is super convenient for switching between documents quickly. It would be awesome if a quick double click of the center home button would switch you to the most recently viewed document.

**Comment by ddvk** [comment]
i'll see if i  can get double clicks to work without screwing the rest. do you think it is way better than long press + first entry tap?

**Comment by digital-tinta** [comment]
> i'll see if i can get double clicks to work without screwing the rest. do you think it is way better than long press + first entry tap?

Hi ddvk. Thanks for implementing "double finger swipe down" as a quick document switcher. However, in landscape mode, it's a "double finger right-to-left swipe". I'm wondering if you could fix this "bug". 
The same applies to "double finger swipe up" to close a document.
Thanks.

**Comment by ddvk** [comment]
yeah, i ll fix it, thanks for the feedback

**Comment by ddvk** [comment]
closing this issue, i won't be implementing button double clicks
