### ISSUE TITLE
Feature request: use lamy pen to toogle between pen and highlighter. 

### ISSUE THREAD

**Issue by spinningrust** [ddvk/remarkable-hacks#60]
Hi.

First, I'd like to thank you for your work, remarkable-hacks makes the PDF reading experience really nice on the RM.

Would it be possible to add the ability to switch other tools than between a pen and eraser? Being able to easily switch between fine liner (or mechanical pencil) and highlighter would be what I'd enjoy, and I think many people using their RM to read/annotate documents would find this useful as well.

A custom patch_06 for this use case would be awesome, or even better the ability to customize the behavior in a config file or something similar.

Thanks!

**Comment by ddvk** [comment]
doing custom patches is cumbersome, customization is the way to go

**Comment by ddvk** [comment]
mapped to left/right button in zen mode

**Comment by Tridens92** [comment]
@ddvk Could you please push this update to rm1 2.2.0.48 as well?  Thanks!

**Comment by ddvk** [comment]
covered by switch to last tool
