### ISSUE TITLE
Feature request: Option to disable 'show front page in files overview'

### ISSUE THREAD

**Issue by FlorianKempenich** [ddvk/remarkable-hacks#62]
Hi,

I love your work and your project made my remarkable much easier to use 😃 However there is one aspect that is problematic for me: I really enjoy seeing the **last** page of each notebook in the overview.

Could you add an option somewhere to switch between the two, so people like me can go back to the original implementation? :)

**Comment by ddvk** [comment]
i can add an option

**Comment by dstango** [comment]
It would be awesome if it could be differentiated by document type (lines/pdf/epub) - I like to see the title page of books, but the currernt page in notes ...

**Comment by FlorianKempenich** [comment]
@ddvk That would be awesome 😃
@dstango That's a good suggestion actually. I think it's what would make the most sense as a default actually. I'd choose that option if it were available: Notes I want to see the last page to remember what I was working on, Books I want to see the cover to see which book it is :) PDF . . . I don't know I'd prefer it to be like notes. Either way, the most important for me is the notes I rarely read books or edit pdf anyway :)

**Comment by ddvk** [comment]
done, i'll add an option if someone wants the old behaviour

**Comment by FlorianKempenich** [comment]
Awesome. Thank you ! 😃

**Comment by jimmystridh** [comment]
@ddvk I loved the old behaviour with page 1 being cover for all types - I created a unique page 1 for my recurring notebooks and as such got "icons" for all of them.

I've tried to find references to an option, but perhaps you didn't add such an option yet? Would that be possible to do?

Thanks for adding all these amazing features to the Remarkable
