### ISSUE TITLE
Trouble upgrading to 2.2.0.48

### ISSUE THREAD

**Issue by bliekp** [ddvk/remarkable-hacks#68]
I just upgraded my RM1 to the latest and greatest. Before I had the patch installed for the previous version, worked great.

However, now the upgrade does not work. The steps I took:

* let RM upgrade to 2.2.0.48
* ran the automagic script again
* RM does NOT show the patches on screen. In device settings it says it is on patch05_1_39... 
* flushed the cache. Restarted services. Rebooted. Tried it all.

Nothing....
What am I missing here?

my /home/rmhacks:
`drwxr-xr-x    5 root     root        4.0K Jun 15 10:03 ..`
`-rwxr-xr-x    1 root     root        4.0M Jun 15 10:03 xochitl.2113`
`-rw-r--r--    1 root     root       52.0K Jun 15 10:03 patch_07`
`-rwxr-xr-x    1 root     root        4.0M Sep  5 11:19 xochitl.22048`
`drwxr-xr-x    2 root     root        4.0K Sep  5 11:26 .`
`-rwxr-xr-x    1 root     root        4.0M Sep  5 11:32 xochitl.patched`
`-rw-r--r--    1 root     root       59.8K Sep  5 11:32 patch_10.06`

my /usr/bin/xochitl:
`-rwxr-xr-x    1 root     root       4199412 Sep  5 11:36 /usr/bin/xochitl`

Running a  diff xochitl.patched /usr/bin/xochitl does not show differences...

**Comment by bliekp** [comment]
Stupid me... I forgot to just open a document to check if the menu was patched in there. It is!
So it does work...

What still puzzles me is that it shows patch05_1_39 in settings... Is this correct???

**Comment by ddvk** [comment]
this is just for troubleshooting and tracking bugs. if it works then it is  ok :>
