### ISSUE TITLE
What are the different modes ?

### ISSUE THREAD

**Issue by zelomel** [ddvk/remarkable-hacks#69]
I know how to activate  Zen mode : Left + Right buttons
I know the existence of Reading mode, but I can't find how to activate anymore.
I just discovered M mode : center + right buttons. What does M mean ? Does it replace Reading mode ?

**Comment by ddvk** [comment]
M is reading mode

**Comment by zelomel** [comment]
Oh! I thought it was R.
thank you for your reply.
