### ISSUE TITLE
Back to home screen via a gesture or another ico

### ISSUE THREAD

**Issue by tuanway** [ddvk/remarkable-hacks#7]
Can we add a gesture or button to go back to home screen? Maybe it could be an additional item on the menu button (where we disable swipes exists for example).

I realize this is minor since we do have the home button, but it would be cool to not have to rely on buttons at all. Thanks for this great project.

**Comment by ddvk** [comment]
added a close button in the notebook menu

**Comment by tuanway** [comment]
That works! thanks for getting this out there so quickly.
