### ISSUE TITLE
Feature Request - hack version number on Device Settings page

### ISSUE THREAD

**Issue by Tridens92** [ddvk/remarkable-hacks#73]
Dear ddvk,

I know you've mentioned that the hack version number listed on the Settings --> Device page is just for troubleshooting.  However, it would be really helpful if the actual version number of the hack that's running was also listed there.  This would confirm, when troubleshooting or requesting assistance, that we're reporting the correct running version number, and would be a way of confirming a patch was successfully installed.

Thanks for considering this.

**Comment by ddvk** [comment]
done

**Comment by Tridens92** [comment]
Perfect!  Thanks so much.  Your hack and responsiveness are just fantastic.  Thanks so much for making my daily life with rM so much easier and productive.
