### ISSUE TITLE
Menu link to copyright information is gone :(

### ISSUE THREAD

**Issue by miekemb** [ddvk/remarkable-hacks#75]
On my rM2 I first installed the hacks.
Last Wednesday my rM2 automatically updated, and now the 'About' section is gone from my menu, 
I did not note down the root password (stupid me, I know, to eager to install the hacks, because I really missed the 'Recent files'), and now I can't upload my custom templates anymore. ([see image](https://drive.google.com/file/d/1FMzaDpNDqme_XSekojrgdc7Do2uYnhu8/view?usp=sharing))

I contacted rM support, to see if there is still an option to flash the rM, but they can't provide me with a flashing tool or instructions and advised me to contact you to see if you could help :)

Do you know if it's still possible to put the rM2 in 'upload mode' (pressing the power button and the middle button simultaneously on the rM1)
Or any other way I can fix this?

I'm using Windows 10. 

Kind regards,
Mieke

**Comment by ddvk** [comment]
sorry about that, i removed the faulty patch as soon as it was reported. (also it says in the readme to write the password down)

i dont know how to put the rm2 in recovery mode, and the support told me there is no way, which i doubt.


in the worst case,you can wait for the next official update. 

or if i can find a way to crash the ui multiple times to force it to boot the old version

**Comment by miekemb** [comment]
Yeah, I know about the password, I'm usually very meticulous about these things. Of course the one time I let it slip something goes wrong :p 

No, no help section either.

I'll just wait for the next official update then. I can do without my custom templates for now, missing the Recent files list was much worse ;)

**Comment by miekemb** [comment]
Just received a new update (2.3.1.27) and the menu (with the help section) is back, yay!
