### ISSUE TITLE
Support for update 2.3.1.27

### ISSUE THREAD

**Issue by hirschk** [ddvk/remarkable-hacks#76]
Just got an update. Could you please add support for the hacks? Thanks!

**Comment by Tridens92** [comment]
For which device?  rM1 or rM2?

**Comment by hirschk** [comment]
RM2

**Comment by duckwagon** [comment]
Same for RM1. Version 2.3.0.16.

**Comment by ddvk** [comment]
should be done, just the readme is not updated
