### ISSUE TITLE
Feature request: finger navigation when zoomed in

### ISSUE THREAD

**Issue by hugo-abreu** [ddvk/remarkable-hacks#77]
Hello,

First of all, thank you for all the great work - remarkable-hacks makes the remarkable much more usable. One feature I would love to have would be finger navigation while zoomed in on a PDF (or on a notebook). 

There seems to be a bug with remarkable-hacks, where I can only use the little menu window to choose the zoom selection while using a pen. Could this be reverted so that I can also use finger input?

On top of that, would it be feasible to implement a finger combination (for example a three finger scroll) to be able to directly navigate while zoomed in?

Best regards,
Hugo

**Comment by StLa1** [comment]
Afaik, if you enable Pinch to Zoom you'll be able to move while zoomed using 1 finger

**Comment by hugo-abreu** [comment]
How can I enable pinch to zoom? When I installed the hacks it was already working. Just tried moving with one finger and it didn't work.

**Comment by sethmnielsen** [comment]
You have to enable swipes as well.

**Comment by ddvk** [comment]
swipe when zoomed

**Comment by hugo-abreu** [comment]
Just received newest firmware update, and when I reinstalled the hacks swipe navigation while zoomed worked perfectly! Thx
