### ISSUE TITLE
List View uses generic icons for notebooks instead of reduce-size previews

### ISSUE THREAD

**Issue by Snowflake6** [ddvk/remarkable-hacks#78]
I've been using remarkable-hacks for quite a long time now, and when I got the 2.3 update the first thing I noticed is that the list view of my notebooks has reduced-size previews as icons for each notebook.  Re-installed remarkable-hacks and now i'm back to the generic icons for the notebooks in list view.

Is there a way to keep the reduced-size previews, but still have the other remarkable-hacks?

**Comment by ddvk** [comment]
i'll think about it. i had removed the previews in list mode because they were mostly illegible

**Comment by motusRP** [comment]
Awesome, thanks!  Oh, just realized i'm signed in from work now.  Same person as above.

Yes, the icons are not readable at all, but frequently the shape of the content was enough to identify them visually.  A minor issue, I agree, but I liked it while I was seeing it.  Maybe make it configurable?

**Comment by ddvk** [comment]
it should be fixed now
