### ISSUE TITLE
Zen mode toggle not working as expected

### ISSUE THREAD

**Issue by LukeyBrown** [ddvk/remarkable-hacks#79]
When in Zen mode: The right button switches between the previously selected pen and erase, and the Left switches between the current pen, and the previous pen.

I'd also like to thank you for putting in the work to make this enhancement!

Using patch_12.10 on a rM1, related to #67
Please let me know if you'd like me to record the steps to reproduce.

**Comment by ddvk** [comment]
still did not understand what the problem is

**Comment by Tridens92** [comment]
@LukeyBrown , as far as I understand, this is expected functionality, not a bug.

**Comment by ddvk** [comment]
works as expected

**Comment by LukeyBrown** [comment]
I see that now, I made some assumptions based upon what was rattling around in my own head ;)
