### ISSUE TITLE
Tried to get latest patch, but ran into a segmentation fault

### ISSUE THREAD

**Issue by tuanway** [ddvk/remarkable-hacks#8]
Got a seg fault when trying to get latest patch.  Any ideas?

root@remarkable:~# sh -c "$(wget https://raw.githubusercontent.com/ddvk/remarkable-hacks/master/patch.sh -O-)"
Connecting to raw.githubusercontent.com (151.101.192.133:443)
Disk space seems to be enough
Version 2.1.1.3
Connecting to github.com (140.82.112.3:443)
wget: note: TLS certificate validation not implemented
Connecting to raw.githubusercontent.com (151.101.192.133:443)
patch_02             100% |**************************************************************************************************************************************| 43121  0:00:00 ETA
cleaning up
Trying to start the patched version
You can play around, press CTRL-C when done
**sh: line 125:   402 Segmentation fault      (core dumped) ./xochitl.patched > /dev/null 2>&1
It crashed?
cleaning up**

**Comment by tuanway** [comment]
Just an update, to get around this, I had to mount 
/dev/mmcblk1p3, which seems to contain some a shadow copy of the old files.
I then just copied the backup xochitl back to my main /usr/bin directory and removed all patches from home/root.  After this running the patch works.

**Comment by ddvk** [comment]
i have no idea why it segfaulted. 

/dev/mmcblk1p 2or3 (the alternative partition) contains the previous version (rootfs) and they get switched after every update.

in case you kept the patched segfaulting binary, sha1sum would be  helpfull

i put back the log output in the install script.

**Comment by zelomel** [comment]
Had the same issue.
I had already installed the hacks without patch_03 few days ago (very impressive hacks indeed !), and I wanted to install the latest patch and I obtained the same seg fault.
My rM reboot several times, went back to 2.0.2.0, updated to 2.1.1.3 and after that I can install your hacks.

**Comment by ddvk** [comment]
> Had the same issue.
> I had already installed the hacks without patch_03 few days ago (very impressive hacks indeed !), and I wanted to install the latest patch and I obtained the same seg fault.
> My rM reboot several times, went back to 2.0.2.0, updated to 2.1.1.3 and after that I can install your hacks.

can you mount the other root partition and post the sha1 of xochitl

**Comment by tuanway** [comment]
Seems to work much better on the latest patches.  I think we can close this one.

**Comment by ddvk** [comment]
seems to be resolved
