### ISSUE TITLE
Can I offer some help with UI & Icons?

### ISSUE THREAD

**Issue by LukeyBrown** [ddvk/remarkable-hacks#80]
Love the work you're doing here, and I'd like to offer some assistance. I'm not a great programmer, but pretty handy with graphics applications, vector artwork, layout, and have some experience with UX/UI. 
If you could let me know how I can get my hands on the icon sets, I'd be happy to lend a hand.

**Comment by bongotai** [comment]
@LukeyBrown Great idea! Many times I thought how to better integrate @ddvk hacks UI with Remarkable factory UI. 
There is also a lot to think about how and where options are placed in the UI. 
Difficult tasks to take on your own, but maybe if we are more?
I've found Sketch very practical for this purpose. Do you use this tool?

**Comment by Eeems** [comment]
You should still be able to point to external images for icons instead of sticking with the embedded font.

**Comment by StLa1** [comment]
I can also help for any UI/UX task

**Comment by StLa1** [comment]
> @LukeyBrown Great idea! Many times I thought how to better integrate @ddvk hacks UI with Remarkable factory UI.
> There is also a lot to think about how and where options are placed in the UI.
> Difficult tasks to take on your own, but maybe if we are more?
> I've found Sketch very practical for this purpose. Do you use this tool?

Sketch is good but only on mac. Most popular multi-platform tools for UI/graphic designers are Illustrator, XD, Figma I'd say

**Comment by LukeyBrown** [comment]
Sounds good! Haven't had any experience with sketch, but I've actually got a copy of XD (I know a little bit) and Illustrator (know very well). Found the font file as well!

@bongotai Looks like it's possible to open sketch documents with XD, and from a very quick google, we should be able to convert XD to Sketch. Probably won't be that straight forward, but we could tackle it.

I haven't tried collaborating on a project like this before, so any advice on how we can share and distribute would be welcome.

**Comment by ddvk** [comment]
sure, suggestions are welcome

**Comment by StLa1** [comment]
> Sounds good! Haven't had any experience with sketch, but I've actually got a copy of XD (I know a little bit) and Illustrator (know very well). Found the font file as well!
> 
> @bongotai Looks like it's possible to open sketch documents with XD, and from a very quick google, we should be able to convert XD to Sketch. Probably won't be that straight forward, but we could tackle it.
> 
> I haven't tried collaborating on a project like this before, so any advice on how we can share and distribute would be welcome.
> 
> I was thinking the first port of call would be the writing interface, and then go from there?

XD offers cloud collab so that would be the best choice. But I don't think any UI improvements/revamps are needed and will be needed. Not sure we can do a lot in this project, it's already pretty good when considering the constraints

**Comment by ddvk** [comment]
yes, i think this not needed atm
