### ISSUE TITLE
Tap to change page

### ISSUE THREAD

**Issue by spinningrust** [ddvk/remarkable-hacks#81]
Hi.

Would it be possible to add the ability to "tap" to go to the next / previous page, like it's possible with more ereaders or using koreader? A zone on the screen would be used to change page with a simple "tap" rather than having to swipe (for example bottom/right to go to next page and bottom/left to go to previous page).

Thanks :)

**Comment by computemachines** [comment]
Have you tried using 'reader mode'?
Press the middle and right buttons at the same time

**Comment by Tridens92** [comment]
Yes, reader mode is the answer.  We wouldn't want page turn tapping in modes designed for writing...that would be a nightmare.

**Comment by spinningrust** [comment]
Well the idea was to make PDF reading more comfortable when using the right buttons to switch tools in zen mode.
Couldn't "finger tap" be limited to a small zone and that way not becoming a nightmare when writing (not being activated by a palm touch)?

**Comment by ddvk** [comment]
people are compaling about a thiny X in the upper corner, wherever such a touch area would appear, someone would manage to activate it.
