### ISSUE TITLE
issues about: patch_12.10 fix button rejection 

### ISSUE THREAD

**Issue by kychris** [ddvk/remarkable-hacks#86]
with the latest button rejection, it is pretty easy to tap the home button when writing which is quite annoying sometimes. One way is to disable the buttons, but zen mode toggle pen/eraser won't work in that case. 

Would it be possible to make button rejection a bit longer? or when disabling the buttons, does not disable pen/erase toggle in zen mode?

**Comment by kychris** [comment]
haha it's ok, I figured out that using the remarkable horizontal fixes the issue.

Also speaking of "pen/erase toggling does not work when the pen is near", not sure if you programmed it that way, the action still happens after you lift your pen. So say if someone accidentally hit the left/middle/right button when writing, the action does not immediately happen, once they lift the pen, then the notebook will quit/change pen. This might be an issue for people if their palm touches the button frequently, it was for me at least, not anymore once used horizontally

**Comment by ddvk** [comment]
that is different, this is when the pen is already touching that the buttons get buffered

**Comment by ddvk** [comment]
closing this one
