### ISSUE TITLE
Feature request - Any chance UI could be flipped 180 degrees?

### ISSUE THREAD

**Issue by Tridens92** [ddvk/remarkable-hacks#89]
@ddvk,

I'm wondering if there's any chance that your hack (or a separate one) could flip the display of the reMarkable 180 degrees?  This would provide benefits for both rM1 and rM2 users:

For rM1 -- allows buttons to be at the top, thus avoiding inadvertent presses during writing.
For rM2 -- would allow lefties to have the larger bezel (and grip) on the right side of the display, affording lefties (like me) the same functionality intended by reMarkable's asymmetrical design that right-handed users enjoy.

Thanks for any feedback on both the "doability" and likelihood of such a feature.

**Comment by ddvk** [comment]
the problem is the pen digitizer

**Comment by Eeems** [comment]
One option that would work with the pen digitizer would be to completely flip all the widgets being displayed in Qt itself. That would require extensive changes though, and likely would be very difficult to maintain between versions.

**Comment by ddvk** [comment]
i ve tried that (rotate the root container), writing is ok but when the page is reloaded it is upside down.

**Comment by Tridens92** [comment]
OK, thanks for confirming that there's probably a hardware limitation here.

**Comment by ddvk** [comment]
well, i also want to flip it, but without modifying the kernel if possible

**Comment by ddvk** [comment]
the only hard part is flipping the digitizers coordinates

**Comment by Tridens92** [comment]
That would be fantastic if you could figure it out.  Wish you the best.

**Comment by nov1n** [comment]
@Tridens92 was there any reason for closing this? Maybe we could reopen this ticket to make it easier for others (like me) to find and to track progress?

**Comment by csc5k** [comment]
I (as a lefty) would love to see this feature implemented. Whatever limitations pertaining to how the pen connects to the tablet, I can deal with

**Comment by martin-braun** [comment]
@ddvk maybe reopen it? I think there is a large audience who would appeal to getting this done.

**Comment by jpmvferreira** [comment]
I'm also very interested in this.
If I remember correctly, there is a way to completely invert an X display, right? If so, couldn't we just use that, beneath all of the widgets and whatnot, and obtain the desired result?

**Comment by Noitues** [comment]
For the RM2, the folio keyboard auto flips the display 180 degrees. Wondering if there is a way to trick the RM2 into thinking its in that mode to force the flipped landscape

**Comment by mb1986** [comment]
Perhaps this could help: https://github.com/mb1986/rm-hacks/issues/95. I plan to implement it in a week or two.
