### ISSUE TITLE
Feature request - Auto sleep time and auto power off time setting

### ISSUE THREAD

**Issue by zelomel** [ddvk/remarkable-hacks#90]
Is it possible to implement auto sleep time and auto power off time setting in the setting page ? It is possible to set them with Remarkable Assistant but it could be useful to have it directly in the battery settings page.

Thank you for your work that make my rm1 even more remarkable !

**Comment by ddvk** [comment]
sorry i'll have to disappoint yoo, this is too much effort for something not that is not that often used.
