### ISSUE TITLE
FR: Lamy Pen button double-click to undo

### ISSUE THREAD

**Issue by AdamSLevy** [ddvk/remarkable-hacks#92]
It would be really useful to be able to control more with the Lamy Digital Pen button. Using it for erasing is amazing. However I also find the undo function to be extremely useful. 

Would it be technically possible to register a double-click, or even a triple-click? Tying this action to undo and redo would be really cool.

Thank you for everything you've done for the RM community. You rock!

**Comment by ddvk** [comment]
- someone asked for button double clicks once. 

it is possible in general, but i'm afraid i'll break something else, also it adds some input lag (500ms  is windows standard)


anyway, i'll keep in mind

**Comment by ai212983** [comment]
Also can we have it customizeable? I am not using eraser, but using undo a lot.

**Comment by ddvk** [comment]
so, a ui to change the mode?


the wishes are:

hold to erase 
click to undo
double click to undo
click to toggle erase/pen
hold to select

**Comment by ai212983** [comment]
I would say, ui to change the mode is optimal. 
Some people are using undo+selection, others prefer erase+undo, etc.

It may differ even for same person depending on use case. For example, when zoomed both eraser (too big) and selection (bugged) are unusable.

**Comment by Tridens92** [comment]
@ddvk, the options you list would be great, even if the double-click isn't really an option due to lag.  You've listed plenty of single-click choices here that would be great!

**Comment by Tridens92** [comment]
Oh my gosh, @ddvk !  This patch_16.1.03 is *incredible*!  The new options, especially for Lamy, make my work so much more effortless.  All the toggles in the hacks menu provide so much customization, and the menu, graphically, looks amazing and fits so much better with the rM UI.  It looks like it's native!

Well done, and deep thanks for making my work day so much more productive and fun.  It would be a blessing any time, but in the challenges of COVID living it makes more difference than you can imagine.  Thank you!

**Comment by ddvk** [comment]
👍

**Comment by AdamSLevy** [comment]
Thank you again for implementing this. The double click to undo is very useful.

**Comment by ai212983** [comment]
Wait, don't close it, we need it implemented for rM2 too!

**Comment by AdamSLevy** [comment]
My bad. Thanks.

**Comment by ddvk** [comment]
ah sure, i was just waiting for bug reports

**Comment by ai212983** [comment]
Just checked 16.2.02, not sure if it works properly.

**Erase: Lamy Button Hold, Lamy Toggle Last Tool.**
On click or hold switching to Erase. When released stays on Erase, until next click/hold.

**Erase: Lamy Button Click, Lamy Toggle last Tool.**
On click or hold switching to Erase. When released switches back to drawing. 

**Erase: disabled, Lamy Toggle Erase**
Can't find the way to erase with button.

**In all cases** 
Can't find the way to switch to Last Tool. Undo works fine with double click.

**Comment by ddvk** [comment]
For the last tool to work, you have to click on "Lamy Toggle Last", (then the button will show toggle erase and the erase hold will be disabled). the lamy button switches the last 2 tools in this mode (or select).

you can't have erasing and switching tools at the same time

(maybe I could improve it to hold to erase with switch tool if short press e.g if you just press it, then it is switch tool  and a longer press > 300ms erase hold)


> `Disable Buttons` setting probably makes no sense on rM2.
yes, but then maintinging it is even more cumbersome

**Comment by ai212983** [comment]
> (maybe I could improve it to hold to erase with switch tool if short press e.g if you just press it, then it is switch tool and a longer press > 300ms erase hold)

Yeah, I thought this was an idea.

> For the last tool to work, you have to click on "Lamy Toggle Last", (then the button will show toggle erase and the erase hold will be disabled). 

So when it shows "Lamy Toggle Erase" it actually toggles Last Tool? Will check tomorrow, but it's kinda weird... Ages old "play/pause" button problem lol.

**Comment by Tridens92** [comment]
Yes, I'm LOVING the new tools, but having similar problems with
understanding how to toggle things.  I've not made any suggestions because
I'm not immediately sure what to suggest differently. :)

The Play/Pause analogy is a good one!

**Comment by ai212983** [comment]
Confirming Last Tool works as described.

 I've noticed the other thing though. Now it's counter-intuitive to have tool icon removed in minimized view.
It is not a problem with manual tool selection, because memory updates which tool is now will be selected, but with pen button it is a bit disorienting.

**Comment by ddvk** [comment]
you can switch to zen mode by long pressing on the menu icon

**Comment by ddvk** [comment]
i think we can close this one
