### ISSUE TITLE
rM2: Zen mode touch gestures for currently button-press-only features

### ISSUE THREAD

**Issue by chimpdude** [ddvk/remarkable-hacks#93]
Hey! So this is possibly a big, hairy feature request/enhancement, but hopefully it won't be!

Just got the reMarkable 2 and as great as it is, unfortunately a lot of the extra and _extremely_ useful functionality offered by Zen mode is no longer possible on the rM2, thanks to the lack of physical buttons.

I was wondering if any of Zen mode's features could be implemented using touch gestures, or if there are any plans for that already?

Here's a little list of some ideas I had:

- long-press on the pen icon when the menu is minimized: possibly toggle between most recently used pens, or the pen-eraser toggle 
- 2-finger swipe up and down are already taken, but 2-finger swipe left or right currently don't have any functions mapped, so those could possibly be Undo or toggle pen color
- Double-tapping and/or long-pressing the bottom corners could have some functionality (unless those would be too easily triggered by accident)
- Koreader has a lot of other gestures that are possible that could serve as inspiration

I came up with these after like 2 minutes of brainstorming, so just some rough ideas. :)

**Comment by ddvk** [comment]
sure, i'll add some gestures for pen toggling

**Comment by chimpdude** [comment]
Wow, that's great! Ooo, that would be a clever gesture for pen toggling. I'm (and I'm sure others are) super excited!

**Comment by mig2000** [comment]
Love all of these ideas. Let me know if you need any help. Thanks

**Comment by ddvk** [comment]
the gestures area is under the menu icon (more or less):

swipe up  to toggle last 2 tools  
swipe down tool/eraser  
swipe right undo

**Comment by chimpdude** [comment]
This works wonderfully! I love the gesture choice. 

One thing I noticed - if I open up a notebook, put it in zen mode, and try to toggle last 2 tools, it doesn't do anything. If I choose a different pen, then it will start working. I'm guessing that's because for a specific notebook, only the last tool is saved between sessions rather than the **last 2 tools**, right? Not a big deal other than the fact that I thought the pen toggling wasn't working at first, until I realized that I didn't have a "last used tool" saved yet. XD

**Comment by jamarier** [comment]
> long on press on the icon is already taken by switch to zen mode
> 
> the gestures area is under the menu icon (more or less):
> 
> swipe up to toggle last 2 tools
> swipe down tool/eraser
> swipe right undo

Excuse me, I can't follow the instructions (on rM2)

I select Zen mode and hide menu. After that I try to swipe down (with one finger) from upper left corner and... nothing.
I've tried with zen mode and showed menu, and nothing too.

Please, can you write detailed instructions about how to swap between eraser writing tool?

Thanks.

**Comment by digital-tinta** [comment]
Hi.

I am having the same issues has jamarier https://github.com/ddvk/remarkable-hacks/issues/93#issuecomment-721770591
Let me be more specific to help you. I am running rM2 with 2.4.1.30-patch_16.2.01-0-g5eda524.

**If I do the following a) write with pencil; b) switch to selection tool. Then, in zen mode with menu hidden:**

1) If I swipe up (bottom to top) near the zen mode icon, it switches to the pencil. However, if I swipe up again it switches to the erarser;

2) If I swipe down (same area where I just swiped up), nothing happens

3) If I swipe right (coming from left to right), again nothing happens, ie, the undo function is not triggered. 

**If I do the following a) write with pencil; b) switch to a fineliner. Then, in zen mode with menu hidden:**

1) If I swipe up near the zen mode icon, it switches immediately to the erarser. It does not go back to the pencil (above it did);

2) If I swipe down (same area where I just swiped up), nothing happens

3) If I swipe right (coming from left to right), again nothing happens, ie, the undo function is not triggered. 

If you could look into these issues, it would be much appreciated. And thanks a zillion for your awesome patches!

**Comment by tsang** [comment]
+1 on report of gesture not working.

**Comment by folofjc** [comment]
For those on rM2, I am assuming you don't have the black pen? When I am in Zen mode, I erase by flipping pen over, so the major gesture I am missing is swapping between two tools and undo.

**Comment by digital-tinta** [comment]
> For those on rM2, I am assuming you don't have the black pen? When I am in Zen mode, I erase by flipping pen over, so the major gesture I am missing is swapping between two tools and undo.

Yes, it's true. But nonetheless, the eraser tool allows for "precision" deletion with the marker tip, which is harder with the marker eraser.

**Comment by b4be1** [comment]
There is one subtle bug in the interface: switching between pens is not working after I switch from eraser to pen using the "toggle write/erase" gesture. However, if I switch from eraser to pen using the pen switching gesture, then pen switching works as expected. So, it's probably an issue with keeping a stack of pens when toggling the eraser.

**Comment by ddvk** [comment]
thanks,i ll fix it

**Comment by chimpdude** [comment]
@ddvk I think the latest patch fixed it - thank you! @b4be1 would you agree?
Also, the undo/redo at the top of the page is a great enhancement. I like it a lot more than swiping left/right in the tiny box below the menu icon.

**Comment by ddvk** [comment]
i think this is fixed
