### ISSUE TITLE
What's the story with the source?

### ISSUE THREAD

**Issue by Zemnmez** [ddvk/remarkable-hacks#94]
hey, annoying to put this in a github issue I know, but I was asked to help install this and I don't understand what the deal is with installing binary patches. Did you make these editing the production binary? As in -- you have no build files at all to generate such patches myself?

**Comment by Eeems** [comment]
https://github.com/ddvk/remarkable-hacks#why-is-this-not-open-source

**Comment by ddvk** [comment]
what @Eeems wrote. i edit the production binary and have no other sources, thus it all falling under the rM copyright.
