### ISSUE TITLE
New version shipped with RM2

### ISSUE THREAD

**Issue by fishyai** [ddvk/remarkable-hacks#95]
Hi,

I'm trying to install the hacks over ssh. When I run `cat /etc/version`, I get `20200914090635`, which is super close to the latest one in the patch, but not quite the same. My device says that it's running `2.3.1.27`, but the patch obviously fails because the version doesn't quite match. 

I'm new to the Remarkable world and excited. Is this typical where there are multiple system versions for the same OS version (i.e. the long string `20200914090635` vs `2.3.1.27`?

Thanks a lot for this project and for your help!

**Comment by mig2000** [comment]
Don't do any install of any hack as release 2.4 is out and most of the items might not work and might need update.

**Comment by ddvk** [comment]
it wasnt typical, until now

**Comment by ddvk** [comment]
btw, if the hash of xochitl (do `sha1sum /usr/bin/xochitl` is the same i can add this version in the patching

**Comment by ddvk** [comment]
it seems i've already added it,try again, closing this issue
