### ISSUE TITLE
Support for rm Version 2.4

### ISSUE THREAD

**Issue by dstango** [ddvk/remarkable-hacks#96]
Seems like a new version 2.4 of the rm software is starting to roll out ...
hopefully the hacks can get patched earlier than I'm due for my update ;-) ...

**Comment by ddvk** [comment]
oh, not again :>

**Comment by ishanina** [comment]
I got the update, is there anything I can do to help?

**Comment by ddvk** [comment]
yes, paste: `cat /etc/ersion` and `sha1sum /usr/bin/xochitl`

**Comment by crisandria** [comment]
I also have 2.4.0.27   hope this helps

cat /etc/version   =  20201016123042        
sha1sum /usr/bin/xochitl   = 797f58ed93d2e22e7d77fcd9de6c6eb5d49a3a7f  /usr/bin/xochitl

**Comment by ishanina** [comment]
cat /etc/version  = 20201016123325
sha1sum /usr/bin/xochitl = 891e06535c0ae742eeaa3b9a20e9ff03d0f659d3  /usr/bin/xochitl

**Comment by ddvk** [comment]
here you go, test if it works

**Comment by ishanina** [comment]
Worked for me, thanks!

**Comment by crisandria** [comment]
Works for me, thank you so much.  I've been missing it these past few days.

**Comment by Cleonwang** [comment]
rm1 version: 2.4.1.30
cat /etc/version =20201028164335
sha1sum /usr/bin/xochitl =336529ce6e7ef9d6fadd30872708556ca8711f0b  /usr/bin/xochitl

**Comment by ddvk** [comment]
ok, added this one as well

**Comment by manuelinux67** [comment]
> ok, added this one as well

I thank U so much, for all U do for us. Without U, there would b no reason to use the rm for me. Thank U thank U and thank U again.

**Comment by Tridens92** [comment]
My continued thanks as well, @ddvk .  Add me to the list of people who would be glad to donate something to you for your rM development.  If there's a way for us to do that, let us know !  We appeciate your work and the difference it makes for us every time we pick up our reMarkable (which for me is all the time!).

**Comment by pstemper** [comment]
There is a way..  On this issue list, if you click the SPONSOR button near the upper right, you can "sponsor" ddvk for all the hard work he is doing on this project.  :)

**Comment by Tridens92** [comment]
Done!  Thanks for pointing me that way, @pstemper !
