### ISSUE TITLE
accidental page swipe

### ISSUE THREAD

**Issue by EERCrso** [ddvk/remarkable-hacks#97]
Hi,

your hack is awesome I have how ever one issue with it. very often when I  write I put my wrist on the screen. Because page turns in single click (tap) on the screen my wrist accidentally changes the page. This could be easy solved by swiping the page with double click instead of one click.

**Comment by ddvk** [comment]
you mean in reading mode?

**Comment by EERCrso** [comment]
Yes reading mode

**Comment by ddvk** [comment]
well, reading mode is for reading, the only difference is page tapping and the hidden icon

**Comment by ddvk** [comment]
it is too much trouble adding double taps
