### ISSUE TITLE
Thumbnail/preview for PDFs is always first page?

### ISSUE THREAD

**Issue by shreevatsa** [ddvk/remarkable-hacks#98]
I don't know if this is related to installing remarkable-hacks or an unrelated issue with some software update, but I've started to notice that for PDFs, the thumbnail (preview image) that is shown on the main screen (etc) (in Grid view) is that of the first page of the PDF, instead of the page I was last reading. 

Is this a consequence of this patch? I prefer seeing a thumbnail of the last opened page, just as with notebooks. (I can imagine why for PDFs that have a distinctive “cover page” always showing it as a thumbnail could be preferred by some, but most of my PDFs are not like that.)

(I see this happen with Version 2.3.0.16-patch_12.11.0-g7812cfb, and don't see this with the stock Version 2.3.1.27.)

**Comment by ddvk** [comment]
yes, by design

**Comment by shreevatsa** [comment]
Oh alas. I prefer it the default way, but this is not a big deal; I won't ask for this to become an option or whatever. :-) Thanks for all the work!

**Comment by shreevatsa** [comment]
Actually, I notice there's already an option: to "Show First Page" or "Show LastOpened Page", which shows up for both notebooks and PDFs, but seems to take effect only for notebooks… could it be changed to work for both?
